### ISSUE TITLE
miningpoolhubstats issue

### ISSUE THREAD

**Issue by airwalker1** [nemosminer/NemosMiner#275]
Reportstatus.ps1 is missing. I added it from MPH but its still got some issues. THANK YOU SO MUCH for this!

**Comment by kevharper** [comment]
Added it from MPH?  Could you clarify?

**Comment by kevharper** [comment]
Ah  you mean MPM  not MPH :)

**Comment by airwalker1** [comment]
Well,  I mean the fork of MPM through MPH :)

**Comment by nemosminer** [comment]
Nemos is not made for a single 970....

**Comment by airwalker1** [comment]
Yes, same issue. The script is calling for reportstatus.ps1 but it is missing:

if($MPHApiKey) {
        .\ReportStatus.ps1 -WorkerName $WorkerName -Version $Version -ActiveMiners $ActiveMinerPrograms -Miners $Miners -MPHApiKey $MPHApiKey
    }

Just adding it from MPH does not solve.

**Comment by kevharper** [comment]
Same here

**Comment by nemosminer** [comment]
@kevharper correct adding it from MPH will not work as i use incluse.ps1 and MPM uses include.psm1 
i'll try sort this out

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.4.2/archive/master.zip  try this one

**Comment by airwalker1** [comment]
Sadly no. It doesn't show up with real-time stats on MPH just as before but the errors are much less according to the log: 

--------------------------------------------------------------------------------
Last Refresh: 02/16/2018 00:31:10
Sleep 30 sec
--------------------------------------------------------------------------------
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Loading miners..
profit workername miners
------ ---------- ------
       server     [...
       server     [...
1BTC =  10095 USD

PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."

**Comment by kevharper** [comment]
Any lucky getting MPH Stats detail reporting to work yet?  I will like to get started back on a profit switcher instead of running stright up DSTM.

**Comment by airwalker1** [comment]
He added the help wanted tag. I think he's waiting for the guy that created it to look at what the issue is. Just gotta be patient.

**Comment by nemosminer** [comment]
yeh sorry we working on it now i'll add support back once i have it running correctly sorry about that

**Comment by kevharper** [comment]
No problem.  Appreciate your great work!!!

**Comment by nemosminer** [comment]
done try new NemosMiner-v2.5 has profit tracking for every pool including working mining pool hub stats

https://github.com/nemosminer/NemosMiner-v2.5/archive/master.zip

Best Regards 
Nemo

**Comment by 8-cloud** [comment]
Did anyone managed to get minigpoolhubstats to work?
I only get extra title "Worker Status (Submitted by MultiPoolMiner) and a Total, but it is always 0.00000000 (0.00 EUR)
Thanks for feedback.
Best Regards,
8C

**Comment by mistorincognito** [comment]
i have same issue

Worker Name | Miner (Algorithm) | Pool | Type | Uptime | Reported Hashrate | Average Hashrate | BTC/Day
-- | -- | -- | -- | -- | -- | -- | --
TOTAL | 0.00000000 (0.00 USD)

**Comment by airwalker1** [comment]
Same issue as well. It does not seem to be reporting anything.

**Comment by nemosminer** [comment]
testing myself atm

**Comment by nemosminer** [comment]
can you also test this please update yesturday: 
 https://github.com/miningpoolhubstats/NemosMiner/archive/master.zip

**Comment by airwalker1** [comment]
Tried both, still the same - no stats being reported. I don't know what a proper miner.log looks like when it works but the only thing I get in it when I assume it's posting is my workername and dots:

Loading miners..
closing current miner and switching
Launching Prerun:  .\Prerun\default.bat
       **ID=server  [...**
1BTC =  9870 USD

**Comment by 8-cloud** [comment]
Same here, tried both, no stats.

**Comment by Braintelligence** [comment]
Is 3.0 supporting mphstats properly currently?
