### ISSUE TITLE
Ahashpoolplus not working!

### ISSUE THREAD

**Issue by jcabello7** [nemosminer/NemosMiner#283]
Hi all! 1st, yhanks to nemos and all contributors for your work!
Ahaspoolplus was working great for me, but just now stopped working.
Nemosminer is showing:
Loading pool stats...
Can't connect to pool.
Retrying connection

All the time. Maybe the calculated profits are down?

Thanks

**Comment by MrPlusGH** [comment]
The site is under high stress, we're not scaling.
I had to take the service down.
