### ISSUE TITLE
Feature Request: Add CPU mining

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner#400]
Given the comprehensive profit calculations/pool switching available in 3.0, can we also add CPU mining (Cryptonight, Cryptonight Lite, HODL, M7m, etc)

**Comment by gak45** [comment]
second this and add yescryptR16 please!

**Comment by bit2017user** [comment]
It will be great if we can have it all in 1 place

**Comment by Quake4** [comment]
Nemo remove cpu mining at begining after fork multipoolminer.
MindMinder have support cpu mining from begining and support yescryptr16 at zergpool.
https://github.com/Quake4/MindMiner

**Comment by gak45** [comment]
No obvious way to see donation time and where it is pointing in the code? Check. No obvious way to pick alogs and not run all supported alogs? Check. Auto updates itself without any input from user? Check. Claiming all new and not based on others works? Check. Low reputation on bitcointalk? Check. 

Yeah... thanks but no thanks. Think I will stick to reputable options.

**Comment by jjziets** [comment]
How to make a cpu only fork for swrichers?

**Comment by MrPlusGH** [comment]
no need to fork. you can disable NVidia in config.
