### ISSUE TITLE
Miners crash and the system fails. 

### ISSUE THREAD

**Issue by Nickfost** [nemosminer/NemosMiner#407]
For whatever reason @nemosminer just closes [this issue](https://github.com/nemosminer/NemosMiner-v3.0-windows/issues/396) (#396) without providing any help and expects donations.

**Comment by MrPlusGH** [comment]
If your system crashes, no one gets donations :)
Could you try without OC ?

**Comment by Nickfost** [comment]
I dont have any overclock

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v3.0-windows/issues/396

driver newer than 388? i use 390.65 personally

**Comment by nemosminer** [comment]
i just download newest master v3.0 is running through bench marking now no issue with any ccminer so far...

**Comment by Nickfost** [comment]
currently using 388.13. i think i saw this either in yours or someone else's documentation, why is that  bad version for mining? i'll update now and report back.

**Comment by nemosminer** [comment]
thankyou also re download fresh v3.0 changes been made 2day

**Comment by Nickfost** [comment]
two hours of downloading the drivers seems the benchmark is working now, will report more in the morning

**Comment by nemosminer** [comment]
my bench marking on test rig has complete no problems.. all algos benchmark and is now mining away on x16r all is well

**Comment by Nickfost** [comment]
We've had connection issues all night, my benchmarks did not complete. i've got 6 more rigs in a datacenter and i'll test on those too today.

**Comment by Nickfost** [comment]
it now seems xmrig is failing.

**Comment by Nickfost** [comment]
all i get is "failed" does the miner output not get captured?
