### ISSUE TITLE
ZergPoolCoins?

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner#408]
Any chance of adding in ZergPoolCoins... and ZergPoolCoinsPlus pool options? Would be nice to not have to mine crap coins along with profitable ones. :)

**Comment by nemosminer** [comment]
on to do list

**Comment by syrm** [comment]
what's ZergPoolCoins ?

**Comment by gak45** [comment]
@syrm it would allow nemos to mine only specific coins and not the crap coins that are not as profitable in a given alog. eg on x17 it would ping the server and see that verge is MUCH more profitable than the rest and only mine verge.... thus greatly improving profits. HOPE this is very, _very_ high on nemos' "to do list"!

**Comment by nemosminer** [comment]
no really

**Comment by gak45** [comment]
damn, that is a shame. it really could make a decent pool into a great one! Willing to set donate to 120 for a week if you put it... 'higher' in your list. ;)

**Comment by lostmind84** [comment]
Hello there, i was looking for the same feature (specify which coin we want to mine for for each algo on ZergPool), hope you will add it in a future release.

**Comment by nsummy** [comment]
If the coins are autoconverted does it really matter which coin you are actually mining?  I am assuming the pool already auto switches to the most profitable coin for each algo.

**Comment by Quake4** [comment]
Gak45, You can try MindMiner. Its has this feature from version [1.25](https://github.com/Quake4/MindMiner/releases/tag/v1.25) from 17 march 2018. See [SpecifiedCoins](https://github.com/Quake4/MindMiner/blob/master/Config.md) at configuration manual.

**Comment by gak45** [comment]
Thats is a very sensible implementation - hardcoding in profitable default coins. Hope nemos sees it and does something similar... as - and please dont take this the wrong way - your app has a 1% hard coded fee. I like the freedom of being able to go higher to reward hard work... cant easily do that with a hard coded fee... well I can as its "$FStart = !$global:HasConfirm -and ($Summary.TotalTime.Elapsed.TotalSeconds / 100 -gt $Summary.FeeTime.Elapsed.TotalSeconds + [Config]::FTimeout)" but doing math to change a fee is never a good idea. Id be just as likely to change it to
$FStart = !$global:HasConfirm -and ($Summary.TotalTime.Elapsed.TotalSeconds / 0.001 -gt $Summary.FeeTime.Elapsed.TotalSeconds + [Config]::FTimeout) as you made me dick around with your code. :P

**Comment by Quake4** [comment]
Fee declared as 1%. You may use mindminer or use other software. Please go to github or bitcointalk.
Nemosminer have fee too.

**Comment by gak45** [comment]
Yes but nemos does not hard code it. On any given day I can simply change it from half a percent to one to hell 20 if I want to... all without figuring out the math as it is MINUTES. Yours... not so much. Id have to change your code. Plus 14.4 minutes is greedy. Is the greed worth it? Maybe. But would I take a chance on another program and deal with bench marking again to find out? Probably not.

**Comment by judgebob** [comment]
I like the idea gak45.  I think this will be a great feature to add later on.   That way you can eliminate mining the coins that are not a profitable and don't sell as easily on the exchanges.
