### ISSUE TITLE
Endless benchmark

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#410]
![nemos-endless](https://user-images.githubusercontent.com/36886126/37552053-587a56fa-29be-11e8-9006-d2368247922d.png)
Try version 3.0, but something strange during benchmark, it never ends

**Comment by nemosminer** [comment]
thanks i'll run nice hash benchmark now see if i can replicate error

**Comment by g5-freemen** [comment]
single GTX 980
i'll try it later, but look like the same thing happens to other algorythms (DSTM)

**Comment by nemosminer** [comment]
no support for 980 readme 1060 to 1080ti only
