### ISSUE TITLE
x11gost Error NiceHash

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#411]
Can't benchmark x11gost algo on nicehash. It saying failed and exiting immediately.

**Comment by yuizen** [comment]
On the new version there are 2 x11gost algo. Other one is the one that is keep failing.
![5wx7qp5 - imgur](https://user-images.githubusercontent.com/37470062/37553827-9577b9ec-29e8-11e8-8770-c12ad42bbc15.png)

**Comment by nemosminer** [comment]
re download that has been fixed

**Comment by yuizen** [comment]
I re-downloaded and it still have 2 x11gost algo. Can't figure what I am doing wrong. I followed the instructions.
![nemos](https://user-images.githubusercontent.com/37470062/37558084-f180a7d2-2a27-11e8-8d64-0d25f50d5203.png)

**Comment by TGM8599** [comment]
I finally activated the NiceHash internal wallet and came across the same issue this morning.  Which miner ps1 should be flagged to run x11gost?
