### ISSUE TITLE
HSR don't Benchmark (Error)

### ISSUE THREAD

**Issue by Riones** [nemosminer/NemosMiner#413]
Hello again.
I have mining on Zergpoolplus only, and I put all algorithms by default... But the HSR don't Benchmark, always give me an (Red) error of connection port...wait 30s, and the same error... wallays.
Can you help me please.

Thank you.
Best regards.

**Comment by nemosminer** [comment]
no error on my end.. https://imgur.com/a/NPuCl

**Comment by Riones** [comment]
You are lucky 😁
I have an error... Look please.
![screenshot_2018-03-17-17-26-07-043_com google chromeremotedesktop](https://user-images.githubusercontent.com/36863608/37558231-a3254512-2a08-11e8-8adf-caaf60a08877.png)
