### ISSUE TITLE
Miner crashes of all kinds and instability issues ...

### ISSUE THREAD

**Issue by McBlocked** [nemosminer/NemosMiner#414]
First off all , Thank you very much for your devoted work and effort to achieve such a programmed masterpiece.

i have been mining peacefully with 5 1080 Tis for a while with +110 core clock , +310 memory and 80% TDP 
until i added the 6th card i decided to download the latest nemosminer and start fresh 
as soon as i started the miner it lasts around 20 to 30 seconds and crashes right away 

(throws a skein512_cpu something and stuck in there forever)
i removed all the oc settings and it started to mine x17 for some hours with no problem then crashes again with a cpu validation issue or quart512_cpu..  function error or anything 

mining phi wont even complete a whole 30 seconds without crashing

it crashes too many times that i cant even make a 0.0003 btc a day

please let me know if i am missing something or if there is anything wrong with the miner

mobo : assus mining expert
cpu : celeron 7th gen
gpus : 6 1080 Tis
driver 391.01

[switching.log](https://github.com/nemosminer/NemosMiner/files/1821790/switching.log)
[miner.log](https://github.com/nemosminer/NemosMiner/files/1821791/miner.log)

![2018-03-17 at 6 30 39 pm](https://user-images.githubusercontent.com/37478731/37557225-95a14d28-2a12-11e8-9970-bac7e2a84ffe.jpeg)

**Comment by nemosminer** [comment]
thats not a NemosMiner error its either you MB or Bios setting alot of MB's work well with 5 gpus but not 6... what MB are you using
