### ISSUE TITLE
A suggestion of a new monitoring function\feature 

### ISSUE THREAD

**Issue by McBlocked** [nemosminer/NemosMiner#415]
can you please add a line that instead of restarting the whole system it restart the cmd window (running mining script) or restarting the miner that crashes and if it detects that the gpus are working and if not Then restarting the system, so the people that has mining problems and plagued mining with ccminer problems (like me) can atleast mine anything without babysitting 24\7

**Comment by nemosminer** [comment]
you need to suit out your rig.. i can't do it for you there is no crashes on my 6x1080ti rig...
