### ISSUE TITLE
2 x11gost 1 fails benchmark

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#416]
I re-downloaded the whole v3.0 just now and tried again. Still it's showing me 2 x11gost and 1 is always failing benchmark it's just looping trying to benchmark the algo. I tried editing the one that is not working (ccminerAlexis78.ps1) and removed this line ["x11gost" = " -i 21 -d $SelGPUCC --api-remote" #X11gost] so the miner won't benchmark it again and continue and it did continue. I don't know if I did something wrong but I just followed the instructions.

![nemos 2](https://user-images.githubusercontent.com/37470062/37558325-b5a0c360-2a2b-11e8-8b3c-e072ca7e86ee.png)
![nemos](https://user-images.githubusercontent.com/37470062/37558326-b5c88c38-2a2b-11e8-879a-d8d57c574d46.png)

**Comment by nemosminer** [comment]
thankyou i'll fix now

**Comment by nemosminer** [comment]
done https://github.com/nemosminer/NemosMiner/commit/f58d081df4743f1c581420780e9596618ac2581e

**Comment by yuizen** [comment]
Thanks for a very fast reply and action. Glad to help. I’ll test it tomorrow I’m kinda beat up.
