### ISSUE TITLE
Changing Payout Coin ZPool

### ISSUE THREAD

**Issue by pitviper79** [nemosminer/NemosMiner#418]
This may be just me, but when I change the payout coin on zpool (selected along with zpoolplus and MPH) from BTC to LTC, it saves in the config.json but the miners still use c=BTC. I was able to over come this by changing the passwordcurrency in the .ps1 file, but may catch some unaware.

**Comment by uprise88** [comment]
Same here

**Comment by MrPlusGH** [comment]
Thank you!
This is a bug in zpool.ps1
Line 47 is:
		    Pass          = "$($Config.PoolsConfig.$ConfName.WorkerName),c=$Passwordcurrency"
And should be:
		    Pass          = "$($Config.PoolsConfig.$ConfName.WorkerName),c=**$Config.**Passwordcurrency"

Will fix in next release.

**Comment by uprise88** [comment]
This is working, last thing i need to be fixed is fiat currency displayed in console, is selecting EUR it still show USD

**Comment by MrPlusGH** [comment]
That last one is already queued for next version: [https://github.com/MrPlusGH/NPlusMiner/issues/30](url)
Thanks for the testing and feedback

**Comment by nemosminer** [comment]
thankyou i have updated zpool i will update rest of pools in 2hours when i get back from work and run it through test rig to confirm LTC  working

**Comment by MrPlusGH** [comment]
@nemosminer we should only update pools which support other currency for payout than BTC I guess.

**Comment by nemosminer** [comment]
@MrPlusGH yes correct
