### ISSUE TITLE
Endless run again

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#419]
Just want to show that possible reason of endless benchmark run. I have 1 "unsupported" GTX 980, but why benchmark runs with 0,1 (two) CUDA devices?

![wrong-number-cuda-devices](https://user-images.githubusercontent.com/36886126/37563797-a85ca228-2a99-11e8-8e1c-9faa4987f4d1.png)

**Comment by nemosminer** [comment]
in config click detect gpu, the save config, exit NemosMiner, Re open and it should now run with your saved config file eg. -d 0 (1 GPU)

**Comment by g5-freemen** [comment]
update miner, reset settings, detect gpu, then save config, exit NemosMiner, Re open but it doesn't help :(

also i don't understand why in benchmark used JP server but in settings EU
![nm1](https://user-images.githubusercontent.com/36886126/37603222-29d5aa88-2b9f-11e8-9448-4daf5ccc326e.png)

**Comment by g5-freemen** [comment]
delete --cuda-launch=8x120 from XMRig.ps1 and look like it helps

**Comment by yuizen** [comment]
About the location, this is a very long time issue with Nemo miner. Miner will not accept EU, use EUROPE instead.

**Comment by g5-freemen** [comment]
try to set USA, but nothing changes, NemosMiner uses JP server

**Comment by nemosminer** [comment]
Xmrig done thanks g5-freemen location for USA should be "US"
