### ISSUE TITLE
Feature Request - Excavator empty wallet address fix

### ISSUE THREAD

**Issue by Zarce** [nemosminer/NemosMiner#420]
Hello. 
In the previous version i use excavator for Neoscrypt and another few scripts. They work better than ccminer or HSRminer, but in the last version V3.0 i see empty wallet and it mining with loss. Can you fix this please.

Thank you !

**Comment by nemosminer** [comment]
thanks  looking into excavator atm is there any other algo apart from neoscrypt that you find it faster?

**Comment by monkeyguy** [comment]
Slightly faster than ccminer on keccak too, but neoscrypt is the significant one (almost 10% faster for me). I am not having the problem mentioned by Zarce though. I took the ExcavatorNvidia1.ps1 file from the latest release of MPM, edited the "Include" reference at the top to match the other nemosminer files, and put it in my nemosminer Pools folder, also manually downloaded excavator and put it in Bin. Seems to be working fine, although the 2 thread ps1 (ExcavatorNvidia2) from mpm crashes when run by nemosminer.

**Comment by gak45** [comment]
Thanks!
Neo and Nist are the two big ones for me... though its equihash is also faster on _some_ of my rigs as well.

**Comment by borzaka** [comment]
Algo's that are faster with Excavator in my case:
- NeoScrypt
- Lyra2RE2

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/commit/998411fb911b47b42a56cf7d50641fea59a14729

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/433
