### ISSUE TITLE
very often stops responding and closes only through Task Manager

### ISSUE THREAD

**Issue by valeriy-efimov** [nemosminer/NemosMiner#421]
![image](https://user-images.githubusercontent.com/5989188/37569071-ea27698a-2ae5-11e8-82be-cdbe8c4307a9.png)

**Comment by MrPlusGH** [comment]
This is known issue (Category small)

It does say "Not Responding" when doing web requests. I have not found a way to fix this yes.
If you wait a little bit until the web request ends. everything is OK and the UI responsive again.

Steps when this occur generally :
   - Loading BTC Rate
   - Loading pools
