### ISSUE TITLE
Q: ZergPool Estimated BTC/D

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#425]
I'm just confused why there are two the in there (red circle) and BTC/D is added up. Is it really my per day or only one of it? FYI there is only 1 miner that is running. I just can't believe the per day it is saying tell me how it it works. Thanks

![nemos 3](https://user-images.githubusercontent.com/37470062/37576348-6b889a9e-2b45-11e8-8e7c-e259cc11c707.png)

**Comment by MrPlusGH** [comment]
You have selected zergpool and zergpoolplus. so you're actually seeing double values.
Select only zergpool plus
