### ISSUE TITLE
High CPU use in 3.0, 2.5.2

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner#428]
On a Core i5 4670k, I typically run XMR-Stak (3 threads) while running Nemos Miner. I note that using 3.0 uses up 25% CPU pretty continuously on its own, and correspondingly drops my XMR-stak CPU hash rate. 2.5.2 peaks up to 25% CPU only when "active" - i.e. not sleeping. Is there any way to reduce this CPU overhead in 3.0? Can I configure longer sleep times in the GUI? Thanks

**Comment by MrPlusGH** [comment]
Thanks for the details!

This is a known issue and is work in progress on my side for performances improvements
New versions have background jobs for BrainPlus and Earning Tracker.

If this is really causing you troubles at this time, there are a few things you can do (Untill I fix the perf issue ;) )

1.  Pick a larger interval
2.  You can stop using earning tracker > config.json > "TrackEarnings":  false,
3.  You can NOT use the Plus option > Will not start BrainPlus jobs
4.   If you still want to use Plus, in BrainPlus folder, edit Config.xml and change Interval to something longer

**Comment by yuizen** [comment]
I thought there are no CPU miner yet. Maybe you are mistaken.

**Comment by Tesla74** [comment]
Not worth mining on CPU

**Comment by NoKwarl** [comment]
I know there is no CPU miner support within Nemos Miner yet. However, nemosminer 3.0 appears to be using more CPU than previous versions, consistently, at least for me.

**Comment by NoKwarl** [comment]
I'm investigating this more. It looks like 2.5.2 zpoolplus is using a full core (25%) CPU for about 140 seconds, followed by 30 seconds of downtime, repeated over and over (while XMR-Stak-CPU is running separately on 3 threads). When XMR-Stak-CPU is off, the same thing occurs, but 30% CPU gets used for the 135-140 seconds. All of this is coming from the Windows Command Processor- one of the Powershell instances under that. I'm going to guess that some monitoring process is locking the CPU for that period of time. Can someone look into this? Next post will be for 3.0 to confirm similar behavior.

**Comment by nemosminer** [comment]
i use celerons dual cores @2.8ghz on all my rigs they stay under %50 utilization...

**Comment by tiztrain** [comment]
@NoKwarl how many gpus are you running in your rig?

I sometimes get high fluctuations when I am running over 9 cards in one rig. With 11 cards my Pentium or i3 was sometimes hitting above 75 to 99% and I would often get a bad share along with it. With 9 cards it never really would go above 50%. Also Teamviewer can take up a nice % of cpu so it is initially better to benchmark and setup your rig without it.

**Comment by MrPlusGH** [comment]
@NoKwarl 

Forgot to thank you for the qualitative feedback which really helps here.

If you try this new version, I'd be interested to ear your feedback on the improvement you see on your rigs?

One thing to note as well is that the main process CPU consumption is also dependent on the number of enabled pools. The more you enable, the more it consumes to poll them all at each interval.
How many pools do you generally select?

**Comment by NoKwarl** [comment]
I'll check it out when I have the time to go around my virus scanning blocking the download (doesn't do this for NemosMiner probably because it downloads things separately after making the Defender exceptions- I would recommend doing that to enable easier install for NPlusMiner)
