### ISSUE TITLE
Reports error on Cryptonight

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner#430]
Yo Nemo. Fucking props to you guys for the new 3.0 version. Love the GUI and easy settings. But the miner comes up with this error 
![error](https://user-images.githubusercontent.com/32222070/37668917-d91f5a68-2c65-11e8-96c7-86e9f5d7c4ba.jpg)
I hope you can see this. I am guessing it's because I mine on Miningpoolhub and Nicehash on EU server, but give it a look. As far as I can teel it doesn't affect the miner.

**Comment by MrPlusGH** [comment]
Thank you!

Select -Unique is case sensitive.
`$AllPools.Algorithm | Select -Unique | ForEach`

Using Sort in place of Select will fix as Sort is not case sensitive...
`$AllPools.Algorithm | Sort -Unique | ForEach`

**Comment by tr1l3r** [comment]
Tnx m8. It was a bit difficult to find it, but the issue is fixed now.

**Comment by MrPlusGH** [comment]
Note that is does not break anything, this is just a display issue.
