### ISSUE TITLE
Feature Request: miningpoolhub plus

### ISSUE THREAD

**Issue by monkeyguy** [nemosminer/NemosMiner#431]
Is there a reason why brain plus option is only available for the pools that it is?

**Comment by MrPlusGH** [comment]
The problem with miningpoolhub is that price are updated ecery half hour due to Couldfare.
So plus does not really make sense until they change their API.

**Comment by monkeyguy** [comment]
I take it their API prevents a 24hr actual option as well?

**Comment by nemosminer** [comment]
yes atm we will look into miningpoolhub see what we can do....
