### ISSUE TITLE
Excavator

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#432]
Excavator

for supported Algos: 
    blake2s, decred, daggerhashimoto, equihash, lbry ,lyra2rev2, neoscrypt, nist5, pascal

note as Excavator is owned by "Nicehash" and has a EULA it is "NOT" enabled in "NemosMiner" by default if you would like to download and use it you will need to enable it yourself, 

in "Miners" folder  Edit : Excavator.ps1 

remove the # from the Algos you would like to use eg.

. .\Include.ps1

$Threads = 1

$Path = ".\Bin\Excavator\excavator.exe"
$Uri = "https://github.com/nicehash/excavator/releases/download/v1.4.4a/excavator_v1.4.4a_NVIDIA_Win64.zip"

$Commands = [PSCustomObject]@{
    #"blake2s" = @() #Blake2s
    #"decred" = @() #Decred
    #"daggerhashimoto" = @() #Ethash
    "equihash" = @() #Equihash
    #"lbry" = @() #Lbry
    "lyra2rev2" = @() #Lyra2RE2
    "neoscrypt" = @() #NeoScrypt
    "nist5" = @() #nist5
    #"pascal" = @() #Pascal
}

save

this example would Enable Excavator for Neoscrypt,Nist5,Lyra2v2,Equihash Algos

if you would like faster x17 and x16r more info here: https://github.com/nemosminer/NemosMiner/issues/375

**Comment by g5-freemen** [comment]
Maybe it possible to add to benchamark different miners for one algorytm? (like in Nicehash miner legacy).
For example benchmark equihash with ZM and Excavator miner, and then NemosMiner decide which is faster.

p.s. sorry for my english

**Comment by nemosminer** [comment]
dstm is faster

**Comment by wantafanta01** [comment]
thank god i found this, i did not want to have to settle for the hashrates i got using ccminer or any ccminer fork for neoscrypt.... i saw a 1.5MH/s boost to my rigs hashrate on neoscrypt after the 1.4.4a update

**Comment by kingyem** [comment]
I'm sorry but I couldn't find Excavator.ps1 in my Miners folder, am I supposed to get it from somewhere?

**Comment by nemosminer** [comment]
"Optional Miners" Folder
