### ISSUE TITLE
Test With 12 GPU RIGS

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#433]
my biggest rigs atm are 8 GPU rigs.. i have disabled all Alexis78  apart from Xevan...

testers wanted to test and give feed back on performance on 12 GPU rigs by default Tpruvot & KlausT are the Main Miners used, if your tests are successful and you would like more speed for the following algos: equihash, lyra2rev2, neoscrypt, nist5  to Enable Excavator more info here: https://github.com/nemosminer/NemosMiner/issues/432

**Comment by tiztrain** [comment]
On my 11 x 1060 rig I did not have a problem with 11 cards:
![image](https://user-images.githubusercontent.com/29892237/37695901-811971be-2d1e-11e8-8ac4-4d8f03ded4b1.png)

This is probably another issue:
My other rig is running 7 vega's and 3 1080ti's, the vega's aren't running on nemos but ethash tries to mine the vegas so I disabled it. 
I disabled the Alexis78 miner apart from Xevan as they came up with Windows graphics blocked error. Got the following result for the results of the 3 cards:
![image](https://user-images.githubusercontent.com/29892237/37696206-b649150e-2d20-11e8-9626-0e2cb0727d80.png)

A quick test on nemos 2.5.2 and the 1080ti's can mine ccminerAlexis78 LyraRE2,X17 fine. Any ideas?

**Comment by nemosminer** [comment]
thanks would prefer 12 card results : https://github.com/nemosminer/NemosMiner/issues/133

**Comment by Dekablade01** [comment]
`poly` from zpool is not working

**Comment by nemosminer** [comment]
fixed poly

**Comment by Braintelligence** [comment]
For some reason DSTM only uses first 6 GPUs when firing it up on my 13 GPU rigs. 
![grafik](https://user-images.githubusercontent.com/6761196/38054340-f71f9574-32d6-11e8-8383-1c5cf3de7d56.png)

I checked the optional miner folder for the 12 GPU miner ps1 but I didn't see any difference between the DSTM ps1 there and in the main folder.

**Comment by Braintelligence** [comment]
Looks like TPruvotskunk doesn't work for my 12/13 GPU rigs. It just doesn't start up.

**Comment by Braintelligence** [comment]
For some reason since the latest commit from 7th Mai I have issues with TPruvot on my 12+ rigs. Either it has become very sensitive to OC or something else is going on.
