### ISSUE TITLE
check card compatibility 750ti 950,970,980ti,1030,1050,1050ti  

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#434]
should now be working well on all these GPUS... can't test my self as i only have 10603gb and above.. 
testing and performance reports welcome

**Comment by g5-freemen** [comment]
Can retest last build on 980 if u want.

**Comment by tr1l3r** [comment]
Everything works well on gtx 970, so that is confirmed at least.

**Comment by thel3lue** [comment]
https://imgur.com/gUjZ95d
1050ti work fine
by the way when will update eth dual miner for nemosminer?
