### ISSUE TITLE
Low results

### ISSUE THREAD

**Issue by 8-cloud** [nemosminer/NemosMiner#436]
My results on 8 x 1080 Ti using NM v3 are almost 40% lower compared to NM v2.x !
Does anyone having the same issue?

Any suggestions how to fix it?

Regards
8C

**Comment by MrPlusGH** [comment]
Everyone have seen profit drop in the last two days whatever tool they use.
Look like the market is getting a little bit better today.

I do not think this is a product issue but really market related.

**Comment by g5-freemen** [comment]
**MrPlusGH**
+1

**Comment by 8-cloud** [comment]
2 rigs (8 x 1080 Ti each) one running NM v2.5, one NM v3 : NM v2.5 result almost 40% higher
I think benchmark is not OK, I also noticed that only 6 miners were downloaded...
Will try again on another pool
