### ISSUE TITLE
Wonky, strange PoolPlus issue

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner#441]
I have multiple rigs. All with 6 1080Ti cards. Both running the same OS, same board, same ram, same nemos config (latest release), driver versions.... same everything. Both rebooted at the same time.

Sooo how come rig 1's pluspool results are different than the rig 2s? IE it will see say x17 as being higher on rig 1 than on rig 2? Checked the benchmarks same results (even copied relevant stats folder from one rig to the other). Doesnt happen all the time but a good 5 times a day and has for weeks... even after nemos updates! Hell right now rig 1 is mining x17 on blazepool, the other is c11 on zerg!

Really... really weird behaviour. Since zerg is PPS would it better to remove the gremlin and use 'non plus' pool options? OR just yank Blaze and just use zergpoolplus?

Any help greatly appreciated as this is driving me nuts... like an itch I can not scratch!

**Comment by nemosminer** [comment]
i only mine on 1 pool.. i like to keep things simple..
