### ISSUE TITLE
Feature Request - Adding a code to check for the ccminer's actual functionality

### ISSUE THREAD

**Issue by McBlocked** [nemosminer/NemosMiner#450]
Hello Nemos :)

can you please add a code to check continuously if the ccminer or the miner program is working or not by looking for a process called "**WerFault.exe**" that opens automatically whenever ccminer.exe or an application stops and report an error like "skein512_cpu_setblock_80" in ccminer.exe case, so whenever it detects that it exists it takes a screenshot of the miner application and store it in the Scr folder in the Monitor folder and then restarts the PowerShell GUI or the script instead of windows falt correction software halting all mining to wait for a keypress.

the process location is:
C:\Windows\SysWOW64\WerFault.exe

Thanks very much for all the hard work

**Comment by MrPlusGH** [comment]
!

**Comment by tr1l3r** [comment]
Oh baby. This is what we need.

**Comment by Olegik-ah** [comment]
I think it dont needed... You just need make some settings to windows error reporting component.
Start - run gpedit.msc
Go to Computer configuration -> Administrative templates -> Windows components -> Windows error reporting
And set "Prevent display of the user interface for critical errors" to "Enabled".
Next time when ccminer or other program will crash it will not show any GUI - just close and dont wait for key press
Hope it helps!

**Comment by McBlocked** [comment]
@Olegik-ah Maaaaan 
If that worked thats gonna be awesome 
Im testing it already 👍

**Comment by OMGTAA** [comment]
@Olegik-ah I run a stripped down version of Win10 Home on all of my machines, and aparently Group Policy (gpedit.msc) isn't in home. 
Damned shame.

**Comment by UselessGuru** [comment]
> aparently Group Policy (gpedit.msc) isn't in home.

Not needed, Directly edit the registry with regedit... gpedit.msc is just a fancy editor for the policies hives in the registry.
