### ISSUE TITLE
Failed to open command file: miningpoolhub_Lyra2RE2_[username].[minername]

### ISSUE THREAD

**Issue by jsaltzman** [nemosminer/NemosMiner#453]
I am trying to use the optional Excavator miner. I moved the ps1 into my milder folder and uncommented the algorithms. When it runs, I get the following error:

Failed to open command file: miningpoolhub_Lyra2RE2_[username].[minername]_1_Nvidia.json

**Comment by nemosminer** [comment]
thanks Excavator may not be working with miningpoolhub atm  i'll do some testing i know its working on yiimp based pools and nicehash...

**Comment by kingyem** [comment]
I am having the same error with all of algos using excavator, noted that in the log tab, stratum was blank
![nemosminer_excavator_error](https://user-images.githubusercontent.com/35198970/37875547-8cc5b150-3073-11e8-8147-bfc9d00703f3.png)

**Comment by JimBrown** [comment]
Check your config file. You have a space at the end of your wallet address.
