### ISSUE TITLE
"Save Config" Close NemosMiner

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#459]
Maybe it possible to restart miner automatically after save config, without close & run by myself ?

**Comment by MrPlusGH** [comment]
You normally do not have to close and restart.
Config updates and taken into account the next cycle after Save Config is hit.

Did you find any occurrences of configuration updates requiring a restart?

**Comment by g5-freemen** [comment]
Ok, but maybe it possible to track 1 & 2 changes and restart automatically?
