### ISSUE TITLE
Question: CPU mining

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#464]
Sorry again about this question, but maybe it possible to add CPU mining section to your miner?
For example at zergpool a few CPU algos (m7m, lyra2z, hmq1725, yescryptR16, x16r, c11, yescrypt, timetravel) and it's diffecult to understand which is better to use.

**Comment by nemosminer** [comment]
sure

**Comment by g5-freemen** [comment]
When it can be ?
