### ISSUE TITLE
LTC Support

### ISSUE THREAD

**Issue by monkeyguy** [nemosminer/NemosMiner#466]
When implementing password currency into the profit estimates (like in the latest core ps1 update) please work in a way for us to add pool specific password currencies. I mine to zergpool with ltc payout and nicehash which only does btc payouts.

Additionally, using a different payout currency on zergpool changes the payout threshold, how could I edit the earningstrackerjob ps1 to allow for pool specific, config specified payment thresholds?

Also, when I run with the newest core ps1 the profit estimates are displaying roughly 2% of the values they were displaying before I updated the core file. I assume that expected BTC/day is being multiplied by the pwdcurrency (LTC) price.

**Comment by nemosminer** [comment]
made some update to LTC today can you download fresh copy of v3.0 and in config tab change BTC to LTC

**Comment by nemosminer** [comment]
testing LTC support atm still needs some work
