### ISSUE TITLE
Difference between profit

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#467]
Don't understand why benchmark shows 0,187 mBTC/D, but in NemosMiner only 0,052 mBTC/D.
Have no reason to use NemosMiner 

![image](https://user-images.githubusercontent.com/36886126/37861802-15e8b90a-2f52-11e8-8836-ab762b5b1330.png)

and how possible to get profit <0 BTC/D ?
![image](https://user-images.githubusercontent.com/36886126/37861941-e99af6a2-2f55-11e8-9d25-ef0d887481f0.png)

**Comment by nemosminer** [comment]
you need to let it finish benchmark so it can actually start to work..

**Comment by g5-freemen** [comment]
but what about 1st picture, all night miner works with BitCore at 0,187 mBTC/D (by Benchmark data), but in NemosMiner only 0,052 mBTC/D.
