### ISSUE TITLE
Altcoin Passwordcurrency Problem

### ISSUE THREAD

**Issue by pol0boy** [nemosminer/NemosMiner#470]
Hi Nemo ! Thank you for everything you do for us =)
Getting an error when putting XVG as ''Passwordcurrency'' and this is because of coinbase limitation. It was working fine before the newest changes you did. 
"https://api.coinbase.com/v2/exchange-rates?currency=$($Config.Passwordcurrency)"
https://api.coinbase.com/v2/exchange-rates?currency=XVG returns and error & I had to fixe it manually to BTC.
Thanks

**Comment by nemosminer** [comment]
thanks
