### ISSUE TITLE
Zergpool new format url

### ISSUE THREAD

**Issue by syrm** [nemosminer/NemosMiner#473]
Hello,

Zergpool format url will change :
We will also change to <ALGO>.mine.zergpool.com:<PORT> server name format, so you can start updating your configuration to support this slowly.

Those urls are already available.

**Comment by nemosminer** [comment]
alreadt done...

**Comment by syrm** [comment]
But... I downloaded the last source and see no modification :-/
Did i miss something ?

**Comment by syrm** [comment]
Nevermind, now i see it.
