### ISSUE TITLE
TheBSODPool support

### ISSUE THREAD

**Issue by nyakze** [nemosminer/NemosMiner#474]
Hello, any chance of adding http://bsod.pw pool to the list?

**Comment by OMGTAA** [comment]
BSOD doesn't have auto-exchange.

**Comment by nyakze** [comment]
You only support pools with auto exchange?

**Comment by nemosminer** [comment]
yip everything is auto converted by the pools into BTC adding support for LTC also...

if you mine with miningpoolhub you can also chose any currency to auto convert or not auto convert at all and you will receive the actual coins you mine no conversion... 

its basically just like NICEHASH but more profitable...
