### ISSUE TITLE
ccminer +25% Hashrate X16r : )

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#476]
https://github.com/brian112358/nevermore-miner

i will compile a fresh copy today with dev fee removed 

Best Regards
Nemo

note: single 1070 70%tdp(125watt) +75core +506mem
edited 09/04/18

MSFTserver/RavenMiner = 8.75mhs no fee (opensource)
CcminerEnemy = 9.43mhs no fee  (closed source)
CcminerAlexis78x16rx16s = 9.89mhs no fee (open source)

**Comment by nemosminer** [comment]
edit: donate.h 
change : #define MIN_DEV_DONATE_PERCENT 1
to : #define MIN_DEV_DONATE_PERCENT 0
save
compile with vs2013 cuda 9

**Comment by nemosminer** [comment]
https://github.com/nemosminer/Ccminernevermore/tree/linux

**Comment by nemosminer** [comment]
done : https://github.com/nemosminer/Ccminernevermore

**Comment by nemosminer** [comment]
note: single 1070 70%tdp(125watt) +75core +506mem

MSFTserver/RavenMiner = 8.95mhs no fee
CcminerEnemy = 9.95mhs no fee
Ccminernevermore = 11.1mhs  : )

**Comment by gak45** [comment]
miner file for nemos seems to MIA now. DL'ed it when it was available but it does not work.

**Comment by nemosminer** [comment]
seems MIA does it? https://github.com/nemosminer/Ccminernevermore/releases

**Comment by nemosminer** [comment]
just compiled and tested x64 release,  performed better that 32bit
seems cuda 9 favours x64 over 32bit

**Comment by nemosminer** [comment]
x64 Release: https://github.com/nemosminer/Ccminernevermore/releases/download/0.1-nevermore/ccminernevermore0.1x64.zip

**Comment by gak45** [comment]
thank you.... but the ccminernevermore.ps1 file is MIA is what I meant. When I ran the one that was removed from miners folder on master.... it puked out and said 'x16 argument invalid' and never could benchmark

**Comment by nemosminer** [comment]
yeh been updating miners over last few days all ps1 are updated now

**Comment by gak45** [comment]
still getting a ccminer 'x16r invalid argument' with it. Any idea where the gremlin may be?

**Comment by nemosminer** [comment]
can you post a screen shoot i just ran v3.0 master through 8x10603gb flew through bench marking no problems at all is now mining x16r with nevermore....

im about to download  and run v3.0 master through my 6x1080ti test rig i'll will let you know how it goes

**Comment by gak45** [comment]
thats all that would pop up in the ccminer winder. BUT I figured it out. Had to nuke and pave the stats folder and reDL everything from the master gitub. NOW it is working. Weird... but it is what it is. Might be a gremlin with enemyminer (I deleted it too). IDK, maybe one doesnt play nice with the other.. but that combo worked for me on all my rigs :)

If anyone runs into the same issue that is the fix. Delete the stats folder and start over from 100% virgin state and make sure enemyminer is _not_ enabled.

**Comment by nemosminer** [comment]
enemyminer is not needed its slow and closed source...

https://github.com/nemosminer/NemosMiner/commit/af77bc14b4b7e912cbabbd8756205112335365f7

**Comment by buxstore** [comment]
https://github.com/ocminer/suprminer/releases/download/1.1/suprminer-1.1.7z   this is much faster than nevermore ，pls test！

**Comment by gak45** [comment]
use nevermore.ps1 as the template. initial results are its a bit faster on 1070s, faster on 1080s and noticeably faster on 1080tis. No idea if its worth the 1percent dev fee yet though. :)

**Comment by nemosminer** [comment]
there is no fee...

https://github.com/nemosminer/ccminernevermore/commit/3d2136dfc03b02e8aa54152d7c81e2e4a67faec3

**Comment by Tesla74** [comment]
https://github.com/ocminer/suprminer/ .. there is no dev fee.  Might be worth testing.  Looks like it was optimized by Alexis!

**Comment by nemosminer** [comment]
testing now

**Comment by ktsonevski** [comment]
I do not see a difference personally, I even feel less...

**Comment by nemosminer** [comment]
tested:... 

my current nevermore (with removed dev fee) is faster my guess is they used same code  compiled with cuda 9.1 instead of 9 and 32bit instead of x64...

ocminer is legit tho so your more than welcome to use it..... 

https://imgur.com/a/opEeq

**Comment by nemosminer** [comment]
https://github.com/nemosminer/ccminernevermore/releases

**Comment by buxstore** [comment]
so tiny time？

**Comment by nemosminer** [comment]
i will continue to test & on more cards but so far i can;t see any speed improvement.. it slower not faster as far as ive tested so far...

**Comment by IgorOsa** [comment]
Also tested suprminer for few hours and found that it's not better than nevermore... had back to "nevermore x64"...

**Comment by tr1l3r** [comment]
I still find enemy to be the fastest x16r miner. It give 14 MH and more on gtx 1070. Been using it for a while now and it gives way higher hashrate than any other out there. Give it a try guys.

**Comment by tr1l3r** [comment]
What fee? I didn't notice any fee on the miner and everything works really nice.

**Comment by tr1l3r** [comment]
I'm mining on a 0% fee pool with 6800 miners. 60% of them are using enemy miner.

**Comment by nemosminer** [comment]
this is faster than enemy and is open source

https://github.com/nemosminer/ccminernevermore/releases

**Comment by tr1l3r** [comment]
Ok. I'll give it a shot nemo. I don't see it being faster after 1 hour, but I'll let it run for a little bit more.

**Comment by gak45** [comment]
Thats the problem with x16r... its hashrate is soooo variable. I found after a day that nevermore was much faster than enemy. In my experience enemy reports one number but the pool sees a different one... a lower one.

**Comment by Tesla74** [comment]
I wonder if superminer was compiled in x64, how it would compare to nevermore x64.

**Comment by yuizen** [comment]
Ok noob question, is nevermore in the current v3.0 that I can download?

**Comment by nemosminer** [comment]
yuizen yes

**Comment by nemosminer** [comment]
@gak45 im on it... will compile version ccminer/never0.2 today 

https://github.com/nemosminer/ccminernevermore

https://github.com/nemosminer/ccminernevermore/commit/366a2652146d1ef9339e5fed2dd19569a970b1cd

**Comment by nemosminer** [comment]
@tr1l3r https://bitcointalk.org/index.php?topic=826901.24040

**Comment by nemosminer** [comment]
ccminer/nevermore v0.2

v0.2 increase opt_statsavg from 30 seconds to 2 minutes 30 seconds (average out fluctuating x16r hash-rate)

https://github.com/nemosminer/ccminernevermore/releases/download/0.2-nevermore/ccminernevermore0.2x64.zip

**Comment by Olegik-ah** [comment]
Hi!
How you make measurements?
I have 2 same rigs 7x1070. I start nemosminer same time, but 1st rig on ccminer enemy, 2nd on ccminer nevermore. After approx 24-30 hours i have reported speed in nemos "enemy" about 10% faster "nevermore"
On 1060 rigs enemy and nevermore speed approx same

**Comment by gak45** [comment]
Are you comparing what is reported by the miner (and thus Nemos) or what the pool is reporting? Pool stats are all that matter. I found enemy to report higher than it was seen by the pool. YMMV

@nemosminer will you be adding in x16s to the nevermore alogs options or using the modded x16r version to give x16s as well? Doesnt matter too much right now as its not auto-trade enabled on most pools but 'should be' soon. Here is the x16s modded miner github location:
https://github.com/brian112358/nevermore-miner-x16s

**Comment by tr1l3r** [comment]
I mine on ravenminer.com

**Comment by nemosminer** [comment]
added supaminer from ocminer with added z16r and x16s support

x16s supoort is already added to master for zergpool

**Comment by buxstore** [comment]
https://github.com/brian112358/nevermore-miner-x16s    pls   remove dev fee and test it

**Comment by nemosminer** [comment]
on it ready to compile today...  https://github.com/nemosminer/ccminernevermorex16s

**Comment by nemosminer** [comment]
done: 

https://github.com/nemosminer/ccminernevermorex16s/releases

https://github.com/nemosminer/ccminernevermorex16s/releases/download/nevermorev0.1x16s/ccminernevermorex16sx64v0.1.zip

**Comment by buxstore** [comment]
now using 3637 as well as 3636, any way to specify that in settings somewhere?

**Comment by nemosminer** [comment]
there is but no need to...

**Comment by buxstore** [comment]
why alex78 cant support 12 cards

**Comment by puch0021** [comment]
Nevermore 0.2 released.
https://github.com/brian112358/nevermore-miner/releases/tag/v0.2

Thanks for all the help Nemo

**Comment by nemosminer** [comment]
all good https://github.com/nemosminer/ccminernevermorex16r

donation removed
fix for linux build
updated code
avg out benchmark hashrate
ready for compile

**Comment by buxstore** [comment]
no windows？

**Comment by nemosminer** [comment]
done : 

Optimized CCMiner (CUDA miner) fork for x16r v0.3

Forked from https://github.com/tpruvot/ccminer
Alexis78 x16r support added by "brian112358" : https://github.com/brian112358/nevermore-miner
disabled fee and recompiled: https://github.com/nemosminer/ccminernevermorex16r

hashrate flauction fix : https://github.com/nemosminer/ccminernevermorex16r/commit/08cc61e55613099281278400e0a356e0da3f6695

dev fee disabled by default : https://github.com/nemosminer/ccminernevermorex16r/commit/f2eda8e32ce2bc52c0045c9c5846a7bf17ebff3f

linux build fix : https://github.com/nemosminer/ccminernevermorex16r/commit/8b50e313888766d30508c9838147082f49d638e8

more Alexis78 kernels added over v0.2,  v0.3 = Added alexis kernels for hamsi (+20%, +1.5% overall) and fugue (+10%,…  : https://github.com/nemosminer/ccminernevermorex16r/commit/c478d04061690617994a377e1b30bfc9c3bc0825

compiled with vs2013 cuda 9 x64

**Comment by nemosminer** [comment]
download v0.3 : 

https://github.com/nemosminer/ccminernevermorex16r/releases/download/nevermorex16rv0.3/ccminernevermorex16rx64v0.3.zip

https://github.com/nemosminer/ccminernevermorex16r/releases/tag/nevermorex16rv0.3

Best Regards
Nemo

**Comment by buxstore** [comment]
Latest release
 1.5
 395885a
more optimizations +7 %
@ocminer ocminer released this 15 hours ago

Assets
7.25 MB suprminer-1.5.7z
 Source code (zip)
 Source code (tar.gz)
1.5

cleanup and windows compiling
 1.4
 b7bec70
more optimizations +14 %
@ocminer ocminer released this a day ago · 3 commits to master since this release

Assets
7.24 MB suprminer-1.4.7z
 Source code (zip)
 Source code (tar.gz)
1.4

optimizations +14%
 1.3
 73321c5
added faster hamsi variant by alexis +20%
@ocminer ocminer released this 2 days ago · 7 commits to master since this release

Assets
7.23 MB suprminer-1.3b.7z
 Source code (zip)
 Source code (tar.gz)
1.3

add hamsi +20 %

**Comment by buxstore** [comment]
LOL，nevermore so slow

**Comment by nemosminer** [comment]
is it?

**Comment by buxstore** [comment]
YOU can try
https://github.com/ocminer/suprminer/releases/download/1.5/suprminer-1.5.7z

**Comment by nemosminer** [comment]
YOU can try 
https://github.com/nemosminer/ccminernevermorex16r/releases/download/nevermorex16rv0.3/ccminernevermorex16rx64v0.3.zip

**Comment by nemosminer** [comment]
might wanna test before you comment...

**Comment by buxstore** [comment]
your soft base on nevermore0.2=suprminer1.4 ，now suprminer 1.5

**Comment by nemosminer** [comment]
ok

**Comment by nemosminer** [comment]
ok

**Comment by buxstore** [comment]
i will test 
yours

**Comment by nemosminer** [comment]
: )

**Comment by nemosminer** [comment]
thanks @buxstore i have to go to work for couple hours when i get back i'll test https://github.com/ocminer/suprminer/releases/download/1.5/suprminer-1.5.7z

if its faster i'll make it default x16r algo miner

Best Regards
Nemo

**Comment by buxstore** [comment]
ok，bye

**Comment by buxstore** [comment]
https://github.com/ocminer/suprminer/releases/download/1.6/suprminer-1.6.7z

**Comment by nemosminer** [comment]
tested both 1.5 and 1.6 no speed increase this is still the best

edited 02/04/18 v0.3 : https://github.com/nemosminer/ccminernevermorex16r/releases

**Comment by buxstore** [comment]
I had run these ccminer couple of day
day，finally enemy is the best so far

发自我的 iPhone

**Comment by nemosminer** [comment]
best for you... not for me

**Comment by tr1l3r** [comment]
Enemy way . Tested all of them, not one comes close to enemy. But your choice dudes.

**Comment by nemosminer** [comment]
"Tested all of them, not one comes close to enemy. But your choice dudes."

edited 02/04/18 v0.3 : https://github.com/nemosminer/ccminernevermorex16r/releases

**Comment by nemosminer** [comment]
https://ravenforum.org/topic/23/enemy-1-03-vs-suprminer-1-6-vs-enemy-1-05-test-results

:  ) no need for closed source miners

**Comment by nemosminer** [comment]
Interesting that Suprminer is up there with Enemy.

**Comment by nemosminer** [comment]
Suprminer is a fork of Nevermore, made by ocminer with counseling from Alexis who is the one who made the improved kernels in the first place. Those improved kernels are the key thing what makes all of these miners better than the first ccminer 2.2.5 release.

**Comment by nemosminer** [comment]
https://github.com/nemosminer/ccminerx16r-x16s/releases

https://github.com/nemosminer/ccminerx16r-x16s/releases/download/x16rx16sv0.4/ccminerx16rx16sv0.4.zip

**Comment by yuizen** [comment]
Question: Where do I put those files?

**Comment by buxstore** [comment]
https://github.com/a1i3nj03/a1_min3r/releases  

发自我的 iPhone

**Comment by buxstore** [comment]
https://github.com/a1i3nj03/a1_min3r/releases

发自我的 iPhone

**Comment by buxstore** [comment]
https://ravenforum.org/topic/25/a1-vs-suprminer-vs-nevermore-vs-enemy-1-04-test-results
