### ISSUE TITLE
NemosMiner 3.0

### ISSUE THREAD

**Issue by MrMineitall** [nemosminer/NemosMiner#477]
Hi there,

I have been using nemosminer since december 2017... had some issues because i run 12 cards rigs but with a bit of troubleshooting on the batch files and PS1 i have managed to always get the miner to run flawlessly. Decided to give 3.0 a go, but i find it much more unstable then 2.5.2... For example, x17 on ahashpool keeps crashing all the time. Im using the exact same OCs as before. Tried to underclock to see if it would help but to no avail. Today i got the last version from the website (clone) and i noticed its now using another miner for x17 but still keeps crashing all the time. I really dont know what i could be doing wrong but for the moment, for me, 2.5.2 its a much better option. 

Will you be updating your v2 nemosminer or you will stick to 3.0 and rule out the "command line" version?

Kind regards,
TF

**Comment by nemosminer** [comment]
miner for x17 is the same in v3.0 and v2.5.2...

**Comment by nemosminer** [comment]
note for 12 cards if your having trouble delete all ps1 files in "miners" folder 

open "OptionalMiners/Miners 12gpu 750ti-1080ti"  copy all the ps1 files from there into "Miners folder"

x17 will now be using Tpruvot latest Release cuda932bits

hope this helps

**Comment by MrMineitall** [comment]
Thanks for the replies.

I will try this now and let you know how it went... cheers buddy!

**Comment by MrMineitall** [comment]
Nemo, thanks for the help.. got my rigs now running without any crash so far, so fingers crossed.

All the best ;)

**Comment by MrMineitall** [comment]
Still crashing... this time on the PHI algorithm... on the 2.5.2 i dont have this issue... like i said, same overclocks, everything is the same.. the only thing that changes is the nemosminer version. :(

Appreciate your help!

**Comment by MrMineitall** [comment]
x17 also crashing... I just wish someone would just create a linux multi algo since there is none as far as i know. Windows is a total bullshit... :(

Thanks anyway nemo for trying to help me out...

**Comment by nemosminer** [comment]
w
