### ISSUE TITLE
Excavator Lyra2RE2 doesn't work

### ISSUE THREAD

**Issue by Braintelligence** [nemosminer/NemosMiner#483]
Looks like this:
![grafik](https://user-images.githubusercontent.com/6761196/38041185-6289a3ca-32b1-11e8-8597-5d5e3bb0fde2.png)

And stays like this on all of my rigs. Seems to only be true for Lyra2RE2.

EDIT: For some reason it seems to work, if you restart the whole thing. Maybe it needs to initialize the json first?

**Comment by nemosminer** [comment]
it works perfectly....

**Comment by Braintelligence** [comment]
I verified that for fresh installs on **10 different rigs** with either 6, 7, 12 or 13 GPUs I **always** have to stop and start the miner again after it hits an Excavator task for the first time while benchmarking, or else I see this:

![grafik](https://user-images.githubusercontent.com/6761196/38052101-691c49bc-32d0-11e8-85fd-1a62bfd7127c.png)

It feels weird when you just say "it works perfectly", when I can 100% safely reproduce this.
