### ISSUE TITLE
x16r doesn't appear to bench correctly

### ISSUE THREAD

**Issue by bobloadmire** [nemosminer/NemosMiner#486]
as shown here: https://i.imgur.com/ANdRVaD.png

Currently mining at around 50mh/s, bench is showing 30mh/s. benchmark numbers never update.

**Comment by nemosminer** [comment]
i have added update to ccminer for x16r to help...   Since v3.0 release...

https://github.com/nemosminer/ccminernevermore/releases

**Comment by nemosminer** [comment]
not if you downloaded release 

i only updated the master 16hours ago 

i have just added 16s Algo support also, so once my test rigs have completed i'll add V3.1 with update x16r miner and x16s support

**Comment by Braintelligence** [comment]
I've updated the binary from your link. Is there a particular commit that enables update of x16r stats? Sadly the stats don't update yet, and therefore the benchmarked hashrate can greatly differ from the hashrate that gets reported in 

```
Stats ' X16r ' -> XX,XX MH after YYYY sec
```

**Comment by nemosminer** [comment]
https://github.com/nemosminer/ccminernevermorex16r/releases

**Comment by bobloadmire** [comment]
What's the update procedure for 3.0?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/archive/master.zip

**Comment by CBDB1LOVE** [comment]
https://i.imgur.com/ANdRVaD.png

**Comment by nemosminer** [comment]
@CBDB1LOVE open 
"stats" folder 
edit: ccminerAlexis78x16r_X16r_HashRate 
change to what you think it should be...s
save
