### ISSUE TITLE
Earning not showing in console or GUI. E key no effect.

### ISSUE THREAD

**Issue by OMGTAA** [nemosminer/NemosMiner#487]
Just grabbed a fresh master and it will not display earnings, which means it won't display trust either. E does nothing (S does work though).

**Comment by MrPlusGH** [comment]
Which pool?

**Comment by OMGTAA** [comment]
Zerg, Blaze, Zpool, Ahash, and MPH.

**Comment by OMGTAA** [comment]
I have tried to pause it and restart; as well as close it out and restart. Doesn't fix.
I have compared the config.json to good running copies, no variance.
I'm running a 3.0 install on a few other machines which work fine, but they were downloaded more than a few days ago. I fired up a Plus2.1 install as well, no problem.

**Comment by MrPlusGH** [comment]
Let's wait for @nemosminer to chime in. He might have changed something on master. 
I'd recommend using the released version rather than Master.

**Comment by nemosminer** [comment]
works fine...

**Comment by OMGTAA** [comment]
Welp, grabbed a fresh master, copied in the BIN,MINERS,PRERUN,STATS, and config.json. It has now been mining to 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE for 15 minutes, and I still get no output from "E" key.

**Comment by duub** [comment]
I've the same issue, also showing the message "Waiting data from pools" maybe it's related with the error I've found in the log:

>  PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4068""
> Miners API Port: 4068

Can you find this messsage on your log @OMGTAA ??
