### ISSUE TITLE
new and have a question

### ISSUE THREAD

**Issue by jasonisdn** [nemosminer/NemosMiner#490]
Everything runs fine to a point. At that point, unknown mining pools and wallet addresses show up in my table and begin to have the benchmark ran for them and launch themselves. These algo's and pools are not in my selected list and should not be adding themselves. I am using the most recent release and it has happened 2 times today.

**Comment by nemosminer** [comment]
donation / fee

**Comment by jasonisdn** [comment]
Is there a way that in the next release instead of a wallet address you can add a if statement that would remove the address and add in a "fee" tag, just to allow for the warm blanket feeling of the code not being tampered with?
