### ISSUE TITLE
CCMiner are not working with 12 GPUs 

### ISSUE THREAD

**Issue by Dekablade01** [nemosminer/NemosMiner#494]
According to #433 

I raised issue for `poly`, which already fixed in master branch. Thanks to @nemosminer 

I just have time to run full test with 12 GPUs rig with zpool's algorithms, which I found some more. 

Which are
- alexis78Xevan  [ xevan ]
- alexis78phi [ phi ]
- alexis78cuda8 [ myr-gr, blakecoin ] 
- alexis78 [ blake2s, veltor, hsr, keccak, lbry, lyra2v2, nist5, sib, skein, c11, x17 ]
- tpruvotskunk [ skunk ]

**Comment by nemosminer** [comment]
Made For & Tested with 6x10603gb 6x1070 6x1070ti 6x1080ti (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards

**Comment by Dekablade01** [comment]
sure ! let me try to produce this, then I'll respond in this issue.

**Comment by nemosminer** [comment]
yes delete everything in miners folder

copy and paste miners.ps1 files from OptionalMiner to Miners

**Comment by Dekablade01** [comment]
ok on it !

**Comment by Dekablade01** [comment]
is not reproducible
