### ISSUE TITLE
no workername on blazepool 

### ISSUE THREAD

**Issue by podlbo** [nemosminer/NemosMiner#495]
There is no visible workername on blazepool.

**Comment by nemosminer** [comment]
thanks will double check 2day

**Comment by nemosminer** [comment]
checked worker name is showing blazepool is working well

**Comment by podlbo** [comment]
In my case worker name does not work... you can see on the picture... :(
![slika](https://user-images.githubusercontent.com/33230718/38884145-f718a186-426e-11e8-9d46-938dd1320e26.png)
