### ISSUE TITLE
Multiple instances minor bug

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner#497]
Hi!
I found minor multiple instances bug.
How to reproduce:
1. Download nemo from git
2. Configure (id, pool, wallet), check Autostart checkbox and bench.
3. Close
4. Make a copy of nemo folder
5. Edit config.json
5.1 in 1st folder
    "SelGPUCC":  "0,1,2",
    "SelGPUDSTM":  "0 1 2",
5.1 in 2nd folder
    "SelGPUCC":  "3,4,5",
    "SelGPUDSTM":  "3 4 5",
6. Start miner from 1st folder. Wait while mining program (ccminer) will start
7. Start miner from 2nd folder. In the start procedure ccminer from 1st miner will be killed <-- bug!

Hope well explained:)

**Comment by dealbreak3r** [comment]
My workaround:

For one of your nemo instances, edit Include.ps1:
Line 80, change `$StartPort = 4068` to `$StartPort = 4069`

The TCP Port detection isn't working, or at least it's causing the running miner to close as you noticed. My way let's each instance start using it's own non-conflicting port

**Comment by Olegik-ah** [comment]
Why did you close the ticket? Why so rude? Any explanation?

To dealbreak3r - it is not port detection bug. I think the bug is in the lines 336 or 339 in core.ps1. But i dont know how to fix it.

**Comment by dealbreak3r** [comment]
Multi-instance is experimental. My method is quick and easy.  If you are already going in and modifying config.json, you are advanced enough to make the port number tweak as well.

I've been multi-instance mining for the past 2 weeks with just the port number change, without having to touch Core_v3.0.ps1.  Rock solid.  They do not interfere with each other (Excavator requires additional tweaks, but that's an optional miner not enabled by default).  Give it a try.

**Comment by MrPlusGH** [comment]
This is a minor bug (thanks for stating :)) has the miner will restart on the right port on next cycle.
This happens only when starting the second instance.
So this is not preventing anything from working. Editing include.ps1 is not even needed.

Still it will have to be fixed. But it is low priority on my list has it id non blocking.
This one should be closed for now. We'll wake it up once actively working on it.

It appears that some miners (not all) do not like the way we poll the port to find out of it is free.

**Comment by Olegik-ah** [comment]
Yes, it happens only 1 time at startup 2nd instance.
MrPlus, thanks. If you already know bug - ok.
Nemo closed my ticket without any comment. It is so rude!
