### ISSUE TITLE
Cryptonight7

### ISSUE THREAD

**Issue by Tesla74** [nemosminer/NemosMiner#501]
Add Cryptonight7. Monero changed its algorithm to Cryptonight7.

**Comment by MrPlusGH** [comment]
XMRrig already handle this. We're ok with the version we use.

**Comment by Tesla74** [comment]
Do the scripts need to be updated?

**Comment by MrPlusGH** [comment]
nope

**Comment by nemosminer** [comment]
done updated XMRig from v2.5.2 to v2.6-beta tested on MPH and NH all is well
