### ISSUE TITLE
new nevermore

### ISSUE THREAD

**Issue by buxstore** [nemosminer/NemosMiner#504]
https://github.com/brian112358/nevermore-miner/releases/download/v0.2.2/nevermore-v0.2.2-win64.zip

**Comment by nemosminer** [comment]
https://github.com/nemosminer/ccminerx16r-16s/releases

https://github.com/nemosminer/ccminerx16r-16s/releases/download/x16rx16sv0.4/ccminerx16rx16sv0.4.zip
