### ISSUE TITLE
phi-phi-pool.com missing

### ISSUE THREAD

**Issue by Dekablade01** [nemosminer/NemosMiner#506]
I saw `phi-phi-pool` was been already merged to `master` branch, but there's no configuration files for it. Nemo's miner doesn't support anymore ? 

https://www.phi-phi-pool.com

**Comment by Tesla74** [comment]
I too would like Phi Phi Pool

**Comment by Tesla74** [comment]
[phiphipool.ps1](https://github.com/nemosminer/NemosMiner/commit/e9c34994325bb9acf441f12d51c94ff1a8c45396)
[phiphipool24h.ps1](https://github.com/nemosminer/NemosMiner/commit/127605456a18cf042474f4c469cd9eb624fed3eb)
[phiphipoolplus.ps1](https://github.com/nemosminer/NemosMiner/commit/c681eaab478a441d9f8546566f1a900ba5f3526b)

**Comment by nemosminer** [comment]
done
