### ISSUE TITLE
NemosMiner does not work with 1 GPU?

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#507]
Hi,

I have 1 x GTX 1070. When I launch NemosMiner the benchmarks constantly fail as it tries to pass -d 0,1 to ccminer.

There is no onboard GPU so the disable GPU0 would actually disable the 1070...

**Comment by nemosminer** [comment]
it auto detects no  need to do anything ...

**Comment by scavern** [comment]
Like  I said thought it passes -d 0,1 to ccminer. ccminer then says the device doesn't exist and then exits.

this is what is being passed...

Bin\NVIDIA-ccminerAlexis78x16r\ccminer.exe -b 4068 -a x16r -o stratum+tcp://x16r.mine.ahashpool.com:3636 -u xxxxxxxxxxxxxx -p Ripley,c=BTC -d 0,1 --api-remote --api-allow=0/0

**Comment by nemosminer** [comment]
https://imgur.com/a/ncvv7

**Comment by nemosminer** [comment]
like i said it auto detects no need to do anything ...

**Comment by scavern** [comment]
So this is very strange. I thought I would have a look again today to try and figure out what is going on.


I launch the miner again, and this time it works perfectly...

________________________________
