### ISSUE TITLE
Constant Failures, never runs miner

### ISSUE THREAD

**Issue by IndiaVenom** [nemosminer/NemosMiner#509]
Running Nvidia 780 3gb
[miner.log](https://github.com/nemosminer/NemosMiner/files/1888463/miner.log)
[switching.log](https://github.com/nemosminer/NemosMiner/files/1888464/switching.log)

**Comment by nemosminer** [comment]
Made For & Tested with 8x10603gb 6x1070 6x1070ti 6x1080ti (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards
