### ISSUE TITLE
MiningPoolHub Cryptonight not working

### ISSUE THREAD

**Issue by RealmKnight** [nemosminer/NemosMiner#510]
Running the start.cmd from the bin (\NemosMiner-v3.0\Bin\NVIDIA-XMRig), the program runs fine (tuned the config file for mph autoswitching), but the miner constantly crashes when nemosminer opens it and closes before I can read the error. Other than messing with the config.json, which is completely fine when run stand-alone, I can't think of anything else to do.

**Comment by nemosminer** [comment]
working great !

**Comment by RealmKnight** [comment]
Hmm... I can not get it to work on my 6 card rig nor on my testing rig of just 2 cards. Like I said, the miner runs fine in standalone mode, but crashes every time when run by nemosminer.
