### ISSUE TITLE
new open source x16 alog

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner#512]
Any chance of testing A1 miner and seeing if it as good as the raven forum say it is. Peeps have tested it and said its about 5 percent better than enemy, nevermore, etc.

https://github.com/a1i3nj03/a1_min3r/releases

**Comment by nemosminer** [comment]
nope im over testing new x16r miners

**Comment by nemosminer** [comment]
another one

**Comment by nemosminer** [comment]
https://github.com/nemosminer/ccminerx16r-x16s/releases

**Comment by nemosminer** [comment]
@gak45  i downloaded and tested https://github.com/a1i3nj03/a1_min3r/releases

there is nothing new here same speed as https://github.com/nemosminer/ccminerx16r-x16s/releases
