### ISSUE TITLE
ccminer-cryptonight

### ISSUE THREAD

**Issue by Tesla74** [nemosminer/NemosMiner#515]
This might help.

 -a  --algo            choose between the supported algos:
                          cryptonight (the old version)
                          monero      (v7)
                          graft       (v8)
stellite (v3)

https://github.com/KlausT/ccminer-cryptonight/blob/master/README.txt

**Comment by nemosminer** [comment]
its already working and being tested with: 

-a cryptonight 
-a cryptonightV7

testing with Nicehash its working well... no need to change anything..

**Comment by nemosminer** [comment]
are you suggesting i change 
-a cryptonightV7
to -a monero
?

**Comment by Tesla74** [comment]
I thought that might be the cause of this error:
https://bitcointalk.org/index.php?topic=1777336.msg34417160#msg34417160

**Comment by nemosminer** [comment]
no cause of error was -b 4068

**Comment by nemosminer** [comment]
KlausT does not have API in this ccminer yet so i have to run it through wrapper that user your referring to in bitciontalk thread downloaded master while i was in the process of updating my master code.. there for he run into a error

**Comment by nemosminer** [comment]
yesyed working on nicehash
