### ISSUE TITLE
MiningPoolHub BTC Payout Threshold

### ISSUE THREAD

**Issue by Renegade5399** [nemosminer/NemosMiner#519]
I read you have it hard-coded to .01 for the earnings/payout tracking.

If you go to your BTC wallet on MPH, the minimum payout is 0.0021 BTC. This changes (infrequently) if the BTC network load is high and the fees are up. But it's been 0.0021 BTC for a while now. Just making a suggestion as this would give a more accurate percentage to payout.

Great mining program. Thanks for all your efforts.

**Comment by nemosminer** [comment]
thanks i'll update

**Comment by nemosminer** [comment]
you can edit payment thresold
