### ISSUE TITLE
test & add new miners to optional miners

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#526]
test & add new miners to optional miners if improvement found

ccminer-bitcore_sp-mod_v2
bitcore

ccminer-phi-sp-mod_v1
Phi

ccminer-skunkhash_sp-mod_v8
Skunk

ccminer-zealot-enemy_v1.08 
    Bitcore = ' -i 20'
    Phi = ' -i 20'
    X16R = ' -i 20'
    X16S = ' -i 20'

**Comment by buxstore** [comment]
no its no need.because I can use alex for my 12cards rigs,   no need optional miners

**Comment by buxstore** [comment]
ccminerAlexis78  ccminerAlexis78cuda8 CcminerAlexis78keccakc CcminerAlexis78Phi ccminerAlexis78poly CcminerAlexis78xevan CcminerKlaust CcminerSkunk CcminerTpruvot CcminerTpruvotcuda9 CcminerTpruvotx64 PalginHSR all normal!!!!!!!!!!!!!!!!!!!!! no need change

**Comment by nemosminer** [comment]
i'll test and decide thanks @buxstore buxstore

**Comment by g5-freemen** [comment]
Looks like download links for optional miners not working now

**Comment by nemosminer** [comment]
@g5-freemen  they are working...

**Comment by borzaka** [comment]
Almost complete X16r miner list (some of them open source, some of them not):
[https://coinguides.org/ravencoin-x16r-miner-list/](https://coinguides.org/ravencoin-x16r-miner-list/)

Maybe some worth testing.

**Comment by nemosminer** [comment]
i have tested them all...

**Comment by nemosminer** [comment]
i found Ravencoin best as it open source no dev fee..

followed by Zealot-Enemyv1.08 fastest (but closed source and 1%built in dev fee)

**Comment by nemosminer** [comment]
ccminer-bitcore_sp-mod_v2
bitcore

ccminer-phi-sp-mod_v1
Phi

ccminer-skunkhash_sp-mod_v8
Skunk

ccminer-zealot-enemy_v1.08

all added still need testing

**Comment by buxstore** [comment]
maybe enemy1.08 is fatest

**Comment by nemosminer** [comment]
not maybe... it is... as i said that above...

i found Ravencoin best as it open source no dev fee.. https://github.com/Ravencoin-Miner/Ravencoin/releases

followed by Zealot-Enemyv1.08 fastest (but closed source and 1%built in dev fee)

**Comment by nemosminer** [comment]
done
