### ISSUE TITLE
support to starpool

### ISSUE THREAD

**Issue by Aishor** [nemosminer/NemosMiner#529]
add please https://www.starpool.biz/ it seems a very interesting option with only 0.1% fee

**Comment by Quake4** [comment]
this pool have mostly asic users (scrypt, x11, sha, qubit)

**Comment by Tesla74** [comment]
IMO not worth it.  I also think minemoney.co is  useless and could be removed.

**Comment by nemosminer** [comment]
Could we get 24hr and Plus for hashrefinery.com? yip
