### ISSUE TITLE
Getting CCminer error when benchmarking RVN 

### ISSUE THREAD

**Issue by Spoon24** [nemosminer/NemosMiner#530]
Having no issues benchmarking any other algo just RVN and help would be greatly appreciated!

**Comment by Spoon24** [comment]
![screenshot_20180418-200745_remote desktop](https://user-images.githubusercontent.com/38570123/39069255-764bd6a6-449c-11e8-8499-3f79807a5bea.jpg)

**Comment by nemosminer** [comment]
im not getting that error  just disable that miner...
