### ISSUE TITLE
First run: No Miners! and full of PowerShell errors.

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#533]
I have done everything what was in the readme:
1, start .bat
2, Config tab, edit stuff
3, close
4, start .bat
5, press start button

This is my log after the first run:
[miner_first_run.log](https://github.com/nemosminer/NemosMiner/files/1938507/miner_first_run.log)

```
Get-Member : You must specify an object for the Get-Member cmdlet.
At D:\mining\NemosMiner-master\Core-v3.1.ps1:238 char:28
+ ...        $Miner.HashRates | Get-Member -MemberType NoteProperty | Selec ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
Get-Member : You must specify an object for the Get-Member cmdlet.
At D:\mining\NemosMiner-master\Core-v3.1.ps1:238 char:28
+ ...        $Miner.HashRates | Get-Member -MemberType NoteProperty | Selec ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
```

After closing, and starting again everything worked, benchmark started.

Latest (downloaded today) master.

**Comment by borzaka** [comment]
It's still an issue with the latest master.

Try to do a clean setup, and you will see.

**Comment by nemosminer** [comment]
i did im not getting that issue.. 

just you... read instructions properly...

  Run NemosMiner-v3.1.bat
  1. Config tab
  2. Set your Wallet address and Username
  3. Select your pool/s and load default Algos button. (Remove any algos you do not want to mine)
  4. "Save Config"
  5. Close
  Run NemosMiner-v3.1.bat
  6."Start

**Comment by borzaka** [comment]
@nemosminer I just made a video for you:
[https://www.dropbox.com/s/laiz7uvlgtxzn8z/2018-04-25_09-22-54.mp4?dl=0](https://www.dropbox.com/s/laiz7uvlgtxzn8z/2018-04-25_09-22-54.mp4?dl=0)

Please, have a look. I hope it helps.

**Comment by MrPlusGH** [comment]
Could you try to comment the following line in Core.ps1 and report if that fixes the issue?

        # Remove miners when no estimation info from pools. Avoids mining when algo down at pool or benchmarking for ever
        $Variables.Miners = $Variables.Miners | ? {$_.Pools.PSObject.Properties.Value.Price -ne $null}

**Comment by borzaka** [comment]
Unfortunately no, it doesn't fixes the issue.
At the very first run it still has many PowerShell errors, and no miners message until the first interval, or a restart.

```
No Miners!
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\Attila\Downloads\NemosMiner-master_first_run_test\Core-v3.1.ps1:238 char:28
+ ...        $Miner.HashRates | Get-Member -MemberType NoteProperty | Selec ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
Get-Member : You must specify an object for the Get-Member cmdlet.
```

```
The property 'HashRates' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\Attila\Downloads\NemosMiner-master_first_run_test\Core-v3.1.ps1:264 char:9
+         $Miner.HashRates = $Miner_HashRates
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
```

```
Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\Attila\Downloads\NemosMiner-master_first_run_test\Core-v3.1.ps1:265 char:18
+         $Miner | Add-Member Pools $Miner_Pools
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberComm
and
```

[miner.log](https://github.com/nemosminer/NemosMiner/files/2016161/miner.log)

**Comment by MrPlusGH** [comment]
Thanks for testing
