### ISSUE TITLE
Changing the WorkerName has no effect.

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#538]
I have changed the WorkerName in the GUI config tab, pressed Save Config, restarted the whole program, but the miners was started with the old (default?) WorkerName.
I have chacked the config.json, and my new WorkerName is there.

This was after running many hours, every miner was benchmarked.

**Comment by nemosminer** [comment]
again issue is with you not program im not getting that problem i run different worker name on every rig...

**Comment by borzaka** [comment]
Have you tried changing the WorkerName on a working setup?

My config.json was edited 24 hours ago, and since than I have restarted the miner multiple times. But it's still using the prev WorkerName, not my new one.
![image](https://user-images.githubusercontent.com/1230402/39217219-42560840-481f-11e8-90fc-8d0458fb7ff3.png)
