### ISSUE TITLE
Add Intensity to Ravencoin-Miner

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#539]
From the official [Ravencoin-Miner GitHub](https://github.com/Ravencoin-Miner/Ravencoin) page:
> Set Intensity with -i, default is 19

But in the example he uses 20:
> ccminer -a x16r -o stratum+tcp://ravenminer.com:3636 -u RSB3YesT18L2ERJS7oxhKc1mVR5tZLkdsR -p d=8 -i 20 --donate 1 -r 5 -N 600

You are using 20 as well for the [enemyzealot1.08.ps1](https://github.com/nemosminer/NemosMiner/blob/master/OptionalMiners/enemyzealot1.08.ps1)

**Comment by nemosminer** [comment]
yes i am
