### ISSUE TITLE
Nemo, can you provide some info why are you closing an issue?

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#540]
Like:
- fixed
- won't fix
- can't reproduce, need more info
- don't care
- etc.

Thx.

**Comment by sephir69** [comment]
he doesn't give a crap and always does that.  use his program or don't

**Comment by borzaka** [comment]
I can see that...

But he is closing issues, which aren't fixed, and still causing problems. :(

**Comment by sephir69** [comment]
see previous response

**Comment by nemosminer** [comment]
there is no issiue... so i closed it i use my own NemosMiner my self on 11 different rigs i know when a issue is real or not...

**Comment by nemosminer** [comment]
i answered every issue you created @borzaka 

not that i needed to as there was no Issue.. that is why i Originally closed them...

if a Issue is Real then it stays open until it is Resolved has Always been like that...

**Comment by nemosminer** [comment]
@sephir69 I do "give a crap" and i don't always do that... there is  issues that have been open for months that won't be closed until resolved.... 
 
 i test and use my program every day so im well aware of whats happening.

**Comment by borzaka** [comment]
Thank you @nemosminer! That's the spirit!

Than my job will be to convince you that (at least some of) my issues are real, and need further investigating. Like #538
