### ISSUE TITLE
Gain %

### ISSUE THREAD

**Issue by CaHek83** [nemosminer/NemosMiner#541]
as seems for me Nemosminer does not calculating Gain% between pools before switching
3.0 version if it make sense
just tested on one pool and i see that it doesn't calculate for one pool same

**Comment by CaHek83** [comment]
i use 3.0 version if it make sense

**Comment by nemosminer** [comment]
works for me

**Comment by CaHek83** [comment]
I've downloaded 3.1
have done all benchs
selected 2 ahashplus zergplus
active gain % set 30 for testing
and miner switches without counting Gain %

**Comment by nemosminer** [comment]
ActiveMinerGain% tested working...
