### ISSUE TITLE
Negative earnings

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#542]
It means, that I have pay to the pool? 😆 

![image](https://user-images.githubusercontent.com/1230402/39188928-43be53e8-47d1-11e8-968f-a1be8b0d3e07.png)

![image](https://user-images.githubusercontent.com/1230402/39188942-49bdc22e-47d1-11e8-9dc0-bfa663aa1780.png)

(Latest master, downloaded today.)

**Comment by MrPlusGH** [comment]
Yes, your earnings at zergpool are showing some negative growth at some points in time.
We are accurately reflecting that:
![image](https://user-images.githubusercontent.com/36303784/39199057-e2a0dfb4-47e8-11e8-9272-32f0d5a742de.png)

**Comment by borzaka** [comment]
Thank you for clarifying!

I didn't know that your are calculating with the Pending balance, not just a cleared Balance which is displayed in the console.

**Comment by nemosminer** [comment]
see no issiue...
