### ISSUE TITLE
Excavator can be faster on Lyra2RE2 with 2 threads

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#549]
![image](https://user-images.githubusercontent.com/1230402/39350660-1a7d74c0-49ff-11e8-882f-72534393d3d8.png)

This is ~1,3% improvement on a 3x 1080 Ti, 3x 1070 Ti RIG.

I duplicated `Excavator.ps1`, renamed to `Excavator2.ps1`, changed `$Threads` to `2` and only enabled `lyra2rev2` algo.
Note: not all algo supports 2 threads with Excavator. For example NeoScrypt crashes.

**Comment by nemosminer** [comment]
thankyou

**Comment by nemosminer** [comment]
done
