### ISSUE TITLE
Please clarify the default donation level

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#553]
In the readme:
> There is a 8 minute per day fee (0.5%), that can be changed in the config (Minimum is 3)0.2%

but later on...
> Donations occurs once every 24 hours for the selected amount of time (default 5 minutes).

config.json contains `8` by default, but in the code you set donation minutes per day between (0,(3..5)) minutes if set to less than 3:
`If ($Config.Donate -lt 3) {$Config.Donate = (0, (3..5)) | Get-Random}`

So, you wanted 8 or 5 minutes for default? :)

**Comment by nemosminer** [comment]
its pretty clear default donation is as stated: 
There is a 8 minute per day fee (0.5%), that can be changed in the config (Minimum is 3)0.2%

if you change settings in config tab when you 1st save you settings to 3 instead of 8 it will mine for 3 minutes per 24hours 

very simple...

**Comment by borzaka** [comment]
But should'nt be `(0, (3..8))` instead of `(0, (3..5))`?

**Comment by nemosminer** [comment]
yes i didnt notice that.. thanks

**Comment by nemosminer** [comment]
i'll increse it next version update this is only used when donation less than 3 mins is set in config...

#Randomly sets donation minutes per day between (0,(3..5)) minutes if set to less than 3

**Comment by nemosminer** [comment]
There is a 8 minute per day fee (0.5%), that can be changed in the config (Minimum is 3)0.2%
  We want to stay completely transparent on the way fees are managed in the product. Donations occurs once every 24 hours for the selected amount of time (default 5 minutes). The first donation sequence occurs 1 hour after miners are started. If Interval is set higher than the donation time, the interval will prime. Example for default parameters. Miners started at 10, First donation cycle runs at 10:52 untill 11, Next donation cycle occurs 24 hours after.All donation time and addresses are recording in the logs folder.

**Comment by borzaka** [comment]
I know that it should not matter 5 or 8, but I just wanted to know about the inconsistency about the donation numbers.

> There is a 8 minute per day fee

> (default 5 minutes)

8 or 5? 5 minute is how many percent? It's not stated.

**Comment by nemosminer** [comment]
its pretty clear default donation is as stated:
There is a 8 minute per day fee (0.5%)

**Comment by borzaka** [comment]
I guessed ;)
Than you should change in the readme. :)

**Comment by nemosminer** [comment]
change what in the readme?

Fee:

  There is a 8 minute per day fee (0.5%), that can be changed in the config (Minimum is 3)0.2%
  We want to stay completely transparent on the way fees are managed in the product. Donations occurs once every 24 hours for the selected amount of time (default 5 minutes). The first donation sequence occurs 1 hour after miners are started. If Interval is set higher than the donation time, the interval will prime. Example for default parameters. Miners started at 10, First donation cycle runs at 10:52 untill 11, Next donation cycle occurs 24 hours after.All donation time and addresses are recording in the logs folder.

**Comment by nemosminer** [comment]
done

**Comment by borzaka** [comment]
Thank you for clarifying!

Sorry, I think this was important.

**Comment by Seetth** [comment]
1st at all thanks for the miner I really like it. About donations I have no problem with donate I even leave it at 8 mins. I mean the miner is good why no 8 mins, but...  

My rigs sometimes need restart so what is happening here is if they was more than 1 hr online that normally is like that,  if I restart 5 times in a day I end making 4-5 donations per day  so 8*5 = 40 mins per day that I already confirm in the logs, for a single card miner normally nemos never need a restart, but for a 6 cards+ rigs restart sometimes is something that will happen. 

If I have one of that days where I have several restarts I end donating almost an HR or even more. I wonder if there is a way top fix donations for true 24 hrs no just start the donation counter each time the miner starts.

Thanks.
