### ISSUE TITLE
Donation question

### ISSUE THREAD

**Issue by kingyem** [nemosminer/NemosMiner#566]
Hello,

Referring to the image attached, is it normal for the fee/donation to be that long (2:50pm - 3:47pm)?
I had put the donation amount to 3min in the config.

![nemosminerwallet_donation](https://user-images.githubusercontent.com/35198970/39466040-415ed0b8-4d59-11e8-8df5-f8ec930e6b02.png)

**Comment by kingyem** [comment]
@nemosminer does closing this issue mean that what I experienced was an isolated case or it is a norm?

If it is a norm, can i know the exact conditions of it happening?

If it was an isolated case, can I help with anything?

**Comment by sephir69** [comment]
see https://github.com/nemosminer/NemosMiner/issues/540
