### ISSUE TITLE
BlockMastersPlus Earnings Tracker seems broken

### ISSUE THREAD

**Issue by papacheal** [nemosminer/NemosMiner#567]
Despite multiple flushes of the Stats folder and restart attempts, I can't get the Earnings Tracker to function properly on BlockMastersPlus. My wallet total is properly returned but both the BTC/D and mBTC/D remain at 0 for multiple days, despite earnings being generated regularly in the wallet.

Manual browser-based attempts to call the standard YIIMP wallet and status API on the site return correct values, so I'm not sure what is going on within NemosMiner.

**Comment by nemosminer** [comment]
yip thanks i'll fix that today has refinery 24hr needs fixing to...

**Comment by nemosminer** [comment]
fixed thanks hashrefinery 24hr plus blockmasters 24hr plus starpool24hr plus all tested and working with plus and earnings tracker
