### ISSUE TITLE
Zergpool 0 bitcore estimates with zergpoolplus

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#569]
Maybe some kind of fallback?

![image](https://user-images.githubusercontent.com/1230402/39518318-de0f0672-4e02-11e8-9522-92e40510495f.png)

![image](https://user-images.githubusercontent.com/1230402/39518399-21fc583a-4e03-11e8-85c7-e1db9fcc54d6.png)

**Comment by sephir69** [comment]
no blocks found = 0 24hr actual from what I understand

**Comment by borzaka** [comment]
I see. So, Zergpool is not good for mining bitcore.

Ahashpool looks better:
![image](https://user-images.githubusercontent.com/1230402/39521863-9f16aa52-4e10-11e8-8311-a2e6b0a930f5.png)

**Comment by nemosminer** [comment]
yeh not many blocks so 24hr Actual is wrong...
