### ISSUE TITLE
Incorrect rate at Nicehash

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#571]
I'm fairly certain my 1 x gtx 1070 is not earning $13 a day at nicehash.

According to ccminer it is hashing at about 700 H/s

Miner                  Algorithm           Speed mBTC/Day BTC/Day USD/Day BTC/GH/Day Pool
-----                  ---------           ----- -------- ------- ------- ---------- ----
ccminerCryptonight     CryptoNight    72,39 KH/s    1,463 0,00146  13,333   20,21693 nicehash-

**Comment by nemosminer** [comment]
remove CryptoNightv7 from your selected algo list...

**Comment by scavern** [comment]
But then I can't use cryptonightv7 at miningpoolhub?

**Comment by nemosminer** [comment]
@scavern go into "miners" find XMRig.ps1 

edit it  : 

remove #      

eg.  before
$Commands = [PSCustomObject]@{
    #"cryptonight" = " --cuda-devices $SelGPUCC" #Cryptonight(max 3 gpus)
    #"cryptonight-lite" = " --cuda-devices $SelGPUCC" #Cryptonight-lite(max 3 gpus)
    #"cryptonightV7" = " --cuda-devices $SelGPUCC" #CryptonightV7(max 3 gpus)

eg. after 
$Commands = [PSCustomObject]@{
    "cryptonight" = " --cuda-devices $SelGPUCC" #Cryptonight(max 3 gpus)
    "cryptonight-lite" = " --cuda-devices $SelGPUCC" #Cryptonight-lite(max 3 gpus)
    "cryptonightV7" = " --cuda-devices $SelGPUCC" #CryptonightV7(max 3 gpus)

save XMRig.ps1

you can then delete ccminercryptonight from miners folder...

this will Enable XMRig it works well but only with up to 3 cards so you have a single 1070 so will work very well...

Hope this Helps you

Best Regards
Nemo

**Comment by scavern** [comment]
I'm confused. So if I switch to XMRig I can mine at nicehash with the stats reflecting correctly?


But if I have more than 3 GPU's I cannot?

________________________________
