### ISSUE TITLE
suprminer SPMOD-GIT does not validate on CPU!

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#574]
**x16s**

![image](https://user-images.githubusercontent.com/1230402/39642689-c69a2cac-4fd2-11e8-8a65-b41857d8b824.png)

![image](https://user-images.githubusercontent.com/1230402/39642716-da539c10-4fd2-11e8-9e5c-98529f6f1bf4.png)

**Comment by nemosminer** [comment]
i know its being fixed now

**Comment by nemosminer** [comment]
fixed thank sp-mod not me he fixed it... i just complied latest commits....

**Comment by nemosminer** [comment]
fixed

**Comment by Braintelligence** [comment]
this is happening again to me, across all of my rigs and across many of the subalgos. I saw keccakc, bmw and shabal or something.
Did anything change?

**Comment by Braintelligence** [comment]
Ok, I just saw in some of the latest commits, that you removed the suprminer. Gonna follow your latest commit.

**Comment by Braintelligence** [comment]
Even with latest commit changes, where you split the miners, I get such errors. They reset each time a new hash order is given, but still.
