### ISSUE TITLE
x16r speeds

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#575]
I know you have done your tests, but here are mine benchmarks:

```
Miner                  Algorithm       Speed mBTC/Day BTC/Day USD/Day BTC/GH/Day Pool
-----                  ---------       ----- -------- ------- ------- ---------- ----
enemyzealot1.08        X16r      103,11 MH/s    2,326 0,00233  22,456    0,02256 zergpoolplus-
ccminerRaven           X16r      102,28 MH/s    2,307 0,00231  22,275    0,02256 zergpoolplus-
ccminersp-hashx16rx16s X16r      100,35 MH/s    2,264 0,00226  21,855    0,02256 zergpoolplus-
ccminerPoolparty       X16r       91,96 MH/s    2,075 0,00207  20,027    0,02256 zergpoolplus-
```

3x 1080 Ti, 3x 1070 Ti overclocked + PILL

Hope it helps.

- ccminerRaven is a good, stable open source x16r miner, consider bring it back

Can you share your x16r overclock settings and results for 1080 Ti and 1070 Ti? Thx.
Mine looks like this:
`GPU0 23.94 MH/s GPU1 24.26 MH/s GPU2 23.83 MH/s GPU3 17.14 MH/s GPU4 16.84 MH/s GPU5 17.41 MH/s`

**Comment by nemosminer** [comment]
sure i'll add Raven back
