### ISSUE TITLE
Suggested number of pools based on number of GPUs?

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#576]
Not really an issue, but more of a question...

Is there a recommended number of pools you should choose based on the number of GPUs you have ?

eg. if you have 1 GPU you shouldn't take more than 2 pools otherwise you may never get paid out.

2 GPUs - 4 pools etc...

**Comment by borzaka** [comment]
There are no rules for that. With a hundreds of GPUs you wouldn't use too many pools either.

I wouldn't choose more than 2 pools, instead find a good all around pool for your desired algos.

With 1 GPU probably I would use NiceHash with their miner. But that's me.
