### ISSUE TITLE
Which pools and settings do you recommend enabling?

### ISSUE THREAD

**Issue by BeardlessDuck** [nemosminer/NemosMiner#577]
Assuming someone had the hashrate to receive regular payouts from all pools, would you recommend enabling all of them?  Are some pools that are flat out better than others?

Do you recommend using the plus option for all pools that support it?  Or would it possibly be better to use the 24 hour option or even the option without plus/24 hour?

In this case, the rig would be all 1080 Tis if that matters.  Does that matter?

**Comment by judgebob** [comment]
I am disappointed that this was closed instantly with no replay.  I can hardly find any data on this topic.....

**Comment by borzaka** [comment]
Nemo recommended zergpool plus + nicehash
https://github.com/nemosminer/NemosMiner/issues/579#issuecomment-386924697
