### ISSUE TITLE
Pool payouts

### ISSUE THREAD

**Issue by judgebob** [nemosminer/NemosMiner#579]
Nemosminer,

Why was this issue closed without any replay.  I was really hoping for an answer to this question.  Information from someone like you would be greatly appreciated in this area.
____________________________________________________________________________________________________________
BeardlessDuck  commented 15 hours ago • ► edited    

Assuming someone had the hashrate to receive regular payouts from all pools, would you recommend enabling all of them? Are some pools that are flat out better than others?

Do you recommend using the plus option for all pools that support it? Or would it possibly be better to use the 24 hour option or even the option without plus/24 hour?

In this case, the rig would be all 1080 Tis if that matters. Does that matter?
 
  @nemosminer nemosminer closed this 13 hours ago

**Comment by nemosminer** [comment]
not really a Issue here Hence why i closed it...
