### ISSUE TITLE
Raven x16r/x16s Spmod-git #3 Skein problems

### ISSUE THREAD

**Issue by papacheal** [nemosminer/NemosMiner#582]
FYI, since moving to this updated miner for x16s today, I've hit consistent problems with CPU validation on the skein algorithm. No overclocking, no power adjustment, stock settings on three different rigs. All crashed with a flurry of skein "Does not validate on CPU" type errors when mining a particular x16s block. Z/Enemy 1.08 miner runs flawlessly on x16s on the same rigs.

Not sure if this is a chronic issue with this miner or...?

**Comment by nemosminer** [comment]
thanks testing myself atm
