### ISSUE TITLE
Feature request: Showing in Currency you set in config

### ISSUE THREAD

**Issue by ErsinErce** [nemosminer/NemosMiner#583]
It would be nice if you can implement this, instead of showing BTC and mBTC together it shows in currency you set and mBTC

NemosMiner-v3.1.ps1 : 134
`$LabelBTCD.Text = ("{0:N2}" -f (($Variables.Earnings.Values | measure -Property AvgDailyGrowth -Sum).sum * $($Variables.Rates.($Config.Currency)))) + " "+ $Config.Currency +"/D   |   " + ("{0:N3}" -f (($Variables.Earnings.Values | measure -Property AvgDailyGrowth -Sum).sum * 1000)) + " mBTC/D"`

**Comment by nemosminer** [comment]
done thankyou
