### ISSUE TITLE
Values retrieved from blockmasters.co correct?

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#584]
Are the numbers I am getting from blockmasters.co correct?

I find it kind of strange that they show almost double of what other pools are showing?

ccminerTpruvotx64      Lyra2z          3,24 MH/s    1,102 0,00110  10,145    0,33988 blockmastersplus-
enemyzealot1.08        X16r           19,49 MH/s    0,988 0,00099   9,092    0,05067 blockmastersplus-
ccminerSp-hashx16rx16s X16r           19,16 MH/s    0,971 0,00097   8,937    0,05067 blockmastersplus-
ccminerAlexis78        C11            30,63 MH/s    0,945 0,00095   8,701    0,03086 blockmastersplus-
ccminerRaven           X16r           18,31 MH/s    0,928 0,00093   8,541    0,05067 blockmastersplus-
ccminerenemy1.03       X17            19,68 MH/s    0,907 0,00091   8,352    0,04610 blockmastersplus-
ccminerAlexis78        X17            19,62 MH/s    0,905 0,00090   8,327    0,04610 blockmastersplus-
spmodphiv1             Phi            33,97 MH/s    0,770 0,00077   7,092    0,02268 blockmastersplus-
ccminerKlausT          C11            23,98 MH/s    0,740 0,00074   6,811    0,03086 blockmastersplus-
ccminerAlexis78phi     Phi            32,32 MH/s    0,733 0,00073   6,749    0,02268 blockmastersplus-

**Comment by scavern** [comment]
I am using the plus option in Nemosminer, does that take into account 24 actual profit?

**Comment by nemosminer** [comment]
i'll fix it today... i have double checked blockmasters, normal and 24hour are working fine its just the plus mode....

**Comment by scavern** [comment]
Any luck with this yet?

**Comment by nemosminer** [comment]
not yet no

**Comment by PoRNo-MoRoZ** [comment]
I'm 99% sure they're artificially increasing their 'current estimates' to raise client base not in fair play.
Please consider removing BlockMasters support from your software or atleast lower their estimates software-side (but they still can raise it afterwards to avoid this).
More details on my investigation can be found in Bitcointalk forum: https://bitcointalk.org/index.php?topic=4101412

**Comment by nemosminer** [comment]
thank you, i have been in contact qith the Dev of Blockmasters all is sorted now it was fixed at there end with API nothing needed changing in NemosMiner ....

Best Regards Nemo

**Comment by nemosminer** [comment]
fixed testing atm to confirm

**Comment by PoRNo-MoRoZ** [comment]
Yeah, their estimates now even lower than other pools (and I noticed them about this, should be fixed I guess), so problem fixed, thanks !

**Comment by nemosminer** [comment]
no promblem
