### ISSUE TITLE
ccminerenemy include devfee

### ISSUE THREAD

**Issue by czjlj** [nemosminer/NemosMiner#590]
Attention!It will hash for a hidden wallet 3-10 minutes after worked 50 minutes.Check pls.

**Comment by Braintelligence** [comment]
I thought it's known that enemy includes a dev fee?

**Comment by nemosminer** [comment]
i take the 1% dev fee into account so it alguds

**Comment by scavern** [comment]
Isn't the same true for any mining software that has a dev fee though? Everytime you switch to it the "dev fee counter" gets reset...

**Comment by nemosminer** [comment]
no not every mining software has a dev fee.. only dstm and claymore and i don't use them either...
 i mine on zergpool or  blazepool...  with dev fee free miners

**Comment by Braintelligence** [comment]
@scavern Nope. There are closed-source miners who don't employ a fee for many of the first minutes, then do their fee round and only THEN activate the optimizations of the closed-source miner. Sadly that's also the reason why specifically those miners are pretty stupid to use for profit-switching algos.

**Comment by nemosminer** [comment]
only dstm/claymore and enemy have dev fee i don't mine etherem or equihash and i don't add enemy1.10 to my "miners" folder there for all the miners I use are dev fee free have no effect on profit switching...
