### ISSUE TITLE
new dstm's ZCash / Equihash Nvidia Miner version v0.6.1

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#591]
> Version 0.6.1
> - fix failover-pool not switching back on ssl errors 
> - fix failover-pool not switching back on some servers 
> - add support for stratum's client.reconnect rpc
> - support configuration of 'temp-target', 'intensity', 'pool' via cmd-line parameters
> - report current difficulty and target on term-ui
> - sort output by gpu_id on term-ui
> - colorize temperature above 70°C on term-ui
> - report intended fan speed on term-ui, web-ui, json-rpc
> - report power consumption on term-ui
> - improve performance on linux systems by ~2%

https://bitcointalk.org/index.php?topic=2021765.0

**Comment by nemosminer** [comment]
thankyou

**Comment by nemosminer** [comment]
done
