### ISSUE TITLE
Enemy 1.08 starts and closes at benchmarks and doesn't recover 

### ISSUE THREAD

**Issue by psynauty** [nemosminer/NemosMiner#592]
Added enemy 1.08 to miner folder, enabled a few algos (hsr, X16r /s, xevan,tribus) nemosminer starts to benchmark but miner closes immediately and never restarts. 
Nemo stuck in benchmarking state but no miner is running

**Comment by borzaka** [comment]
- Check your overclocking settings, try with base settings at first.
- Try to run manually (copy the starting string from the logs) the miner from the Bin folder, and see if there is an error message.

**Comment by nemosminer** [comment]
ok enemy 1.08 can't mine xevan,tribus so good luck with that....

**Comment by psynauty** [comment]
Ace,
Hadn't realised as all the algo options where available in the ps1 file.
All good and thanks for the quick response.
