### ISSUE TITLE
Incorrect intensities with CcminerAlexis78 on GTX1080ti

### ISSUE THREAD

**Issue by UselessGuru** [nemosminer/NemosMiner#593]
I am referring to https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1702 & https://github.com/nemosminer/ccminerAlexis78/releases

I get the following error when running your miner on a **GTX 1080ti:**
```
ccminer.exe -a x17 -o stratum+tcp://europe.mine.zergpool.com:3737 -u 1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF -p BlackBox,c=BTC
*** ccminer alexis-1.0 for nVidia GPUs from alexis78@github ***
*** Built with VC++ 2013 and nVidia CUDA SDK 7.5 (Recommended)

*** Based on tpruvot@github ccminer
*** Originally based on Christian Buchner and Christian H. project
*** Include some of the work of djm34, sp, tsiv and klausT.

[2018-05-13 14:07:31] Starting on stratum+tcp://europe.mine.zergpool.com:3737
[2018-05-13 14:07:31] NVAPI GPU monitoring enabled.
[2018-05-13 14:07:31] 1 miner thread started, using 'x17' algorithm.
[2018-05-13 14:07:31] Stratum difficulty set to 0.1
[2018-05-13 14:07:31] x17 block 266654, diff 819.700
[2018-05-13 14:07:31] GPU#0: Intensity set to 22.5, 6291456 cuda threads
[2018-05-13 14:07:32] GPU#0: result for 00000006 does not validate on CPU!
[2018-05-13 14:07:32] GPU#0: an illegal memory access was encountered
Cuda error in func 'quark_blake512_cpu_setBlock_80' at line 547 : an illegal memory access was encountered.
```

It appears that the miner is using incorrect default intensity (22.5). If I **change it to '-i 21.5'** the miner runs very well.

Other algos report the same problem:
The same goes for **C11**. Default intensity 22 is too high -> **lower intensity to 21.5**.
The same goes for **X11evo**. Default intensity 22 is too high -> **lower intensity to 21**.

**Comment by nemosminer** [comment]
yip i know that...

**Comment by nemosminer** [comment]
. .\Include.ps1

$Path = ".\Bin\NVIDIA-Alexis78\ccminer.exe"
$Uri = "https://github.com/nemosminer/ccminerAlexis78/releases/download/3%2F3%2F2018/ccminer-Alexis78.zip"

$Commands = [PSCustomObject]@{
    "hsr" = " -d $SelGPUCC" #Hsr(fastest)
    #"bitcore" = "" #Bitcore
    "blake2s" = " -d $SelGPUCC" #Blake2s(fastest)
    #"blakecoin" = " -d $SelGPUCC --api-remote" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = "" #Cryptonight
    "veltor" = " -i 23 -d $SelGPUCC" #Veltor(fastest)
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    #"hmq1725" = "" #hmq1725
    "keccak" = " -m 2 -i 29 -d $SelGPUCC" #Keccak(fastest)
    "lbry" = " -d $SelGPUCC" #Lbry
    #"lyra2v2" = " -d $SelGPUCC -N 1" #Lyra2RE2(ccminerxevan faster) 
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = " -d $SelGPUCC --api-remote" #MyriadGroestl
    #"neoscrypt" = " -i 15 -d $SelGPUCC" #NeoScrypt
    "nist5" = " -d $SelGPUCC" #Nist5(fastest)
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    "sib" = " -i 21 -d $SelGPUCC" #Sib(fastest)
    "skein" = " -d $SelGPUCC" #Skein(fastest)
    #"timetravel" = "" #Timetravel
    "c11" = " -i 21 -d $SelGPUCC" #C11(fastest)
    "x11evo" = " -N 1 -i 21 -d $SelGPUCC " #X11evo
    #"x11gost" = " -i 21 -d $SelGPUCC --api-remote" #X11gost
    "x17" = " -i 20 -d $SelGPUCC" #X17(enemy1.03 faster)
    #"yescrypt" = "" #Yescrypt

**Comment by UselessGuru** [comment]
> yip i know that... check my ccminerAlexis78.ps1 in "miners" folder has correct intensity already

I cannot test, but do these intensities also work for other cards, e.g. GTX1060 or GTX1070?
Since you have the source code (and know how to compile) it should be easy to 'fix' it.

**Comment by nemosminer** [comment]
yes works on all cards from 10603gb to 1080ti and everything in between...
