### ISSUE TITLE
Wrong --solver parameter in EWBF miner?

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#597]
If I run the EWBF miner without the `--solver 0` parameter, it will benchmark at set solvers:
- solver 2 for 1080 Ti
- solver 0 for 1070 Ti

![image](https://user-images.githubusercontent.com/1230402/40129339-54d4c788-5934-11e8-8091-6a28bd5bb06a.png)

So, why the fixed `--solver 0`?

BTW, for me, EWBF is faster than DSTM - after removing the 2% dev fee.

**Comment by nemosminer** [comment]
do the speeds differ? solver 2
solver 0?
