### ISSUE TITLE
adding Bminer - a faster Equihash miner

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#598]
[Bminer: When Crypto-mining Made Fast](https://www.bminer.me/)
[Bitcoin Forum thread](https://bitcointalk.org/index.php?topic=2519271.0)

I know it has a bad reputation, and a closed source, but with the new version I'am having ~2,5% improvement compared to EWBF (fastest miner in my case).

With my 3x 1080 Ti, 3x 1070 Ti RIG, I have:
- 3,85 KH/s with EWBF (3,81 KH/s with DSTM after removing 2% dev fee)
- 3,95 KH/s with Bminer (after removing 2% dev fee)

Probably longer tests required to check these numbers on pool as well.

Edit 1.:
Snapshot from Mining Pool Hub looks OK:
![image](https://user-images.githubusercontent.com/1230402/40132559-66e55740-593d-11e8-890f-9cf355570c59.png)

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/archive/Bminer-testing.zip

Newest Bminer added Need help getting benchmark to complete

**Comment by borzaka** [comment]
Tested. Results, and comments:
- At first start, it downloaded Bminer, but not benchmarked (not was in the list, probably had to wait one interval), only after complete restart - common issue, I already reported ;) #533
- Starting command line for password is wrong.
Example from the [site](https://www.bminer.me/examples/):
`bminer -uri stratum://foo.w:pwd@us-east.equihash-hub.miningpoolhub.com:17023`
What was actually runned:
`bminer.exe  -api 127.0.0.1:1880 -uri stratum://borzaka.nvidiaworker.x@europe.equihash-hub.miningpoolhub.com:17023`
So, separate password with `:` not `.`
- The benchmark results wasn't saved after 3 intervals, still 'Benchmarking'...
I have 600 sec interval and 600 sec `StatsInterval`
![image](https://user-images.githubusercontent.com/1230402/40167675-ea1d548a-59c1-11e8-8d96-cd1348b4aadc.png)

- You can use comma separated GPU counts, as in any ccminer:
`-devices $SelGPUCC`
- Consider turn off watchdog:
`-watchdog false`
> Automatic restart to recover from hung GPUs. Bminer exits itself in case of errors if watchdog is disabled.

I saw that you used this for EWBF (`--eexit 1`)
- There is a `-nofee` option: 
> Disable the devfee but it also disables some optimizations.

I haven't tested, but probably we would loose more than 2% (dev fee) if we turn this off.

**Comment by nemosminer** [comment]
added in optional
