### ISSUE TITLE
Excavator

### ISSUE THREAD

**Issue by bit2017user** [nemosminer/NemosMiner#600]
error with for both of them on the latest from 2 hours ago
![untitled](https://user-images.githubusercontent.com/37226252/40150169-00222c30-5970-11e8-8c3b-ddd9022e5f9a.jpg)

**Comment by nemosminer** [comment]
https://imgur.com/a/nXm36tN

**Comment by nemosminer** [comment]
nope

**Comment by borzaka** [comment]
@nemosminer This is a real issue: the config file for Excavator is not present when the Excavator first runs. After restarting NemosMiner it works, but for the first time, it doesn't.

**Comment by Braintelligence** [comment]
@borzaka I already filed an issue for this. There was no action at that time as well.

**Comment by borzaka** [comment]
@Braintelligence I know :( We have to convince @nemosminer, that this is real, and need further investigation :)

**Comment by nemosminer** [comment]
After restarting NemosMiner it works, but for the first time, it doesn't.

then restart NemosMiner.... 

  Run NemosMiner-v3.1.bat
  1. Config tab
  2. Set your Wallet address and Username
  3. Select your pool/s and load default Algos button. (Remove any algos you do not want to mine)
  4. "Save Config"
  5. Close
  Run NemosMiner-v3.1.bat
  6."Start"

note: number 5  6...

**Comment by borzaka** [comment]
I have done that (as always, when testing, and starting first). It needs another restart after that...

**Comment by nemosminer** [comment]
ok thanks not the end of the world
