### ISSUE TITLE
Z-ENEMY VER 1.10 (PUBLIC)

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#601]
> For Windows (Cuda 9.1)
> zealot/enemy-1.10 (z-enemy) From: Dk & Enemy
> 
> - Fixed compatibility issues that resulted in performance degradation with some non-yiimp pools. Now you'll see the expected hashrate on them (suprnova).
> 
> - Kernels speed improvements : (1.09a vs 1.10) +1-2% total (all algos) and (1.09b vs 1.10) +1-2% for x16r &x16s.
> 
> - Support & impove new algo : Tribus (-a tribus) , recommended intensity for Tribus 20-21. +5% speed vs 1.09b ( Service release)

[source](https://bitcointalk.org/index.php?topic=3378390.0)

**Comment by Braintelligence** [comment]
@nemosminer 
Currently this seems to be the fastest miner for X17, Phi, x16r (by 30% margin, omg) and x16s. Can you confirm?

**Comment by borzaka** [comment]
For me;
- fastest x17: ccminerenemy1.03
- fastest phi: spmodphiv1
- fastest x16r: enemyzealot1.10
- fastest x16s: enemyzealot1.10

**Comment by Braintelligence** [comment]
ccminerenemy1.03 doesn't work for my 12+ GPU rigs, it says something about a GPU ID that doesn't exist.

I can confirm spmodphi is faster by 0,0078% in my case. Not enough reason for me to switch.

**Comment by Braintelligence** [comment]
Oh yeah, I also confirm enemyzealot 1.10 is way better than TPruvot and Nanashi for Tribus for me.

**Comment by nemosminer** [comment]
no can't confirm i don't use it...
