### ISSUE TITLE
adding faster neoscrypt miner

### ISSUE THREAD

**Issue by miner232** [nemosminer/NemosMiner#604]
there is need to add faster neoscrypt miner. hsrminer is 10% faster then ccminer klausT on neoscrypt algo.

**Comment by miner232** [comment]
also bitcore faster miner: BitcoreSPmod2-its free

**Comment by borzaka** [comment]
Excavator is the fastest NeoScrypt miner, and it's also free.

Copy `Excavator.ps1` from `OptionalMiners` to `Miners` folder.

**Comment by miner232** [comment]
great bytw it stuck on checking version please fix

**Comment by miner232** [comment]
no mether it was net lag you can close ty!

**Comment by nemosminer** [comment]
there is no need to add hsr miner Excavator is faster and has no dev fee
