### ISSUE TITLE
Enabled ahashpoolplus, pool stats are not updated ever since

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#607]
- First, I was only using zergpoolplus.
- I enabled ahashpoolplus as well, so zergpoolplus and ahashpoolplus are enabled.
- It's mining one algo (x17) ever since.
- Earnings are not updated; it's still:
```
Miner                Algorithm       Speed mBTC/Day BTC/Day USD/Day BTC/GH/Day Pool
-----                ---------       ----- -------- ------- ------- ---------- ----
ccminerenemy1.03     X17       107,05 MH/s    3,000 0,00300  24,277    0,02803 ahashpoolplus-3
```
**for even after 8 hours**.

On the pool, my earnings is nothing near to 0,003 BTC/Day - it should be 0,001 after 8 hours (1/3 day), but it's ~0,0003

![image](https://user-images.githubusercontent.com/1230402/40390751-79d17586-5e16-11e8-9c9e-8283d8d64361.png)

- cache?
- divisor problem?

**Comment by borzaka** [comment]
**After 16 hours**, earnings for ahashpool still not changed (for zergpoolplus it does):
![image](https://user-images.githubusercontent.com/1230402/40405713-06542b74-5e5e-11e8-9d9a-662963a936a6.png)

It's still mining x17 ever since with ccminerenemy1.03.

I have earned this time (16 hours) at the pool ~0,0005 BTC, which is nothing close the the estime 0,03 BTC/Day.

Clearly something is wrong. What's the problem?

**Comment by MrPlusGH** [comment]
This is the expected behavior on the current version.
BrainPlus is not started when changed on the fly. So it gives static values.
On the fly changes will be available in the next version of NPlusMiner which should be coming in a few days
