### ISSUE TITLE
Feature Request: Backup Benchmark results and auto reset on InvalidJsonException

### ISSUE THREAD

**Issue by dangi12012** [nemosminer/NemosMiner#608]
If there is a power outage or the miner crashes, 80% of the time Nemosminer wont work after. I tried to test Nemosminer for a big Rig ~600 Gpus but with 3.1 the software is still not robust enough for productive use.

Feature: Automatically backup all config files and restore them if an invalid Json Exception is detected. This way the miner is still functional after a sudden crash.

**Comment by nemosminer** [comment]
ok for me when there is a power cut my miners automatically turn back on after  (bios setting) and start mining... no  invalid Json Exception detected... i'll look into it more for you

**Comment by dangi12012** [comment]
Well the Json only gets corrupted like 40% of the time but then the miner is broken. So if you repeat simulating a power outage for 5x it should happen. 

Another fix would be to write to temp files only and then delete and rename to main name. This way only non corrupted jsons can exist at any time.

**Comment by scavern** [comment]
Why not have some proper power management though to prevent this? It seems a bit silly to rely on the mining software for this - especially for such a large scale operation I'm assuming the files were corrupted as they were open at the time the power cut occurred, but in saying that any of your OS files could also be come corrupted.

**Comment by dangi12012** [comment]
Well you see no other miner keep files open during mining. This way nothing gets corrupted. And miners do 100% crash after a while, and it would be good for the software to be robust enough to keep mining like ALMOST ALL OTHER mining software out there.
