### ISSUE TITLE
Enabled another pool, but Earnings Tracking for that pool is not shown

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#609]
- First, I was only using zergpoolplus.
- I enabled ahashpoolplus as well on the fly.
- NemosMiner window shows only my ahashpool Earnings Tracking.

After restart, it shows my ahashpool Earnings Tracking as well.

Can't change settings on the fly, because abnormal activities will occur. Always needs restart after changing some settings. --> put it in the readme maybe?

**Comment by MrPlusGH** [comment]
This is the expected behavior on the current version.
On the fly changes will be available in the next version of NPlusMiner which should be coming in a few days
