### ISSUE TITLE
how to run on start up...

### ISSUE THREAD

**Issue by StartxPH** [nemosminer/NemosMiner#610]
how to run on start up...

i keep getting error running auto run with shortcut even with auto start...

there is no readme file on how to auto run on start up.. please help

**Comment by nemosminer** [comment]
1 .right click on NemosMiner-v3.1.bat   (send to: desktop(shortcut)

2.copy the desktop shortcut 

3. startmenu /  open run / in run type  shell:startup  

4.paste you copy desktop short cut into startup folder

Done 
Best Regards
Nemo

**Comment by MrPlusGH** [comment]
https://github.com/MrPlusGH/NPlusMiner-Documentation/wiki/Autostart
