### ISSUE TITLE
DelosMiner 1.1.2

### ISSUE THREAD

**Issue by centreece** [nemosminer/NemosMiner#612]
> optimized for BitCore, HMQ1725, HSR, Phi, Skunk, x16r, x16s, x17

[Source](https://bitcointalk.org/index.php?topic=4344544.msg38869231#msg38869231)

**Comment by centreece** [comment]
Version 1.2.1 was released today!

**Comment by nemosminer** [comment]
thanks

**Comment by nemosminer** [comment]
done testing
