### ISSUE TITLE
Feature request: Add a check for CUDA version on start

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner#614]
I downloaded today's most updated NemosMiner and was getting multiple errors upon benchmarking. Checked the issue and the failing miners were telling me that Cuda 9.2 needed to be installed. I shouldn't have to check manually to find out what is going on - obviously we are supposed to be running recent versions of CUDA but it would really help if NemosMiner just ran a quick check along with its version check. Thanks for considering this enhancement.

**Comment by nemosminer** [comment]
read me .....

Requires Nvidia driver 397.44 or newer

**Comment by nemosminer** [comment]
https://www.geforce.com/drivers/results/134624
