### ISSUE TITLE
Can't get balance value from MPH

### ISSUE THREAD

**Issue by lyesbenhouhou** [nemosminer/NemosMiner#615]
Hi all,

Just ask if it's normal to can't get the balance value of MPH despite my API key/user/workername are provided.
No problem to get balance of other pools (nicehash, zerg, blaze).

Also, if someone can provide me the method to change the MPH's payement treshold from 0.01 to 0.002.
Tried to change the value of "PaymentThreshold" in the file /Config/poolapiref.json without success.

Thanks in advance.
Lyes

**Comment by borzaka** [comment]
I'am experiencing the same.

**Comment by nemosminer** [comment]
i dont use miningpool hub... just got to there website and check until i do more testing i alwalys use nicehash for eth cryptov7 equihash....

**Comment by nemosminer** [comment]
MPH's payement treshold from 0.01 to 0.002

i have to change it but it will change for everyone i use 0.01 you can change yours to 0.01 in miningpoolhub settings 0.002 is a low threshold...

**Comment by borzaka** [comment]
I'am using [MiningPoolHubStats](https://miningpoolhubstats.com) to check my balance on MPH.

It would be nice to see it in NemosMiner, but I'am not sure it's possible; you can change your autoexchange coin at any time, and it's not in the stats. MiningPoolHubStats is not giving you good results, until you register, and give info about your autoexchange coin.

**Comment by nemosminer** [comment]
thanks https://github.com/nemosminer/NemosMiner/commit/7507536a001a2359c1585ed51e656754cd476599
