### ISSUE TITLE
Missing wallet info and wrong Stratum in history window

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#619]
I just started a new benchmark;

![image](https://user-images.githubusercontent.com/1230402/40856618-cdd5b24a-65d8-11e8-8981-8d45bcfb3b0c.png)

**Comment by nemosminer** [comment]
miningpoolhub

**Comment by borzaka** [comment]
Some Stratum come from the miner lunch commands:

`miner.exe --api 127.0.0.1:4068 --server europe.equihash-hub.miningpoolhub.com --port 17023 --fee 0 --solver 0 --eexit 1 --user borzaka.nvidiaworker1070ti --pass x --cuda_devices 3 4 5 --intensity 64`

`zm.exe --telemetry=127.0.0.1:4068 --server europe.equihash-hub.miningpoolhub.com --port 17023 --user borzaka.nvidiaworker1070ti --pass x -d 3 4 5 --color`
