### ISSUE TITLE
no miners running

### ISSUE THREAD

**Issue by zuhair01** [nemosminer/NemosMiner#622]
i was restoring my pc installed.
no miners running please help!
![capture](https://user-images.githubusercontent.com/24286542/40973946-b6187df6-68ce-11e8-9b04-db89252634bb.PNG)

**Comment by Atikeen** [comment]
Comfirmed. I guess it began on June 4th or 3rd. Till then worked fine.

**Comment by nemosminer** [comment]
not confirmed everything is fine... just download and tested master now no problems at all...

your problem is at your end...

**Comment by Atikeen** [comment]
The problem was with CUDA 9.2.88 + driver 398.11 + VS 2017. Needed to uninstall completely everything of NVIDIA, install VS 2017, then CUDA with its driver, then update the driver itself. Looks like working for now.
