### ISSUE TITLE
How to add Cryptpnight Algo from MPH

### ISSUE THREAD

**Issue by rinkal26783** [nemosminer/NemosMiner#627]
I have nemos 3.1 and want to mine Cryptonight-Monero coins
I have added Cryptonight-Monero, Cryptonight, CryptonightV7 to algo list but it doesnt add Cryptonight coins to mining list.

**Comment by nemosminer** [comment]
MPH-Cryptpnight not working atm..

 i recommend nicehash for CryptonightV7

**Comment by nemosminer** [comment]
fixed sorry it took so long
