### ISSUE TITLE
update to ENEMY 1.11 

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#628]
> Z-ENEMY VER 1.11 (PUBLIC v4)
> 
> For Windows (Cuda 9.1)
> zealot/enemy-1.11 (z-enemy)  From: Dk & Enemy
> 
> - Performance improvements: x17 (+4-8%), x16r&s (+1-3%) and other ...
> 
> - Fast start on multi gpu-rigs
> 
> - GPUs limit increased to 24
> 
> - AeriumX(AEX) - the miner supports Aerium new swap algo (-a aeriumx), starting 4th June.
> 
> - Added: C11(-a c11) basic and fast x64(ver.4) , Skunk(-a skunk) basic , improved TimeTravel8(-a timetravel) and Polytimos (-a poly)

[source](https://bitcointalk.org/index.php?topic=3378390.0)

**Comment by nemosminer** [comment]
i'll update today

**Comment by nemosminer** [comment]
done testing atm

**Comment by sasukexy** [comment]
Error: Unable to query the number of cuda devices 
I kept getting this error, I've tried both version 1.11 and 1.10 and my drivers are upto date 
please help

**Comment by borzaka** [comment]
Post your command line how did you runned Z-ENEMY.
