### ISSUE TITLE
Cryptodredge miner

### ISSUE THREAD

**Issue by airwalker1** [nemosminer/NemosMiner#631]
Please add support for this new miner - getting some very good results.

https://bitcointalk.org/index.php?topic=4129696.0

**Comment by borzaka** [comment]
[CryptoDredge 0.4.1 Nvidia GPU Miner With Faster Lyra2REv2 Performance](https://cryptomining-blog.com/9892-cryptodredge-0-4-1-nvidia-gpu-miner-with-faster-lyra2rev2-performance/)

**Comment by nemosminer** [comment]
(allium) test

**Comment by nemosminer** [comment]
https://github.com/technobyl/CryptoDredge/releases

2moros job test and https://github.com/DumaxFr/ccminer

**Comment by nemosminer** [comment]
no API

**Comment by buxstore** [comment]
https://github.com/CryptoDredge/beta/releases/tag/v0.6.0-beta.2 should be compatible with awesome miner as ccminer 2.3
Could you check it?
API had added
