### ISSUE TITLE
Pigeoncoin Miner / CUDA 9.2 / if statement

### ISSUE THREAD

**Issue by centreece** [nemosminer/NemosMiner#632]
I'm not sure if you can add this, as it might not work on all systems due to CUDA 9.2:

https://github.com/Pigeoncoin-Miner/Pigeoncoin/releases/tag/v2.6-64bit-cu92

Could you add an if statement that selected betweet new and old CUDA based on the driver that is installed?

**Comment by nemosminer** [comment]
Requires Nvidia driver 397.44 or newer
