### ISSUE TITLE
ccminerKlaust retry pause is out of range

### ISSUE THREAD

**Issue by g5-freemen** [nemosminer/NemosMiner#633]
![image](https://user-images.githubusercontent.com/36886126/41435403-5daa29fc-7027-11e8-85ff-3c243bdede41.png)

-R 0 causes an error, -R 1 works fine

**Comment by nemosminer** [comment]
NO -r 0 does not cause error...

**Comment by g5-freemen** [comment]
not small "r", big "R"

**Comment by nemosminer** [comment]
got ya thankou
