### ISSUE TITLE
ccminer-klaust "Value for retry pause is out of range"

### ISSUE THREAD

**Issue by jpbcx43** [nemosminer/NemosMiner#636]
When doing initial benchmarking, I saw that ccminer Klaust was in a Running: Failed: 1 state. I manually typed in the parameters of the string, to see the miner report "Value for retry pause is out of range."

If I remove the -R 0 before declaring -a neoscrypt, the miner starts with no issues. 

In your ccmienrKlausT.ps1 file, on line 48, I changed the -R to -r, and it works:

Arguments = "-b $($Variables.MinerAPITCPPort) -r 0 -a $_ -o

**Comment by nemosminer** [comment]
ok i'll test ccminer-klaust 

- R 1 should be working its working with all other ccminers...

**Comment by jpbcx43** [comment]
No worries, something I noticed, just bringing it to your attention. Awesome software, really mind blowing actually.

**Comment by nemosminer** [comment]
it should be -R 1 not -R 0

its working correctly
