### ISSUE TITLE
Equihash - BMiner not starting up

### ISSUE THREAD

**Issue by isak-ialogics** [nemosminer/NemosMiner#638]
BMiner for equihash was not starting up for me on ZPoolPlus. 
Command used to launch had a "," in it, which caused it to fail.

I edited the  \Miners\Bminer.ps1 script from:

`Arguments = " -api 127.0.0.1:$Port -nofee -uri stratum://$($Pools.(Get-Algorithm($_)).User),$($Pools.(Get-Algorithm($_)).Pass)@$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port)$($Commands.$_)"`

to

`Arguments = " -api 127.0.0.1:$Port -nofee -uri stratum://$($Pools.(Get-Algorithm($_)).User).$($Pools.(Get-Algorithm($_)).Pass)@$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port)$($Commands.$_)"`

Seems to be launching fine now.

**Comment by nemosminer** [comment]
not sure why you command had that , ...

my source code is:

-api 127.0.0.1:$Port -nofee -uri stratum://$($Pools.(Get-Algorithm($_)).User).$($Pools.(Get-Algorithm($_)).Pass)@$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port)$($Commands.$_)"
