### ISSUE TITLE
xmr-stak 6x1080ti <C:/xmr-stak/xmr-stak-2.4.5/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:312

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#643]
you need to go into "Bin" folder / "CryptoNight-FireIce" folder

find nvidia.txt   open/edit it

you need to change blocks to 28

like this: 

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 1,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 2,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 3,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 4,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9308/11264 MiB
  //      smx: 28
  { "index" : 5,
    "threads" : 54, "blocks" : 28,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

save 

xmr-stak will now run on 6x1080ti rigs

**Comment by borzaka** [comment]
You only need to change the default `"bfactor" : 6` to `8` for a 1080 Ti. Everything else can be leaved at default.
You can try 10, if your GPU is serving a monitor as well.

**Comment by nemosminer** [comment]
havn't tryied changing "bfactor"

**Comment by borzaka** [comment]
My nvidia.txt for a 6x 1080 Ti rig:

```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9309/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9309/11264 MiB
  //      smx: 28
  { "index" : 1,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9310/11264 MiB
  //      smx: 28
  { "index" : 2,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9310/11264 MiB
  //      smx: 28
  { "index" : 3,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9310/11264 MiB
  //      smx: 28
  { "index" : 4,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9310/11264 MiB
  //      smx: 28
  { "index" : 5,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],
```

I only changed bfactor 6 to 8.

**Comment by nemosminer** [comment]
thanks only 6x1080ti seem to have this problem 

i've tested 8x10603g 6x1070 6x1070ti and 6x1080ti rigs

**Comment by nemosminer** [comment]
cryptodredge now handles cryptonight variants
