### ISSUE TITLE
fall over between pools

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#644]
Zergpool went down for 30min today. I was expecting nemos to then switch to nicehash as I have Zergpool and Nicehash ticked. But that did not happen. the miners just kept on replying to connect. I understand that ccminer does not have a fail over setting as does clymore. Is that not something Nemosminer can address? when ccminer fails to connect for a few times it should excet and nemosminer should then try another algo/pool

**Comment by nemosminer** [comment]
i have zerg and nicehash selected and all my miners switched to nicehash while zerg was down and the switched back when zerg came back online i didnt have to do anything...

**Comment by jjziets** [comment]
mine just sat there. I am using the master as you have not update in a long time.

**Comment by nemosminer** [comment]
mine didin't... i was using master as well
