### ISSUE TITLE
Adding Ravencoin Miner 3.1

### ISSUE THREAD

**Issue by centreece** [nemosminer/NemosMiner#645]
Could you add the latest release?

https://github.com/RavencoinProject/RavencoinMiner/releases

Prefferably the CUDA 9.2 build!

**Comment by nemosminer** [comment]
sure

**Comment by jjziets** [comment]
how do I add this?

**Comment by nemosminer** [comment]
i'll test and add in a couple of hours 

My current ccminerx16r which is forked from vhttps://github.com/sp-hash/suprminer is faster and is cuda9.2

**Comment by nemosminer** [comment]
testing atm will have to do a full 48 hour test on 6x  1080ti's for x16r algo to get a true average
