### ISSUE TITLE
Warning of Delosminer.

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#649]
FIY
There have been several reports now of people having their wallets hacked after downloading Delosminer. The wallets auto transfer maximum funds out to hackers address once amounts of 5k - 10k are met. Anyone who has downloaded it already should transfer all funds to another wallet and clean install OS, burning the original wallet.dat. Delosminer is obviously communicating with wallets after downloading. Issue persists even after removing miner.

**Comment by jjziets** [comment]
A warning for miners
A program called  CNlargement just got posted in another discord, claiming higher hashrates for cryptonight
It appears it actually just installs a hidden monero miner on your system and mines for someone else
So don't install it

Stick to the trusted/well known miners.

**Comment by jjziets** [comment]
soruce https://discordapp.com/channels/407610160580657164/407801978333167617

**Comment by jjziets** [comment]
why people risk mining on systems with a wallet is beyond me.

**Comment by nemosminer** [comment]
thanks delos  is already disabled by Default in NemosMiner... you have to copy it over yourself if you really want to use it....

**Comment by nemosminer** [comment]
and plans on adding CNlargement

**Comment by nemosminer** [comment]
i added this issue to Read Me in OptionalMiners
