### ISSUE TITLE
Add EWBF Equihash miner to OptionalMiners

### ISSUE THREAD

**Issue by platinum4** [nemosminer/NemosMiner#652]
Different than the usual 0.3.4b

https://bitcointalk.org/index.php?topic=4466962.0

only has MEGA/GoogleDrive links for downloads; could be useful to host your own copy and make a .ps1 in OptionalMiners for this miner

**Comment by pinpins** [comment]
we have added equihash192 to zergpool.com which exactly is being mined with EWBF 0.3

**Comment by nemosminer** [comment]
done
