### ISSUE TITLE
Profit predictions for x16r and x16s.

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#655]
The X16R hashing algorithm consists of 16 hashing algorithms operating in the chain
fashion with the ordering dependent on the last 8 bytes (16 nibbles) of the hash of the
previous block. The hashrate very wildly due to all the possible combinations. making profit predictions unreliable at best. 

I have two suggestions. At this stage, the combination of x16r and x16s is just too much to use an average over time for the 16r and x16s. the variance on profit is huge making switching unreliable. 

As the last block determines the next sequence it should be theoretically possible for NEMOSMINER to monitor the miner and get an updated hashrate shortly after a change. Thus recalculate the profitability. Assuming difficulty adjust can be updated aswell. 

The problem is if minerx16 is not running. Then NEMOSMINER will not be sure what the new profitability will be except if it runs the miner again. Which would not be beneficial given the frequency of the changes in blocks. Another method would be to benchmark each of the 16 algorithms then it should theoretically be possible for NEMOSMINER predict what the new hash rates would be for that combination of algorithms. This might have a lower error than averaging.

**Comment by nemosminer** [comment]
only x16r 

x16s does not have that promblem
