### ISSUE TITLE
Lyra2RE2 Benchmark is not correct

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#656]
Lyra2RE2 Benchmark is not correct, I tried to benchmark couple of times already.
<img width="556" alt="lyra2re2" src="https://user-images.githubusercontent.com/37470062/41931997-d0bad582-7990-11e8-890b-5c92c7e8750b.png">

**Comment by nemosminer** [comment]
not sure why YOU are having that issue im not....

**Comment by regener** [comment]
I am having the same issue.
I could fix it by setting the GPU intensity to an exact number (20 instead of 20.5) or auto (0) value inside Miners/_affectedminername_.ps1 file.

**Comment by yuizen** [comment]
No matter how I re-benchmark it it’s always like that. I’m not the only one. Also my colleague. I’m not sure why and how it is happening. All I can do is disable it.
