### ISSUE TITLE
zealot enemy is a scam

### ISSUE THREAD

**Issue by spykerhond** [nemosminer/NemosMiner#658]
![untitled](https://user-images.githubusercontent.com/40660997/42028670-37903fe4-7acd-11e8-9539-6869cd371780.jpg)

this is a scam and comes straight from them. note the 11 dev fee in the middle of the night !!! CUNTS

**Comment by jjziets** [comment]
why would they tell you it is a dev fee if they wanted to scam you?

**Comment by platinum4** [comment]
It's actually not much better than the nemos recompiled ccminers now

**Comment by spykerhond** [comment]
Yiimp is now suspect because they get angry when they drop your pay from 700 to 480 after 15 days and then this happens after 28 days because i took my eyes off the miners. After switching to Suprnova all is normal again. how does Suprnova pay 700 plus without any fees , and yiimp pays 200 less with a 2 % fee ?

**Comment by spykerhond** [comment]
That 11 persent plus 2 persent make almost 14 persent vic, someone is gangster.

**Comment by nemosminer** [comment]
Zealot is in OptionalMiners its your choose if you want to Enable it..
