### ISSUE TITLE
negative profit? 

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#659]
![image](https://user-images.githubusercontent.com/19214485/42039921-c987e520-7aee-11e8-96f1-1b0685c8d1c0.png)

Any idea why my profit calc on zergpool is so out? all the Time? I have reset it menay times but it never gives me number i trust.

**Comment by thebeerbaron2018** [comment]
It's because the pool has paid you out recently and the code for calculating the profit doesn't take this into consideration sometimes.  I have already suggested a better way of calculating the profit values which will correct this in the open issue #629

**Comment by MrPlusGH** [comment]
Could you share the chart from ZergPool for the same time frame. Is it showing decrease?
