### ISSUE TITLE
Bitcore and Phi2 showing zero profit on ZergpoolPlus

### ISSUE THREAD

**Issue by TGM8599** [nemosminer/NemosMiner#660]
The API looks fine for Bitcore and Phi2 on Zergpool (Plus), but both are showing 0.000 mBTC/day and are consequently not being utilized by NemosMiner v3.2.  Likely due to 0 actual over 24h.  Is there a way to weight the current vs. 24h differently (similar to HashAuger).

**Comment by MrPlusGH** [comment]
Phi2 works for me

**Comment by TGM8599** [comment]
Yes, works for me as well now that a block was won in the last 24h, but I left this open for the question about user-adjustable weighting of current estimate and 24h actual.

**Comment by nemosminer** [comment]
working well now phi2 was only just added
