### ISSUE TITLE
phi and phi2 assigned incorrect miner.

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner#666]
C:\NemosMiner>Bin\NVIDIA-TPruvot\ccminer.exe -b 4068 -N 1 -R 1 -q -a phi -o  stratum+tcp://phi.mine.zergpool.com:8333 -u  123 -p ID=NemosMiner3.2,c=BTC -d 0,1,2,3,4
*** ccminer 2.2 for nVidia GPUs by tpruvot@github ***
[2018-06-29 22:10:24] Unknown algo parameter 'phi'
Try `ccminer --help' for more information.

C:\NemosMiner>Bin\NVIDIA-TPruvot\ccminer.exe -b 4068 -N 1 -R 1 -q -a phi2 -o  stratum+tcp://phi2.mine.zergpool.com:8333 -u 123 -p ID=NemosMiner3.2,c=BTC -d 0,1,2,3,4
*** ccminer 2.2 for nVidia GPUs by tpruvot@github ***
[2018-06-29 22:11:45] Unknown algo parameter 'phi2'
Try `ccminer --help' for more information.

**Comment by platinum4** [comment]
Again, you are not using ccminer v2.3 here.

**Comment by nemosminer** [comment]
ccminer 2.3 only use latest source code : https://github.com/nemosminer/NemosMiner/archive/master.zip
