### ISSUE TITLE
lyra2z submit stale

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner#667]
C:\NemosMiner>Bin\NVIDIA-TPruvot\ccminer.exe -b 4068 -N 1 -R 1 -q -a lyra2z -o stratum+tcp://lyra2z.mine.zergpool.com:4553 -u 123 -p ID=NemosMiner3.2,c=BTC -d 0,1,2,3,4 --submit-stale -i 20.50
unknown option -- submit-stale
*** ccminer 2.2 for nVidia GPUs by tpruvot@github ***
unknown option -- submit-stale
Try `ccminer --help' for more information.

**Comment by platinum4** [comment]
That's a very old version of ccminer, what miner file loaded that?

**Comment by jagauthier** [comment]
Beats me.. i just did a git pull.. I haven't used nemos in a few months. I will clone into a new folder.

**Comment by platinum4** [comment]
That looks like Nanashi-mod, let me know which miner file does that ok

**Comment by platinum4** [comment]
https://github.com/nemosminer/NemosMiner/pull/670
