### ISSUE TITLE
CryptoDredge with API

### ISSUE THREAD

**Issue by buxstore** [nemosminer/NemosMiner#672]
https://github.com/CryptoDredge/beta/releases/tag/v0.6.0-beta.2 should be compatible with awesome miner as ccminer 2.3
Could you check it?
API had added

**Comment by nemosminer** [comment]
thanks will check

**Comment by platinum4** [comment]
https://github.com/nemosminer/NemosMiner/pull/673

**Comment by platinum4** [comment]
Doesn't gather hashrates, but it will gather power draw and compute usage

**Comment by buxstore** [comment]
so pity!

发自我的 iPhone X

**Comment by buxstore** [comment]
so pity

发自我的 iPhone

**Comment by buxstore** [comment]
so pity！

发自我的 iPhone X

**Comment by buxstore** [comment]
How can i use it?

发自我的 iPhone X

**Comment by buxstore** [comment]
AwesomeMiner works fine
0.0.0.0:4031

**Comment by buxstore** [comment]
https://github.com/technobyl/CryptoDredge/releases/download/v0.6.0/CryptoDredge_0.6.0.zip
Add ccminer 2.3 compatible API
Add --cpu-priority option to set process priority (0 - 5)
Other minor fixes

**Comment by nemosminer** [comment]
0.0.0.0:4031

**Comment by buxstore** [comment]
Doesn't gather hashrates

**Comment by nemosminer** [comment]
does now
