### ISSUE TITLE
CuBalloon overrides user-keyed ps1 entries

### ISSUE THREAD

**Issue by TGM8599** [nemosminer/NemosMiner#678]
CuBalloon is working with 8x 1080 GPUs, but generates syntax for 11 cards with 64 threads each even when using user-modified CuBalloon.ps1 file.  Recommended threads per 1080 is 384, but (—cuda_threads 384,384,384,384,384,384,384,384) is printed in addition to (—cuda_threads 64,64,64,64,64,64,64,64,64,64,64), with the latter taking precedence.

**Comment by nemosminer** [comment]
you can edit cuballoon.ps1 and edit line. 16

Arguments = " -b $($Variables.MinerAPITCPPort) -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_) --cuda_devices 0,1,2,3,4,5,6,7,8,9,10,11 --cuda_threads 64,64,64,64,64,64,64,64,64,64,64,64 --cuda_blocks 48,48,48,48,48,48,48,48,48,48,48,48 --cuda_sync 0 -t 0"
