### ISSUE TITLE
bminer parameters

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner#679]
This failed, and my whole rig sat for hours doing nothing.
Seems to correlate to zergpool adding  equihash

Failed:  1

    Speed Exited   Active   Cnt  Command
    ----- ------   ------   ---  -------
0.00 PH/s 00:17:07 00:00:00 Once Bin\NVIDIA-Bminer\bminer.exe  -api 127.0.0.1:1880 -watchdog=false -nofee
                                 -no-runtime-info -no-timestamps -uri stratum://1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE.Nemo
                                 sMiner3.2,c=BTC@equihash.mine.zergpool.com:2142 -devices 0,1,2,3,4

**Comment by nemosminer** [comment]
thanks
