### ISSUE TITLE
Second NiceHash wallet

### ISSUE THREAD

**Issue by A120970n** [nemosminer/NemosMiner#680]
Please add the ability to enter a second NiceHash wallet. They do have an internal wallet with a withdrawal of 10 times less than the external. For miners with small capacities this is important.

**Comment by MrPlusGH** [comment]
This is already available with advanced config.
See: https://github.com/MrPlusGH/NPlusMiner/blob/master/README.md
Section: Per pools config (Advanced)

**Comment by nemosminer** [comment]
done
