### ISSUE TITLE
Program crashing

### ISSUE THREAD

**Issue by joeyoon80** [nemosminer/NemosMiner#681]
I started using your miner last week. I started to notice random crashes that happen. My rig runs 3x Asus GTC 1070 with latest nVidia drivers. Can u guide me on what errors I should be looking for? In my Windows event viewer, I see the error was APPCRASH for dwm.exe

**Comment by MrPlusGH** [comment]
If you're using OC, try with stock settings.
If now issue then fine tune your OC.

**Comment by joeyoon80** [comment]
I do use MSI afterburner, but only to tune the fan settings. I dont OC at all.

**Comment by joeyoon80** [comment]
should I try with removing my MSI afterburner?
