### ISSUE TITLE
No Miners! Powershell errors.

### ISSUE THREAD

**Issue by firrae** [nemosminer/NemosMiner#683]
This seems to be potentially the same issue as #533 but that doesn't seem to have ever been resolved. On first starting the script everything starts up, I go through the config and add my settings and then, after adding itself to Windows Defender I get the following log:
[miner.log](https://github.com/nemosminer/NemosMiner/files/2171012/miner.log)

Any help with this would be appreciated.

**Comment by firrae** [comment]
To clarify my steps to do this:

- Download latest release
- Modify config files to meet my settings
- Run the bat file to get the GUI
- Press start on GUI

**Comment by firrae** [comment]
Hm, interesting. I just tried following your config verbatium and it works. Seems like if you manually modify the config files it skips the miner download steps? Is this intended?

**Comment by nemosminer** [comment]
Run NemosMiner-v3.3.bat
  1. Config tab
  2. Set your Wallet address and Username
  3. Select your pool 
  4. Save Config
  5. Start
  
  note: 2. you only need to change Username if you are using Miningpoolhub

if there is a initial "no miners error" just close and re run
