### ISSUE TITLE
Failed Miner..

### ISSUE THREAD

**Issue by Merckle** [nemosminer/NemosMiner#684]
Tried runing Realease 3.2 and also 3.3
Almost every miner will fail when running. 3.2 will run for a bit then stop. 
I have latest drivers with Nvidia, Running 7 1080tis No over clock

Firewall turned off and Windows Defender turned off and UAC Disabled

Any suggestions on what I am apparently doing wrong?

I alos checked the logs but doesnt state why miner failed that I could see

**Alos running sniffdog miner I run into no issues.

**Comment by firrae** [comment]
@Merckle can you tell me what algo it's trying? I finally pared down my list a bit and now, after removing all x16(s), and yes(s) it's back to working again I think?

**Comment by Merckle** [comment]
@firrae Here is the Core.log File - https://pastebin.com/1J9BPheL

But right now its failing on "hsr" but seems to fail on several other algos.

Algos that finished benchmarking: "X16R, PHI2, KeccakC, Skunk, Keccak"

**Comment by firrae** [comment]
PHI also failed for me, as well as Neoscrypt now.

**Comment by Merckle** [comment]
@firrae I want to say I have 9.2 drivers already installed

**Comment by firrae** [comment]
@Merckle I thought I did as well, but when I installed the patch on the CUDA downloads page the few that I tried that wasn't working now are. We'll know eventually if it gets through all of them though.

**Comment by nemosminer** [comment]
If you have Windows 7, 8, or 8.1, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=54616

CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

running multiple cards its recommended to increase Virtual Memory 64gb is optimal

Requires Nvidia driver 397.44 or newer

Made For & Tested with 8x10603gb 6x1070 6x1070ti 6x1080ti (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards
