### ISSUE TITLE
Bench issue

### ISSUE THREAD

**Issue by RickillerZ** [nemosminer/NemosMiner#685]
in new version, bench not working for ennemy and cryptodredge.

**Comment by KitFisto78** [comment]
Here is my fix for cryptodredge:
Notice that the first port in arguments, and the port at the bottom have been changed to "4444"

if (!(IsLoaded(".\Include.ps1"))) {. .\Include.ps1;RegisterLoaded(".\Include.ps1")}

$Path = ".\Bin\NVIDIA-CryptoDredge\CryptoDredge.exe"
$Uri = "https://github.com/technobyl/CryptoDredge/releases/download/v0.6.0/CryptoDredge_0.6.0.zip"

$Commands = [PSCustomObject]@{
    "allium" = "" #Allium
    "lyra2v2" = "" #Lyra2RE2
    "lyra2z" = " --submit-stale" #Lyra2z
    "neoscrypt" = "" #NeoScrypt
   # "phi" = "" #Phi
    "phi2" = "" #Phi2
    #"skein" = "" #Skein
    #"skunk" = "" #Skunk
}

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = " **-b 127.0.0.1:4444** -d $($Config.SelGPUCC) -a $_ --no-watchdog -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_) -R 1 -q -N 1"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week * .99} # substract 1% devfee
        API = "cryptodredge"
        **Port = "4444"**
        Wrap = $false
        URI = $Uri
        User = $Pools.(Get-Algorithm($_)).User
    }
}

**Comment by Merckle** [comment]
Did that fix the cryptobridge issue @KitFisto78 ? My cryptobridge is just steady using cryptobridge on skunk even though it isnt finished benchmarks. Seems like its not saving the stats for bench

**Comment by RickillerZ** [comment]
not fixed,  stats not saving , i manually add stat in folder but  not updated.

**Comment by RickillerZ** [comment]
@KitFisto78 thanks, work for CryptoDredge!

**Comment by Merckle** [comment]
Same port @RickillerZ for enemy? the 4444

**Comment by RickillerZ** [comment]
@Merckle , i use port 4445, work perfect.

**Comment by Merckle** [comment]
My only issue is that it's not saving stats. Do you use 0.0.0.0:4445" or "
127.0.0.1:4445"

And is that saving and switching
