### ISSUE TITLE
Error every cycle (non critical) but noticed in logs

### ISSUE THREAD

**Issue by thebeerbaron2018** [nemosminer/NemosMiner#691]
```
You cannot call a method on a null-valued expression.
At C:\Users\miner\Desktop\NemosMiner-masterrun\Core.ps1:497 char:41
+     $Variables.BrainJobs.ChildJobs | % {$_.Output.Clear()}
+                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Seems to be related to the $_.Output.Clear() command

**Comment by MrPlusGH** [comment]
Could you confirm you are not using any Plus version of any pool?
I'm guessing that is the case.

You're right, this is nothing critical. It will be fixed in next NPlusMiner version.

Thank you

**Comment by MrPlusGH** [comment]
It if fixed on NPlusMiner Master branch.
Even if i do not recommend downloads from master but wait for the next autoupdate.

**Comment by thebeerbaron2018** [comment]
Yep, sorry, should have said just zerg and nicehash (no plus) - glad it's sorted!

**Comment by MrPlusGH** [comment]
#693
