### ISSUE TITLE
Error in Bminer

### ISSUE THREAD

**Issue by A120970n** [nemosminer/NemosMiner#692]
Correct the error in calculating the speed of Bminer. Instead of 860 sol, gives 86 ksol.

**Comment by MrPlusGH** [comment]
How is you're OS configured?
Are you using "," or "." for decimal separator?

**Comment by A120970n** [comment]
Probably I incorrectly explained: in the Bminer window speed is shown normally, and Nemos shows the overestimated speed. Probably the problem is the divisor.

**Comment by MrPlusGH** [comment]
Bminer is the only one using the Wrapper. The Wrapper interprets comma as a thousands separator if you're OS is not set to US.
This is a known issue that still needs to be fixed in the Wrapper.

If you do not want to change your OS settings. Delete BMiner.ps1 and use EWBF.

**Comment by A120970n** [comment]
Changed the OS separator to a point , but the result remains the same: the speed in the miner is normal, and in Nemos the speed is overstated by 100 times, ie should be 1.5 kSol and produces 150 kSol.

**Comment by nemosminer** [comment]
should be sorted testing now
