### ISSUE TITLE
BTC/GH/Day Reporting Incorrectly from Pools

### ISSUE THREAD

**Issue by liquidone** [nemosminer/NemosMiner#695]
I am rebenching a rig using the latest master and it looks like there is an issue with the BTC/GH/Day reporting.  It would be nice if I was making $9,609.55 with Lyra2RE2 a day on this rig but somehow I don't think it is true :)

![rebench 3 3 nemo issue](https://user-images.githubusercontent.com/35848125/42413603-ff66c37a-81e0-11e8-9b27-c20b7727b56b.jpg)

**Comment by nemosminer** [comment]
thanks fixed

**Comment by RickillerZ** [comment]
same problem for me Lastest master: 
![nemo](https://user-images.githubusercontent.com/40898884/42666132-30cbf104-8611-11e8-95ea-6a1bc43f819e.jpg)
How resolve this? trying to set my system in us but same issue for me..
