### ISSUE TITLE
Script continuously re-downloads miner

### ISSUE THREAD

**Issue by thebeerbaron2018** [nemosminer/NemosMiner#697]
KlausT is a good example - the script tries to delete the miner from the bin folder but fails to delete VCRUNTIME140.DLL and then when the miner is re-downloaded it fails and then loops - downloading again and again.  Core.ps1: 234 Character: 57  {Remove-Item -Recurse (Split-Path $NewMiner.Path)}
Is the error line.

**Comment by thebeerbaron2018** [comment]
Again - screenshot from bitcointalk thread to assist.

![screenshot_2018-07-08_13-58-14](https://user-images.githubusercontent.com/36641730/42420001-0dfc4b54-82b7-11e8-94ef-c7830d9fd10b.png)

**Comment by thebeerbaron2018** [comment]
To reproduce - run the miner - and while running, edit the klausT ps.1 miner file and save... then wait for the next interval.

**Comment by MrPlusGH** [comment]
This should fix itself next time it switches miner.

This is the way miners updates are dealt with. Unfortunately we cannot update the miner binaries while its working. So we keep it working and it will update once it has finished working. (cycle after that)

Will work on getting rid of the error in logs wich shouldn't be there anyway as it is unrelevant.

**Comment by thebeerbaron2018** [comment]
Not so much.  For example even if KlausT isn't running - modify the PS1 file and let the interval pass - you'll see it tries to delete the KlausT bin folder but fails to delete the DLL even though it's not in use (and never has been since no miner has been started first fun).  It deletes everything else in the folder however!  This causes the loop of "downloading KlausT...downloading KlausT...downloading KlausT..." etc

**Comment by MrPlusGH** [comment]
Thanks! I'll check.
Don't see any reason why this DLL would be locked.

**Comment by thebeerbaron2018** [comment]
Yeah the screenshot is from the guy on bitcointalk - not mine - but the same issue is present there - its a permission denied on the remove-item method of the dll - again - when I am at the rigs - I'll do the klausT loop for you and upload the screenshot and exact error message.

**Comment by thebeerbaron2018** [comment]
Maybe this will help?  
![screenshot_2018-07-08_18-37-56](https://user-images.githubusercontent.com/36641730/42422453-1cbbf320-82de-11e8-9f04-58189f6c64f0.png)

**Comment by thebeerbaron2018** [comment]
adding "-force" to lines 701,702 in include.ps1 and line 201 in core.ps1 definitely solves this one!

**Comment by MrPlusGH** [comment]
Thanks!
Will fix in next NPlusMiner version

**Comment by nemosminer** [comment]
added -force 701,702 in include.ps1

checking 201 in core.ps1 = # Use location as preference and not the only one ?

**Comment by thebeerbaron2018** [comment]
My bad, got confused with the first one... it's line 234 in core.ps1

**Comment by nemosminer** [comment]
done thankyou
