### ISSUE TITLE
Miner request: PhoenixMiner

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#698]
PhoenixMiner is 1-2% faster than Claymore in my case, and has 0,35% lower devfee. This can make a difference.

Can you add this as an optional miner?

[PhoenixMiner 3.0c: fastest Ethereum/Ethash miner with lowest devfee (Windows)](https://bitcointalk.org/index.php?topic=2647654.0)

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/tree/EthashPhoenix

testing

**Comment by nemosminer** [comment]
done
