### ISSUE TITLE
miner t-rex 

### ISSUE THREAD

**Issue by RickillerZ** [nemosminer/NemosMiner#699]
now availlable in windows . very fast lyra2z but 1% dev fee.

https://bitcointalk.org/index.php?topic=4432704.0;all

**Comment by cfmarque** [comment]
as of version 0.4c, it doesn't have an API, but devs indicate that it's coming soon

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/704

**Comment by nemosminer** [comment]
sure

**Comment by jjziets** [comment]
how does ethcontroller manage to monitor the miner then?

**Comment by nemosminer** [comment]
i'll add it today

**Comment by RickillerZ** [comment]
Good! Thanks! Merci!

**Comment by nemosminer** [comment]
i can't even get it to run in windows,,, it just closes instantly...

you can download and try yourself 

url:  http://nemos.dx.am/opt/nemos/t-rex-0.4c-win-cuda9.1.7z

.bat file t-rex -a lyra2z -o stratum+tcp://lyra2z.mine.zergpool.com:4553 -u 1QGADhdMRpp9Pk5u5zG1TrHKRrdK5R81TE -p c=BTC -i 17

**Comment by nemosminer** [comment]
if you have this running on windows please share your .bat file

**Comment by RickillerZ** [comment]
My .cmd file : Work

@echo off
:start

t-rex -a lyra2z -o stratum+tcp://lyra2z.mine.zergpool.com:4553 -u 17FL8yH3eJxQbAgEVyWVEfpM3QoixR4PTn -p RigTest,c=BTC

goto start

**Comment by nemosminer** [comment]
thanks i have it working now no API is a problem tho ,  trying to run it through wrapper like Bminer and Phoninex but im not getting any output in the wrapper just blank

**Comment by RickillerZ** [comment]
Ok,  waiting for API, im not sure if dev working on api now.

**Comment by RickillerZ** [comment]
Api released ! @nemosminer https://github.com/technobyl/CryptoDredge/releases

**Comment by RickillerZ** [comment]
@nemosminer 
my ps1 file  working with t-rex:

. .\Include.ps1

$Path = ".\Bin\NVIDIA-t-rex\t-rex.exe"
 $Uri = "ftp://radio.r41.ru/t-rex-0.5.0-win-cuda9.1.zip"

$Commands = [PSCustomObject]@{
    "hsr" = "" #Hsr(Testing)
    "phi2" = "" #Phi2(Testing)
    "lyra2z" = "" #Lyra2z(Testing)
    "tribus" = "" #Tribus(Testing)
    "c11" = "" #C11(Testing)
    "x17" = "" #X17(Testing)
   
}

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = "-a $_ -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week * .99} # substract 1% devfee
        API = "Ccminer"
        Port = 4068
        Wrap = $false
        URI = $Uri
        User = $Pools.(Get-Algorithm($_)).User
    }
}
