### ISSUE TITLE
Comma in password breaks bminer.exe

### ISSUE THREAD

**Issue by GuyTechie** [nemosminer/NemosMiner#709]
Bminer is "broken".

Currently Nemosminer is using this syntax:
Bin\NVIDIA-Bminer\bminer.exe  -api 127.0.0.1:1880 -nofee -uri stratum://walletaddress.workername,c=BTC@equihash.mine.zpool.ca:2142 -devices 0,1

That comma is breaking bminer.exe

Not sure how it can be fixed since the full password should have a comma. "workername,c=BTC"

Omitting the workername will work in a pinch.

Bin\NVIDIA-Bminer\bminer.exe  -api 127.0.0.1:1880 -nofee -uri stratum://walletaddress.c=BTC@equihash.mine.zpool.ca:2142 -devices 0,1

**Comment by nemosminer** [comment]
bminer works great...

**Comment by MrPlusGH** [comment]
Note that the version on Master works.
Not the one in 3.2 release.
@nemosminer, pushing a pool request to simplify Bminer.ps1
