### ISSUE TITLE
Cannot convert value "GB" to type "System.Decimal"

### ISSUE THREAD

**Issue by duub** [nemosminer/NemosMiner#713]
Using the _Phoenix Miner 3.0c Windows/msvc_ and NM 3.3 I get this error:
```
Cannot convert value "GB" to type "System.Decimal". Error: "Input string was not in a correct format."
At C:\Users\mekanow\Downloads\NemosMiner-master3.3\Wrapper.ps1:35 char:13
+             $HashRate = [Decimal]$Words[$Words.IndexOf(($Words -like  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDecimal
```

**Comment by nemosminer** [comment]
i don't... get that error

**Comment by duub** [comment]
What about this:
It's a thing related to NemosMiner?
```
CUDA error in CudaProgram.cu:377 : out of memory (2)
[here comes the log pasted in the first message]
GPU1: CUDA memory: 11.00 GB total, 9.09 GB free
GPU1 initMiner error: out of memory
```

**Comment by nemosminer** [comment]
read the readme...

**Comment by nemosminer** [comment]
If you have Windows 7, 8, or 8.1, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=54616

CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

running multiple cards its recommended to increase Virtual Memory 64gb is optimal

Requires Nvidia driver 397.44 or newer

Made For & Tested with 8x10603gb 6x1070 6x1070ti 6x1080ti (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards

**Comment by duub** [comment]
I read optional instead of optimal...
