### ISSUE TITLE
ETHash Phoenix miner, bad report speed

### ISSUE THREAD

**Issue by cervajz1** [nemosminer/NemosMiner#714]
Hi, in new Nemosminer 3.3 is problem with bad reporting speed of new ETHash Phoenix miner 3.0c
Speed is right but there is problem with units -  Gigahash (GH/s) instead Megahash (MH/s).

Problem is in Stats and nemos GUI. Miner shows right units MH/s

**Comment by sky61** [comment]
Same problem for me too

**Comment by duub** [comment]
why is closed without any answer? I'm having the same problem

**Comment by nemosminer** [comment]
its not problem v3,3 is very well tested 

Nothing to Answer....

**Comment by nemosminer** [comment]
i installed and bench marked Latest Realase v.3.3
on 3 different new rigs this morning 
6x1070 6x1070ti 6x1080ti and all of them is recording the correct speed for Phoenix miner 3.0c

**Comment by cervajz1** [comment]
Hi, for those, who have same problem, - SOLVED. There is problem with decimal mark if you have other language then english (Czech in my situation)

Solution - You must change decimal mark (decimal point), from dash to point, in Control panels - region setting. 
![decimal](https://user-images.githubusercontent.com/35784176/42757344-f2d3cf4c-88ff-11e8-8930-ba8612433a2d.png)

I found, that similar problem was with bminer which using Wrapper, same as phoenix miner.

**Comment by duub** [comment]
Thanks @cervajz1 worked for me (after deleting the corresponding file in the stats folder)
