### ISSUE TITLE
Not work the GPU separation

### ISSUE THREAD

**Issue by spr32** [nemosminer/NemosMiner#715]
Hi!

I use NemosMiner 3.3. I adjust config.json, but the program overwrites it to all cards.
For example, it does not work:

"GPUCount":  6,

"SelGPUCC":  "2,3",
"SelGPUDSTM":  "2 3",

Thanks.

**Comment by MrPlusGH** [comment]
set manualconfig to true in config.json
Once done, everything needs to be done manually.

**Comment by spr32** [comment]
It does not work either.

**Comment by MrPlusGH** [comment]
https://github.com/MrPlusGH/NPlusMiner/issues/102

**Comment by MrPlusGH** [comment]
Fixed in NPlusMiner on master: https://github.com/MrPlusGH/NPlusMiner/archive/master.zip
