### ISSUE TITLE
More equihash144 coins in Zergpool.com

### ISSUE THREAD

**Issue by pinpins** [nemosminer/NemosMiner#716]
Hello,

Not really an issue, but wanted to discuss doable option to bring more coins, which have personalization string in command line of miner.

Currently Snowgem(XSG) has  --pers sngemPoW if I would add BitcoinZ (BTCZ), it would have --pers BitcoinZ.

Apparently if top profitable coin in equihash144 would be changed, miners would need to re run their miner with new personalization.

Two options in my mind currently to potentially solve it :
1. Make equihash144 ports per one coin only. 
2. Provide top coin in API/Status, so Nemos could re-run miner with appropriate personalization

Do you have any other ideas?
Thank you

pinpin

**Comment by RainbowMiner** [comment]
Hi pinpin,

I would appreciate very much, if you always would send the most profitable coin along with it's algo through the API. with that, the benchmark has only be run once for the underlying main algorithm and the EWBF can be switched nicely to the other personalization. I already implemented this coin selection in my miner to detect for more coins.

Rbm

**Comment by pinpins** [comment]
Hi,

Ok, do you think something like this would be ok? 

{"name":"equihash144","port":2146,"coins":1,"fees":0.5,"hashrate":786,"workers":14,"estimate_current":"0.00370156","estimate_last24h":"0.00346925","actual_last24h":"1.71098","mbtc_mh_factor":0.001,"hashrate_last24h":872.8737**,"bestcoin":"XSG"**}

Don't implement yet, lets mutually confirm first.
pinpin

**Comment by RainbowMiner** [comment]
Hi,

yes, that would be wonderful. On top of that, if you add the name of the coin, too, it is a perfect solution. 

Regarding your question: yes, either skip the parameter or set it anyway. It is interesting and leaves all options on the table, for future uses. In my RainbowMiner script, I always try to show, which coin is currently "on", just for information purposes.

For miners w/o profit switch, you might be right - on the other hand, those are mostly miner who know what they are doing. So I would anticipate, that it would do no harm.

It is already implemented at RainbowMiner, because of Equihash144 and Bitcoin Gold. It switches seamless between Eqh144 - BitcoinGold and Eqh144 - Snowgem.

Rbm

**Comment by MrPlusGH** [comment]
Let me think a bit more about it and i'll get back to guys.
@pinpins, thanks for the collaborative thinking offer ;)

**Comment by MrPlusGH** [comment]
Might not be that easy but if we were to implement some logic around option 3. I think it should do the trick.
ie: c=BTC,mc=Coin

1. Build some specific pool file (like ZergPoolCoins)
2. Get pool algo stats
3. Get pool coins stats
4. Generate pools for each coin (pass will be different "mc=" so each coin will be seen a different miner command)
5. Implement logic to change command line based on 'mc=' in miner file (Simple switch)
6. The current code should pick the coin with the highest price without requiring any change.

So for us that would be two things:
- addition of a specific pool
- modification of EWBFv2.ps1

For Pinpins: No change
 - @pinpins,
    - Note that is doesn't solve the issue for miners w/o profit switch
    - This will double API calls on each cycle

Thinking about it, we don't even need a specific pool file but can implement the logic in current Zergpool pool files. Like if equihash144 use option3.
It will make ZergPool different from others but I think this is manageable.

Thoughts?

**Comment by MrPlusGH** [comment]
Is "24h_btc" the actual in currencies API?

**Comment by MrPlusGH** [comment]
Got a draft here: https://github.com/MrPlusGH/NPlusMiner/blob/BrainPlusTopCoin/Pools/ZergPoolPlusTopCoin.ps1

This takes BrainPlus calculations for ZergPool and find the best coin for the best algo.
The pass is then set with mc=COIN and add coin and symbol properties to the pool

Currently testing on one rig.
Note that this applies to all algo.

We should then be able to map pool properties in the EWBFv2 miner file to inject the proper command switches...

Comments welcome.

**Comment by pinpins** [comment]
Problem is that I don't have mc= yet supported for equihash. But that would make a trick for good switch over between miner and --pers.

It would also force me to speed up with mc= implementation for equihash.. :)

And it does not solve problem for miners w/o profit switch - yes, but we could say Option 1 is not supported. Only Option 2 and Option 3. If you want profit switch use NemosMiner. 

Let me give it a bit more thought

**Comment by MrPlusGH** [comment]
Yeah.
I'm also afraid that this type of logic might make the switching rate really high as coins are moving fast and that might be totally counter productive....

**Comment by MrPlusGH** [comment]
We actually don't have to use mc= for equihash144. Has i'm adding coin to the pool properties, this will be enough to determine --pers.
So no big deal that mc is not implemented there.
When not implemented, how do you deal with cases when it is passed? are you ignoring it or it breaks?

**Comment by nemosminer** [comment]
testing option 3 with zerg atm 
can these be implemented into 24hour and normal also

**Comment by MrPlusGH** [comment]
Theoretically yes. This is a very early version.
Just need to test and validate
 - That it causes no issues
 - That it brings value (earnings) - not sure on this one
    - @nemosminer, Could you run side by side testing?
 - That the switching rate is reasonable
 - Performance are bad right now and need to be improved

**Comment by nemosminer** [comment]
yes i'll test with 6x 1070ti rig side by 3 cards each,

zergpoolplus vs zerpoolplustopcoins

**Comment by MrPlusGH** [comment]
Please report results here: https://github.com/MrPlusGH/NPlusMiner/issues/104

**Comment by nemosminer** [comment]
sure 

test will start within next 30 mins will leave running for 24-48hour or longer if needed...

you can monitor process here:

**Comment by MrPlusGH** [comment]
Madecode changes in ZergPoolPlusTopCoin.ps1 to improve pool polling performances

**Comment by nemosminer** [comment]
ok im ready to start i'll add improved polling performance then start test you can monitor balances here:

zergpoolplus : http://zergpool.com/?address=17H7wRfPFBVyoZ3NzeXuuwKVcxddx9bpFe

zerpoolpluscoins: http://zergpool.com/?address=1GVMpten2zvqMDgWa2fF1QFkixTqbhUoG7

**Comment by pinpins** [comment]
Guys, thanks. I was just over helmed with other pool issue. So had little no time to respond. Let's slow it down/ park for little while

**Comment by MrPlusGH** [comment]
@pinpin, any reason why c=BTC,mc=XSH results in stratum connection errors while miners not specifying mc= works ok mining XSH?

```
*** ccminer alexis-1.2 for nVidia GPUs from alexis78@github ***
*** ccminer alexis-1.2 compiled by nemosminer@github ***
*** Built with VC++ 2013 and nVidia CUDA SDK 7.5 (Recommended)

*** Based on tpruvot@github ccminer
*** Originally based on Christian Buchner and Christian H. project
*** Include some of the work of djm34, sp, tsiv and klausT.
                        Alexis78-v1.2

[2018-07-18 17:01:08] Starting on stratum+tcp://x17.mine.zergpool.com:3737
[2018-07-18 17:01:08] NVAPI GPU monitoring enabled.
[2018-07-18 17:01:08] 2 miner threads started, using 'x17' algorithm.
[2018-07-18 17:06:09] Stratum connection interrupted
```

**Comment by MrPlusGH** [comment]
@nemosminer, they are mainly mining HSR which has only one coin so not sure the test is meaningful so far.

**Comment by nemosminer** [comment]
correct HSR has been most profirable last 9 hours...

do you want me to only enable Algos with multiple coins ?

**Comment by MrPlusGH** [comment]
Might make sense for the specific test.

**Comment by nemosminer** [comment]
test will restart in 30 mins only algos with 3 or more coins selected will update monitoring wallets once started

**Comment by nemosminer** [comment]
test started

**Comment by nemosminer** [comment]
no new updated : 

zergpoolplus : http://zergpool.com/?address=1Ag57ZpQSTr5BfcKGBtTKGrbihSHZY4vKh

zerpoolpluscoins: http://zergpool.com/?address=1PAF3Su4C9RhQYdo8wzH8ENVTcEwdEiF7i

**Comment by nemosminer** [comment]
Test restarted due to different Variables 

This should be a True test

new addresses

zergpoolplus : http://zergpool.com/?address=14rXrtks1c44az91FwDq6kuhM9U5WJqwj8

zerpoolpluscoins: http://zergpool.com/?address=1KqHHPLFsVZbPvDgP6CvcJ9uXiQoKL8iYj

**Comment by pinpins** [comment]
Hello,

Basically, in order to keep flexibility for regular miner w/o profit switch software, I will not be able to lock multiple coin under one port and algo, if they have different personalization

So seems adding algorithm for each personalized coin is the best way to go, it would allow profit switch through benchmark, as well as would keep standalone miners working well.

Equihash
EquihashZER
EquihashXSG
EquihashBTCZ

The only downside a bit messy look at main page of zergpool having potentially many Equihash coin specific stratum ports :/

PS:
The best coin in API would partially solve problem for profit switch, though would provide somedelay and false mining, as API is updated with some delay, and miner also fetching values periodically, leaving some period of time with mining against wrong coin leading to not accepted shares...

Let me know if any other perhaps good ideas you have

**Comment by nemosminer** [comment]
Equihash
EquihashZER
EquihashXSG
EquihashBTCZ

quick and easy will work perfect for now... we can always review and come up with a different/better solution if your home page starts looking to messy.. 

Best Regards
Nemo

**Comment by MrPlusGH** [comment]
May be one suggestion: Can we get some sort of naming convention like equihash144-ZER.
This might enable us to code things to deal with the suffix so users only have to select equihash144 and not all coins. From a users perspective it might make things simpler and they won't have to track additions of coins or change their config when new coins are added.

Also, this is gonna bring a lot more switching. The current test Nemo is running for ZergPoolPlusTopCoin, do not show a great impact so far due to switching. Seems like the pool does a better job than the client software due to miner warm up time.

Anyway, i agree this is a good interim solution untill we find a better approach.

MrPlus

**Comment by pinpins** [comment]
Regarding naming convention, so it works well in yiimp also.

I will make it as following:
equihash144btcz
equihash144zel

For XSG and ZER both DNS names are supported as interim
equihash192 and equihash192zer
equihash144 and equihash144xsg

However algos in API still named old way.  Need to find right time to change them also.

**Comment by nemosminer** [comment]
@pinpins   http://api.zergpool.com:8080/api/status 

there is no equihash144btz ?

**Comment by pinpins** [comment]
@nemosminer  it was in test mode to see we find blocks, found 2, so enabling in API

**Comment by pinpins** [comment]
@nemosminer , let me know if I should open new request instead.

I am excided to annoucne that we managed to get personalized equihash coins profit switch without EWBF miner restart, as well as adding mc= functionality to equihash stratums.
Credits to EWBF developer supporting the change. We will group all Equihash 144 5 coins under one port equihash144.mine.zergpool.com:2146 making all Options(1,2,3) functionallity working with latest EWBF release 0.5.

More details
https://goo.gl/hejB5f
