### ISSUE TITLE
PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression." in logs

### ISSUE THREAD

**Issue by NorbertColon** [nemosminer/NemosMiner#717]
_Nemos 3.3, Windows 10, recent Windows updates installed, GTX1080
Log sample:_

> Last Refresh: 07/16/2018 09:26:24
> Sleeping 300
> Starting Cycle
> Loading BTC rate from 'api.coinbase.com'..
> Loading pool stats..
> Computing pool stats..
> Loading miners..
> Comparing miners and pools..
> PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
> PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
> closing current miner and switching
> Starting miner

**Comment by MrPlusGH** [comment]
This is a non blocking error that we need to fix.
You can ignore it for now.
We'll work on it.

@MrPlus

**Comment by MrPlusGH** [comment]
Fixed in NPlusMiner Master.
Would be great if you could test and report.
