### ISSUE TITLE
Manually set GPUs to use

### ISSUE THREAD

**Issue by jimmykl** [nemosminer/NemosMiner#719]
I have a rig where I only want to use two cards with Nemos. 

With 3.2 I used to use the GUI for most of the config then manually change config.json file to:
```    
"SelGPUCC":  "6,7",
"SelGPUDSTM":  "6 7",
```
But with 3.3 it seems to automatically change it back to
```    
"SelGPUCC":  "0,1",
"SelGPUDSTM":  "0 1",
```
whenever Nemos runs. Is there a way to stop that happening?

**Comment by MrPlusGH** [comment]
https://github.com/MrPlusGH/NPlusMiner/issues/102

**Comment by jimmykl** [comment]
Cool thanks @MrPlusGH closing this dupe
