### ISSUE TITLE
Adding T-rex miner

### ISSUE THREAD

**Issue by RickillerZ** [nemosminer/NemosMiner#721]
I upload new t-rex miner: ftp://radio.r41.ru/incoming/t-rex-0.5.1-win-cuda9.1.zip
Temp directory.
Work Very good after 8hours test on HSR  +2mh/s vs Alexis78 (1070ti)

My ps1 file.

. .\Include.ps1

$Path = ".\Bin\NVIDIA-t-rex\t-rex.exe"
  $Uri = "ftp://radio.r41.ru/incoming/t-rex-0.5.1-win-cuda9.1.zip"

$Commands = [PSCustomObject]@{
    "hsr" = "" #Hsr(Testing)
    "phi2" = "" #Phi2(Testing)
    "lyra2z" = "" #Lyra2z(Testing)
    "tribus" = "" #Tribus(Testing)
    "c11" = "" #C11(Testing)
    "x17" = "" #X17(Testing)
   
}

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = " -b 0.0.0.0:4028 -a $_ -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week * .99} # substract 1% devfee}
        API = "Ccminer"
        Port = 4028
        Wrap = $false
        URI = $Uri
        User = $Pools.(Get-Algorithm($_)).User
    }
}

**Comment by nemosminer** [comment]
testing atm

**Comment by nemosminer** [comment]
have other test going on atm will test sometime today tho initial test i don't think its working may need some work still

**Comment by gilby77** [comment]
Trex not working at blazepool? Failed run benchmark algos hsr,x17...

**Comment by papacheal** [comment]
Miner config file requires IP added to -b parameter in Arguments section.

i.e. -b $($Variables.NVIDIAMinerAPITCPPort)
-> -b 0.0.0.0:$($Variables.NVIDIAMinerAPITCPPort)

**Comment by nemosminer** [comment]
sorted working now
