### ISSUE TITLE
All algos for pool not loaded when clicking "Load default algos..."

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#733]
I have noticed that not all algos are loaded when clicking "Load default algos..."

I had zergpoolplus selected, clicked on "Load default algos..." and saw that the equihash algos, balloon and possibly more were not loaded.

Is it by design that only a select number of algos are loaded? Even if they pool does support them?

**Comment by nemosminer** [comment]
yes i need to update default algos

**Comment by scavern** [comment]
What about having an option to load all algos? That way if a pool starts using an algo nemosminer will be able to use it straight away?

**Comment by nemosminer** [comment]
i have all algos enabled by default... i just need to update default algos.json i'll try get that done 2moro

**Comment by MrPlusGH** [comment]
Next version of NPlusMiner will mine all algos available on selected pools if algo list is left blank.
This will basically make the algo list dynamic based on what the pools are proposing.
I'm thinking of making this the default configuration.

Available in Master here: https://github.com/MrPlusGH/NPlusMiner
Just set the algo list to blank and save config.

Would be great if you could test and report ;)

**Comment by nemosminer** [comment]
testing

**Comment by nemosminer** [comment]
working well can properly remove Default Algos button and Algos.json from servers and then just leave algo list blank in conf.json

**Comment by MrPlusGH** [comment]
Lets think about it. We might wanna make it a prefered/best algo list.
I believe @tesla74 did some work about it. let him chime in.
