### ISSUE TITLE
if miners = 0 skip

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner#734]
Hello!
I have got a bug with brainplus on zergpool.
![2018-07-23_11-34-03](https://user-images.githubusercontent.com/31293967/43110692-22e541e2-8ef6-11e8-8d12-76e6a6b6dc6f.png)
![2018-07-23_11-34-56](https://user-images.githubusercontent.com/31293967/43110696-25ce2f40-8ef6-11e8-949f-68f1b903740b.png)
I think the reason is that the balloon algo does not have miners (pool bug, or no jobs), but for some reason the pool is reported a certain "Current estimate"...
Maybe you can make some fix for it?

**Comment by Olegik-ah** [comment]
For example:
if "Number of miners"=0 then
$AlgoData.($Name).actual_last24h = 0
else
$AlgoData.($Name).actual_last24h = $Price
end if

Sorry, i dont know PS syntax...

**Comment by nemosminer** [comment]
yeh i noticed the same while benchmark balloon must be down atm because i can't seem to connect to or neither can any one else by the looks, it would make since if miner = 0 skip that algo,,,

**Comment by MrPlusGH** [comment]
Sounds more like a pool issue to me.
We use the estimations reported by the pool which is this case has an availability issue.

**Comment by nemosminer** [comment]
balloon working now

**Comment by Olegik-ah** [comment]
Yes, sounds like pool bug... But i think it will be great, if you will make something like this to prevent stop mining...
if miners = 0 & price!=0 skip
