### ISSUE TITLE
bitcoin-gold at miningpoolhub?

### ISSUE THREAD

**Issue by Moskga** [nemosminer/NemosMiner#735]
miningpool hub added bitcoin-gold at AUTO SWITCHING PORTS PER ALGO.
in the statistics of api bitcoin-gold:

https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics

add in ewfbv2.ps1
"
"equihash-btg" = "--cuda_devices $ ($ Config.SelGPUDSTM) --algo 144_5 --pers BgoldPoW" # Equihash-btg
"

add in algoritm.txt
"
"equihash-btg": "equihash-btg",
"
but not working

**Comment by nemosminer** [comment]
working now..
