### ISSUE TITLE
Disable/enable algorithms per pool

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#736]
It would be great if one can select which algorithms mine to which pool. 

I use zergpool and nicehash and the actual income for some of the algorithms are very bad compared to estimated. I have a theory about this but regardless I would like to not mine lyra2z, neoscrypt and lyra2rev2 on zergpool but would like to switch to nicehash when they do good there.

**Comment by nemosminer** [comment]
use 24hour for zerg...

**Comment by jjziets** [comment]
Is that a recommendation? Not to use Plus?

**Comment by jjziets** [comment]
which is best to use? zergpool24hr or zergpoolplus? I see that coins such as lyra2z, neoscrypt and lyra2v2 Actual are horrible compared to estimates.
so I'm worried that I might mine it when using plus.
but then again I don't want to mine for 24h when an algo tanks
I was hoping plus would work around that.
