### ISSUE TITLE
EquihashBTG?

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#737]
I am not getting EquihashBTG to work. 

I have downloaded the master and got EquihashBTG in the config. but it is not benchmarking. Is it to early? 

This is with zergpoolplus

**Comment by MrPlusGH** [comment]
EquihashBTG in on MiningPoolHub
ZergPool has
   - equihash144btcz 
   - equihash144zel

**Comment by jjziets** [comment]
Ok. that explain it.
