### ISSUE TITLE
Start Child Jobs

### ISSUE THREAD

**Issue by triggerhaven** [nemosminer/NemosMiner#738]
Unable to get the latest version started.
![image](https://user-images.githubusercontent.com/38239909/43165079-e6540176-8f47-11e8-928e-1437474066ab.png)

**Comment by triggerhaven** [comment]
Additionally I get this at start up 
![image](https://user-images.githubusercontent.com/38239909/43165313-70ed4752-8f48-11e8-98cd-2ba3ad24cea1.png)

**Comment by nemosminer** [comment]
thanks fixed
