### ISSUE TITLE
Eu support 

### ISSUE THREAD

**Issue by jjziets** [nemosminer/NemosMiner#740]
Nicehash has an eu server and now zpool 

#zpool We've launched a beta EU based stratum server located in Central Europe.  Please, if you are in EU give it a try.  stratum+tcp://<algo>.eu.mine.zpool.ca:<PORT>

Please fix the location problem with nemosminer. Don't want to mine to JP on nicehash when I use eu.

**Comment by nemosminer** [comment]
ok

**Comment by jjziets** [comment]
zpool eu 180ms
zpool usa 270ms

nicehash eu  178ms
nicehash usa  300ms
nicehash jp 400ms

**Comment by MrPlusGH** [comment]
in the meantime, use Europe instead of EU, that will work for NiceHash

**Comment by jjziets** [comment]
o, whish i knew that

**Comment by nemosminer** [comment]
ok

**Comment by jjziets** [comment]
@everyone Regional stratum servers enabled for North America (na) & Europe (eu) - example: stratum+tcp://scrypt.eu.mine.zpool.ca. If not region supplied then na servers are used as default.

**Comment by nemosminer** [comment]
ok
