### ISSUE TITLE
Issue with 5 x GTX1080Ti

### ISSUE THREAD

**Issue by Ericminer** [nemosminer/NemosMiner#742]
The Nemosminer will always (few hours) occur 2 types of error with 5 GTX1080Tis rig. However, the rig with 1 GTX 1080Ti is just fine.
### 1st Type is Just In Time error popout window, here is the log:
-------------------------------------------------------------------------------------------------------------------
如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.Management.Automation.CommandNotFoundException: 無法辨識 'out-file' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包含路徑的話，請確認路徑是否正確，然後再試一次。
   於 System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   於 <ScriptBlock><trap>(Closure , FunctionContext )
   於 System.Management.Automation.ExceptionHandlingOps.ProcessTraps(FunctionContext funcContext, RuntimeException rte)
   於 System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   於 <ScriptBlock>(Closure , FunctionContext )
   於 System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   於 System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   於 System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   於 System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   於 System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   於 System.Windows.Forms.Timer.OnTick(EventArgs e)
   於 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
-------------------------------------------------------------------------------------------------------------------
2nd Type of RED error message show in the NemosMiner windows, here is the log:
-------------------------------------------------------------------------------------------------------------------
IsLoaded : 無法辨識 'IsLoaded' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包含路
徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1319 字元:19
+             if (!(IsLoaded(".\Core.ps1"))) {. .\Core.ps1; RegisterLoa ...
+                   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (IsLoaded:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

IsLoaded : 無法辨識 'IsLoaded' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包含路
徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1320 字元:19
+             if (!(IsLoaded(".\Include.ps1"))) {. .\Include.ps1; Regis ...
+                   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (IsLoaded:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PrepareWriteConfig : 無法辨識 'PrepareWriteConfig' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字
是否正確，如果包含路徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1321 字元:13
+             PrepareWriteConfig
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PrepareWriteConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

在此物件上找不到屬性 'Text'。請確認該屬性存在並且可供設定。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1322 字元:13
+             $ButtonStart.Text = "Stop"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

InitApplication : 無法辨識 'InitApplication' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正
確，如果包含路徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1323 字元:13
+             InitApplication
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (InitApplication:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Split-Path : 無法辨識 'Split-Path' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包
含路徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1325 字元:58
+ ...       $Variables | add-Member -Force @{MainPath = (Split-Path $script ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Split-Path:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1327 字元:13
+             $CycleRunspace.Open()
+             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1328 字元:13
+             $CycleRunspace.SessionStateProxy.SetVariable('Config', $C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1329 字元:13
+             $CycleRunspace.SessionStateProxy.SetVariable('Variables', ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1330 字元:13
+             $CycleRunspace.SessionStateProxy.SetVariable('StatusText' ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Split-Path : 無法辨識 'Split-Path' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包
含路徑的話，請確認路徑是否正確，然後再試一次。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1331 字元:64
+ ... $CycleRunspace.SessionStateProxy.Path.SetLocation((Split-Path $script ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Split-Path:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

在此物件上找不到屬性 'Runspace'。請確認該屬性存在並且可供設定。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1333 字元:13
+             $powershell.Runspace = $CycleRunspace
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1334 字元:13
+             $powershell.AddScript( {
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1345 字元:13
+             $Variables | add-Member -Force @{CycleRunspaceHandle = $p ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

不可在值為 Null 的運算式上呼叫方法。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1347 字元:13
+             $TimerUI.Start()
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

在此物件上找不到屬性 'Visible'。請確認該屬性存在並且可供設定。
位於 C:\Users\Eric\Downloads\NemosMiner-master\NemosMiner-master\NemosMiner.ps1:1349 字元:13
+             $ButtonPause.Visible = $True
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
-------------------------------------------------------------------------------------------------------------------
Please check. Many thanks.

**Comment by nemosminer** [comment]
nope
