### ISSUE TITLE
miningpool hub you need to create you own username and worker name.. or remove miningpooolhub from selected pools list....

### ISSUE THREAD

**Issue by phenomeus** [nemosminer/NemosMiner#744]
hi

$($Pools.(Get-Algorithm($_)).User) this part is not working for example in CryptoDredge.ps1 to mine on MPH. the USER and WORKERNAME configured in the GUI is not inserted in the startup commands. 

thats why its not mining. if I hardcode my user and worker into the ps1 its working like a charme.

**Comment by nemosminer** [comment]
checking

**Comment by nemosminer** [comment]
checked working PERFECT!  https://imgur.com/a/H2kmIRb

YOU need to make an account with mining-pool hub and add a worker...

**Comment by nemosminer** [comment]
my settings are default... 

download and run nothing fancy....

**Comment by nemosminer** [comment]
this is my config i use

config: https://imgur.com/a/nKjNxgb

i change 3 things
 
donate = 3
Currency = NZD
pools  zerg24hr,nicehash,miningpoolhub

save
