### ISSUE TITLE
New PS error

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner#745]
Hello!

I think error related to:
https://github.com/nemosminer/NemosMiner/issues/732

I got it after update core, include and nemosminer from master.
But it is new error. Before update there was "TimerUITick" and "The property 'Lines' cannot be found on this object"
Now i have got error with "out-file" 2 times after update (less than 24h):

System.Management.Automation.CommandNotFoundException: Имя "out-file" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
   в System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   в <ScriptBlock><trap>(Closure , FunctionContext )
   в System.Management.Automation.ExceptionHandlingOps.ProcessTraps(FunctionContext funcContext, RuntimeException rte)
   в System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   в <ScriptBlock>(Closure , FunctionContext )
   в System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   в System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   в System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   в System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   в System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

And now in coreCycle.log many-many errors like this:
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:555 знак:41
+     $Variables.StatusText = "Sleeping $($Variables.TimeToSleep)"
+                                         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:125 знак:9
+         $Variables.StatusText = "Starting Cycle"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Stats Equihash144zel -> 23,00  H after 7592 sec
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:187 знак:9
+         $Variables.StatusText = "Loading BTC rate from 'api.coinbase. ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:195 знак:9
+         $Variables.StatusText = "Loading pool stats.."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:206 знак:9
+         $Variables.StatusText = "Computing pool stats.."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:238 знак:9
+         $Variables.StatusText = "Loading miners.."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
Исключение при задании "StatusText" : "Команда "Add-Member" найдена в модуле "Microsoft.PowerShell.Utility", но загрузит
ь этот модуль не удалось. Для получения дополнительных сведений выполните команду "Import-Module Microsoft.PowerShell.Ut
ility"."
C:\Users\olegik\Desktop\Miners\NemosMiner-v3.3\Core.ps1:281 знак:9
+         $Variables.StatusText = "Comparing miners and pools.."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ScriptSetValueRuntimeException
--------------------------------------------------------------------------------

**Comment by nemosminer** [comment]
nope not for me...
