### ISSUE TITLE
Incorrect earnings!

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner#746]
Hello!
Same error i got 4-5 times on 3 different rigs... Divisor is incorrect.
To fix it - i must delete all zegrpoolplus*.txt from stats and zergpoolplus.json from BrainPlus\zergpoolplus
![2018-07-30_16-25-58](https://user-images.githubusercontent.com/31293967/43400099-7082dd8c-9415-11e8-8902-fbcfd4b48ddf.png)

**Comment by nemosminer** [comment]
no

**Comment by Quake4** [comment]
try it https://github.com/Quake4/MindMiner
