### ISSUE TITLE
Xevan 9 Failure, TpruvotPHI failure

### ISSUE THREAD

**Issue by triggerhaven** [nemosminer/NemosMiner#747]
While doing benchmarks with this new version, I couldn't get through Xevan9 and TprovotPHI.  I removed xevan9 from miner list then it gave me issues with TpruvotPHI.  Both would start the miner then report errors like "could not throughput CPU" , so I had to go back to 3.3.

**Comment by nemosminer** [comment]
there is no Issiue with Xevan 9 there is no TpruvotPHI...

only Tpruvot2.2.5 and 2.3...
