### ISSUE TITLE
Xevan 9 Failure

### ISSUE THREAD

**Issue by not-idol** [nemosminer/NemosMiner#749]
Benchmarking on 3.4 failed to continue after this error.

![](https://cdn.discordapp.com/attachments/459089445531156481/473929194561208321/unknown.png)

![](https://cdn.discordapp.com/attachments/459089445531156481/473930206676254720/Capture.JPG)

**Comment by nemosminer** [comment]
fix your rig then then nothing wrong with NemosmIner or ccminer xevan cuda 9
