### ISSUE TITLE
Updated T-Rex 0.5.7 available

### ISSUE THREAD

**Issue by papacheal** [nemosminer/NemosMiner#751]
FYI. Another day, another T-Rex release:

T-Rex 0.5.7
Faster renesis, hsr, x16r, x16s, x17, c11. Few % improvement across all of them.

Linux
CUDA 9.1: 
https://mega.nz/#!LY9nnJrI!IcUKpZFibh26Sf67jZ37FQwKDobo_6TK-Tua3T0MhIM

CUDA 9.2:
https://mega.nz/#!yBklEZhK!BMVD_BVJiXbkr4sv_ZB5Jpfb1MF6ogHR_SedqgN7zi8

Windows (unstable, use with caution, some people reported issues causing miner restarts)
CUDA 9.1/9.2:
https://mega.nz/#!CAEF1KCJ!0G7jXCnaIKYFSaBIo5H7Il_kNncDG2VR-ZAPvcps658

FTP mirror:
ftp://radio.r41.ru/t-rex-0.5.7-win-cuda9.1.zip
ftp://radio.r41.ru/t-rex-0.5.7-linux-cuda9.1.zip
ftp://radio.r41.ru/t-rex-0.5.7-linux-cuda9.2.zip

**Comment by nemosminer** [comment]
thanks i'll update it today

**Comment by nemosminer** [comment]
done

**Comment by 88plug** [comment]
We have a mirror up for you!

https://cryptoandcoffee.com/ccminer/t-rex-0-5-7-linux-cuda9-2-zip/
