### ISSUE TITLE
Minemoney

### ISSUE THREAD

**Issue by Remie9** [nemosminer/NemosMiner#753]
Mine money is not coonecting to pool.

In Folder:
C:\Users\Jeremie\Downloads\NemosMiner-v3.3\NemosMiner-v3.3\Pools\
Changing:
$HostSuffix = ".MineMoney.co"
instead of $HostSuffix = ".MineMoney.ca"
to:
in files minemoney.ps1 and  minemoney24hr.ps1
should make things work correctly

**Comment by nemosminer** [comment]
thanks done
