### ISSUE TITLE
Continuous CryptoDredge benchmark loop

### ISSUE THREAD

**Issue by TGM8599** [nemosminer/NemosMiner#757]
CryptoDredge 0.8.2 in any compile variant ends up in a three-cycle benchmark loop for skein and lyra2z.

**Comment by nemosminer** [comment]
checking

**Comment by TGM8599** [comment]
This is strange, but it appears that the system is “forgetting” the benchmarks for certain algorithms for CryptoDredge only.  I have checked the box on Auto Update to see if this has any influence.

**Comment by nemosminer** [comment]
fixed was a issue with v0.8.2 

now running v0.8.3
