### ISSUE TITLE
Cryptonight-Monero @ MiningPoolHub

### ISSUE THREAD

**Issue by jigoku-shoujo** [nemosminer/NemosMiner#761]
I tried mining @ MPH after a while, but for the life of me I can't get CryptonightV7 to work.

Even when I chose it as the only algorithm, Nemos says that no miners exist. And I have xmrstak in the /Miners folder. I also tried adding "cryptonight-monero" and "cryptonightmonero" at the .ps1 file but it didn't work as well.

Any ideas?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/627
