### ISSUE TITLE
x16s algo - DelosMiner not included

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#763]
x16s algo commented out in many miner, referencing "delos faster", but it's not included.

`#"x16s" = " -i 20" #X16s(delos faster)`

[DelosMiner for nVidia GPUs by TeamDelos](https://bitcointalk.org/index.php?topic=4344544.0)

Right now, the only miner can miner x16s in NemosMiner is ccminerDumax.

**Comment by nemosminer** [comment]
enabled x16s in ccminerspmodgit7
