### ISSUE TITLE
Z-Enemy 1.17 released

### ISSUE THREAD

**Issue by papacheal** [nemosminer/NemosMiner#765]
Another day, another updated miner.

Z-ENEMY VER 1.17 (PUBLIC) From: Dk & Enemy (z-enemy)
-  Major performance improvements: 5-10% for X16R & X16S, XDNA (hex), x17, Bitcore(BTX), c11, Sonoa, Renesis, Aergo
-  Lower end cards like 1050/1060 will see additional few %  (yes, a bonus)
-  The miner no longer depends on memory, it allows to run memory clock at +0 or -500 MHz without performance loss.

Interesting update, as prelim testing shows memory overclocking no longer appears to be required with this miner.

**Comment by nemosminer** [comment]
thanks i'll have that updated in a few hours

**Comment by nemosminer** [comment]
testing supported algos atm

**Comment by nemosminer** [comment]
testing on 8x1060 3gb rig and a 6x1070ti rig

**Comment by nemosminer** [comment]
done
