### ISSUE TITLE
Reduced payment threshold on Zergpool

### ISSUE THREAD

**Issue by papacheal** [nemosminer/NemosMiner#769]
Zergpool reduced their regular BTC payout threshold from 0.005 to 0.0025 a few days ago, so you may want to update pool info for them.

Also, please review my notes on Aergo commit as it doesn't solve the issue previously posted.

**Comment by nemosminer** [comment]
thanks i'll lower that

i did.. aergo is working on zergpool....

**Comment by nemosminer** [comment]
https://imgur.com/a/mM45kpr

**Comment by papacheal** [comment]
That is my point. AeriumX is the coin name, not the algorithm name (aergo). And the deeper issue is that the configured algorithm list for mining is not being "translated" via the Algorithms.txt matrix to standardize them. If I use "lyra2v2" in my algorithm list (which is what all the pools use), it doesn't enable it; you have to use the exact name NemosMiner has defined as the "standard" name (i.e. "lyra2re2"), which seems awkward.

**Comment by papacheal** [comment]
Right...and that is fine for those that want to use all of the algorithms, but most will tune down that to a specific list.

From reading your code, the most graceful solution to the issue seems to be running the $Config.Algorithms list through the Get-Algorithm function to replace and standardize the user-specified names. This can be done when the Config file is first loaded or when the "Start" or "Save Config" buttons are clicked. The TBAlgos.text value can then be regenerated to let the user know what the "corrected" list of algorithms are.

**Comment by nemosminer** [comment]
most leave it blank and use all algos...

**Comment by nemosminer** [comment]
thanks fixed
