### ISSUE TITLE
maybe updating to latest version of miners

### ISSUE THREAD

**Issue by arminmacx** [nemosminer/NemosMiner#770]
Hi,

maybe updating to latest version of miners be good idea because right now ccminer dumax cant handle phi2 and latest version can and i had to redownload it and add it to miners in nemo.
or each time i had to edit powershell script to address this issue

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/blob/master/Miners/ccminerDumax.ps1

https://github.com/DumaxFr/ccminer/releases


im already running latest Dumax 0.8.4 have been for last 20days....
