### ISSUE TITLE
Not mining lyra2RE2 on mph

### ISSUE THREAD

**Issue by ToniG123** [nemosminer/NemosMiner#771]
Hi, I've setup nemosminer and its working on Equihash, Ethash and other algos but it doesnt even try to benchmark Lyra2RE2. I've checked the config files and it seems to be enabled, but still does nothing with it.

¿How can I enable Lyra2RE2?

**Comment by nemosminer** [comment]
adding Excavotor2 from "optional miners" will enable it on MPH 


https://imgur.com/a/4vTydD6

**Comment by ToniG123** [comment]
Excellent, got it working. Thanks for the help!
