### ISSUE TITLE
Nemosminer 3.3 - Unhandled exception error

### ISSUE THREAD

**Issue by Headhunter1231994** [nemosminer/NemosMiner#775]
Hi,

I get a couple of errors using version 3.3
![nemos 3 3 error](https://user-images.githubusercontent.com/25772604/45001028-f47e3800-afc9-11e8-8cf7-c1789c457f65.PNG)

This is the error I got recently. What can I do to solve this?

**Comment by nemosminer** [comment]
use v3.4

https://github.com/nemosminer/NemosMiner/archive/master.zip
