### ISSUE TITLE
Disable Bitcoin Gold

### ISSUE THREAD

**Issue by mctrivia** [nemosminer/NemosMiner#787]
there doesn't seem to be a way to disable BTG.  without dropping equihash all together even though they are different algorithms.  Now that binance is delisting BTG i don't want to mine it any more.

**Comment by nemosminer** [comment]
or jst type in the Alos you want to use and it will only use them... 

if you leave algo list blank it enables all supported algos, if you type in some algos it will only use the one you type and save...

**Comment by mctrivia** [comment]
that isn't an option since list of algos already does not contain equihashBTG but it still does it

**Comment by nemosminer** [comment]
yes it is a option 

eg. tpye ethash in algo tab save

it will mine only etherem based coins..

eg. tyoe ethash,neoscrypt  

it will mine only neoscrypt and ethash based coins 

you need to learn how to use program properly... 

you can mine what ever algo you what to.....

**Comment by mctrivia** [comment]
i know how to use it.  I do not have equihashBTG on my list of algorithms to mine.  it mines it anyways though.  presumably because equihash is on my list.  they arent the same algorithm though.
