### ISSUE TITLE
Enable all algos by default on mining software

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#788]
While all algos are enabled for the app, they are not enabled by default for each mining software.

This becomes a problem later when a new version of mining software is released and an algo is disabled.

**Comment by nemosminer** [comment]
no problem here 

i test them for you best opensource is available in Miners folder
Fastest close source in Optional Miner
if a newer version  of mining software come out i will test all supported algos and enable in NemoMiner if i see improvements...
