### ISSUE TITLE
Wllet Nicehash add separately please

### ISSUE THREAD

**Issue by petrovsky34** [nemosminer/NemosMiner#792]
![default](https://user-images.githubusercontent.com/39003568/45526836-81eb3480-b7e1-11e8-974f-78e36e91cd80.PNG)

**Comment by petrovsky34** [comment]
that would have 2 purses was one on nicehash another on the pools

**Comment by nemosminer** [comment]
this can be achieved already i may add nicehash wallet to gui but not at this stage

**Comment by petrovsky34** [comment]
Ok))) Буду ждать спасибо!!!

**Comment by nemosminer** [comment]
na
