### ISSUE TITLE
Interest in central monitoring?

### ISSUE THREAD

**Issue by grantemsley** [nemosminer/NemosMiner#802]
I built the central monitoring stuff for MultiPoolMiner, that lets you check the status of all your mining machines in one place like this: https://multipoolminer.io/monitor/?address=1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb

Would you be interested in me integrating something similar into nemosminer?  It wouldn't take too much effort to modify it to work with your version.

There is a server part that either you could host for everyone (requires a webserver that supports php and mysql), or people can run themselves for their own private use.

Figured I'd ask if it's something you want before I go through the extra work of making it public.

**Comment by nemosminer** [comment]
is that a different service to this? https://miningpoolhubstats.com/

**Comment by grantemsley** [comment]
I believe the one you linked mostly tracks your pool balances, but I haven't used it personally.

This tracks what each of your mining rigs is doing - whether it's online, if it's mining or paused, which miners are running, which version of nemosminer it's using, uptime, etc.

I find it incredibly useful for making sure none of my machines have rebooted or crashed without having to login to each one. 

Already have a mostly working hacked together version, just have to fix some things and get it integrated properly.

**Comment by nemosminer** [comment]
sure that would be great

**Comment by nemosminer** [comment]
i have webservers that supports php and mysql ready..

**Comment by nemosminer** [comment]
do you have a BTC donation Address @grantemsley  i would like to add you to Dev List  # Developers list and wallets is publicly available at: http://nemosminer.x10host.com/devlist.json

**Comment by grantemsley** [comment]
Really?  Thank you, I really appreciate that.  My BTC address is: 16Qf1mEk5x2WjJ1HhfnvPnqQEi2fvCeity

I'll let you know when the monitoring stuff is ready on my test server so you can test it out (and so can anyone else following this thread).

**Comment by grantemsley** [comment]
Not nearly done yet, but if anyone wants to check the progress so far, it's available here: https://github.com/grantemsley/NemosMiner/tree/monitoring (or https://github.com/grantemsley/NemosMiner/archive/monitoring.zip if you don't use git).

Set the monitoring server to "https://mining.emsley.ca" (no guarantees that will be up either, since it is still a work in progress as well).

**Comment by grantemsley** [comment]
![monitoring](https://user-images.githubusercontent.com/669579/45903294-2a3b6300-bdb7-11e8-9506-31b638950b16.png)

Pretty much done with the changes to nemosminer, unless I find any bugs.  Still working on the server side part that it reports to.

**Comment by nemosminer** [comment]
http://nemosminer.orgfree.com/

**Comment by nemosminer** [comment]
thankyou @grantemsley  http://nemosminer.x10host.com/devlist.json

**Comment by grantemsley** [comment]
Much appreciated :)

**Comment by nemosminer** [comment]
should update readme with some info on Monitoring and how it works so people now as its new.. ?

**Comment by grantemsley** [comment]
Yeah. Maybe just link to the setup guide?  http://nemosminer.orgfree.com/setup.php

**Comment by grantemsley** [comment]
@nemosminer just pushed a tiny bug fix to https://github.com/grantemsley/NemosMiner-MonitorServer - the top menu was broken in mobile view.  May want to update your site to match.

**Comment by nemosminer** [comment]
done
