### ISSUE TITLE
Wrong estimates for equihash on zpool.ca reporting 0

### ISSUE THREAD

**Issue by bhh7419** [nemosminer/NemosMiner#805]
Bminer            Equihash         4,41 KH/s        0,000      0,00000        0,002    0,05583 zpool24hr-
EWBF              Equihash         4,28 KH/s        0,000      0,00000        0,002    0,05583 zpool24hr-

Something wrong with calculations, Pool shows

equihash hot | 2142 | 4 | 198 | 834.7 kS/s | 1.75% | 0.10858 | 0.09960 | 0.02835
and it reports estimates in kS/s on site (not aware how it shows it trough api, please investigate)

**Comment by nemosminer** [comment]
thankyou

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/commit/a688ca62f5be62c8076914ecfb2cdf0396bbbfd0

**Comment by nemosminer** [comment]
updated to 0.6.9

**Comment by nemosminer** [comment]
still showing incorrect price only equihash and only zpool

**Comment by nemosminer** [comment]
may add Bminer back to Wrapper to fix this until proper fix can be made

**Comment by nemosminer** [comment]
disabling equihash asic now
