### ISSUE TITLE
InvalidOperation

### ISSUE THREAD

**Issue by sedver** [nemosminer/NemosMiner#806]
Невозможно вызвать метод для выражения со значением NULL.
C:\Mining\NemosMiner_v3.4\Miners\Bminer.ps1:17 знак:74
+ ... _)).User):$($Pools.(Get-Algorithm($_)).Pass.ToString().replace(',','% ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
СВЕД.: Last error 203

**Comment by nemosminer** [comment]
use v3.4.2
