### ISSUE TITLE
Not really an issue persay...

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner#810]
I would be very leery of using Trex 6.8. It has a known bug that cause it to hang on shutdown on SOME rigs (as per trex discord channel). The dev knows about it and promises to fix it in the next unofficial beta. Last non-beta is 6.6... and 6.7 is rock stable for ME. YMMV

**Comment by grantemsley** [comment]
0.6.9 was released this morning for testing which has a potential fix for that bug

**Comment by nemosminer** [comment]
updated to 0.6.9
