### ISSUE TITLE
Something wrong with nlpool.nl

### ISSUE THREAD

**Issue by jigoku-shoujo** [nemosminer/NemosMiner#815]
Something seems to be way off to the calculations of nlpoolplus.

Anyone else checked this?

**Comment by nemosminer** [comment]
i'll check today i did check it when i 1st merge support it was right  at the time

**Comment by jigoku-shoujo** [comment]
Most algorithms seem OK, even a little lower than other pools, but yescrypt shows crazy profitability. For my 9x1070 rig it showed something like 68€ per day, and of course it's nowhere near that.

**Comment by jigoku-shoujo** [comment]
![untitled-1](https://user-images.githubusercontent.com/25940211/46106197-bf3bc300-c1e0-11e8-8bad-3a4a786cc33b.jpg)

**Comment by gak45** [comment]
Any status update on this? It is still showing crazy profits for yescrypt. eg 10Kh/s is showing 3.5mbtc!

**Comment by nemosminer** [comment]
not yet for now just remove yescrypt from algo list

-yescrypt

Algo selection / removal
  
      +algo for algo selection
      -algo for algo removal

      If "+" Used, all selected algo have to be listed
      If "Minus" Used, all algo selected but exluded ones.

      Do not combine + and - for the same algo

     Examples:
     Algo list = -x16r
     Will mine anything but x16r

     Algo list = -x16r,-bcd
     Will mine anything but x16r and bcd

     Algo list = +x16r
     Will mine only x16r

     Algo list = +x16r,+bcd
     Will mine only x16r and BCD

     Algo list = +x16r
     Will mine only x16r

     Algo list blank
     Will mine anything

**Comment by nemosminer** [comment]
still not correct i don't think

**Comment by gak45** [comment]
yeah still borked, but their stats are way, way inflated. So I dont think it matters.
Stats claimed 3.0mbtc. Ran it for 48hrs... got 0.1mbtc per day. Ugh. Ran away... as no way I was getting 8.7mbtc on third day to get 3.0mbtc avg.
For comparison. Blaze claims 2.6 I get 2.6.

**Comment by nemosminer** [comment]
sorted https://github.com/nemosminer/NemosMiner/commit/a5c92b108d3e8f789366de6d756bcf440ebf932f
