### ISSUE TITLE
2080 / ti

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#819]
v3.5 https://github.com/nemosminer/NemosMiner/archive/master.zip

newest Nvidia driver is required 411 + : https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/411.70/411.70-desktop-win10-64bit-international-whql.exe&lang=us&type=TITAN

**Comment by nemosminer** [comment]
use v3.5 https://github.com/nemosminer/NemosMiner/archive/master.zip   (not released yet)

**Comment by grantemsley** [comment]
You aren't planning on dropping support for the 10 series cards any time soon right?  It's going to be quite awhile before I even consider replacing all mine with new ones.

**Comment by nemosminer** [comment]
now will support both just waiting on trex cuda 10 (2080 support then v3.5 will be released)

with support for 1060 6gb to 2080ti

**Comment by petrovsky34** [comment]
1050ti
