### ISSUE TITLE
Add nlpool to poolapiref.json

### ISSUE THREAD

**Issue by grantemsley** [nemosminer/NemosMiner#823]
Needs to be updated in github and at http://nemosminer.x10host.com/poolapiref.json

    {
        "Name":  "nlpool",
        "EarnTrackSupport":  "yes",
        "PoolUri":  "https://www.nlpool.nl",
        "WalletUri":  "https://www.nlpool.nl/api/walletEx?address=",
        "StatusUri":  "https://www.nlpool.nl/api/status",
        "CurrenciesUri":  "https://www.nlpool.nl/api/currencies",
        "PaymentThreshold":  0.001,
        "Total":  "total",
        "Balance":  "balance"
    },

**Comment by nemosminer** [comment]
done
