### ISSUE TITLE
Better Handling of 3gb cards 

### ISSUE THREAD

**Issue by Nickfost** [nemosminer/NemosMiner#824]
I have 30 nvidia 1060s 3gb and i want hoping to miner less alts with ethash

**Comment by nemosminer** [comment]
nope

**Comment by nemosminer** [comment]
Easy configuration, easy start:

  Run NemosMiner.bat
  1. Config tab
  2. Set your Wallet address and Username
  3. Select your pool 
  4. Save Config
  5. Start
  
  note: 2. you only need to change Username if you are using Miningpoolhub
  
 Algo selection / removal

  +algo for algo selection
  -algo for algo removal

  If "+" Used, all selected algo have to be listed
  If "Minus" Used, all algo selected but exluded ones.

  Do not combine + and - for the same algo

 Examples:
 Algo list = -x16r
 Will mine anything but x16r

 Algo list = -x16r,-bcd
 Will mine anything but x16r and bcd

 Algo list = +x16r
 Will mine only x16r

 Algo list = +x16r,+bcd
 Will mine only x16r and BCD

 Algo list = +x16r
 Will mine only x16r

 Algo list blank
 Will mine anything
Pools variants

  24hr - uses last 24hour Actual API too request profit
     -Low switching rate
  plus - uses advanced calculations to reduce switching
     -Medium switching rate
  normal - uses current estimate API too request profit
     -High switching rate
