### ISSUE TITLE
Zergpool shutting down

### ISSUE THREAD

**Issue by grantemsley** [nemosminer/NemosMiner#825]
From their website:

    We have taken decision to close down the pool. Stratum servers will be stopped during next hours, and all pending earnings payed within next 24h.

May not want to remove it entirely just yet, but I'd recommend stopping mining on it.

**Comment by nemosminer** [comment]
i know

**Comment by nemosminer** [comment]
https://bitcointalk.org/index.php?topic=2759935.msg46774096#msg46774096

**Comment by MrPlusGH** [comment]
Pushed #826
As ZPool is low on BCD block found, This will allow to mine with Plus based on projection when actuals are not available.

**Comment by MrPlusGH** [comment]
Should we use autoupdate to replace Zergpool with zpool for miners which have Zergpool still active in config?
We could push a update where nothing changed but where the PostUpdateActions.ps1 changes Zergpool with zpool is selected.

This would help users who are not monitoring closely not loose hashrate by still mining Zergpool.

**Comment by nemosminer** [comment]
yes i switched all my rigs manually already, yes we should do that for other users who have not be following zerg and don't know
