### ISSUE TITLE
Phi  phi pool

### ISSUE THREAD

**Issue by gilby77** [nemosminer/NemosMiner#829]
Connection error all algos.

**Comment by nemosminer** [comment]
thanks

**Comment by nemosminer** [comment]
fix https://www.phi-phi-pool.com/

**Comment by nemosminer** [comment]
its not a issiue with nemosminer... i can not connect to https://www.phi-phi-pool.com/ stratum server at all even just with a normal .bat file and ccminer..

https://imgur.com/a/mTMSCuA

**Comment by MrPlusGH** [comment]
https://github.com/MrPlusGH/NPlusMiner/releases/tag/4.5.3
