### ISSUE TITLE
benchmarking issues with tribus

### ISSUE THREAD

**Issue by diablos821** [nemosminer/NemosMiner#832]
when running a full benchmark and running all algos, stumbled upon 
Bin\NVIDIA-TPruvotx64\ccminer-x64.exe -b  -a tribus -o stratum+tcp://blockmasters.co:8533 -u <wallet> -p ID=<id>,c=BTC -d  --api-remote --api-allow=0/0
where it gose -d -- api-remote, it is missing the device number usually "0,1" or what ever number of devices 

i would assume its just a typo error in the command string builing process just thoguht id give it a mention 
if you require any thing else feel free to ask aka need logs, configs, or anything else

**Comment by nemosminer** [comment]
no its correct and working correctly

**Comment by diablos821** [comment]
yeah i think i did a stupid, i copy pasta over 3.4 rather then a full new installation... fixed now so yeha my bad
