### ISSUE TITLE
Add support for ccmineralexis78

### ISSUE THREAD

**Issue by rinkal26783** [nemosminer/NemosMiner#833]
Did you remove ccmineralexis78 from miner folder?
There are still some algos good to miner with ccmineralexis78. 
Please add ccminerAlexis78-v1.3 to miner folder. and add support for following algos.
Skein
x11evo
x11
x13
x14
Keccakc

**Comment by nemosminer** [comment]
no alexis 78 does not work with rtx cards

**Comment by nemosminer** [comment]
i'll re add and disable with # users can enable if wanted..

**Comment by nemosminer** [comment]
done

**Comment by nemosminer** [comment]
recompiled with cuda10.0 with RTX Support

**Comment by nemosminer** [comment]
re enabled
