### ISSUE TITLE
NemosMiner Monitoring

### ISSUE THREAD

**Issue by scavern** [nemosminer/NemosMiner#837]
Estimated profit shows per miner but not in the total.

**Comment by nemosminer** [comment]
what is the issiue? are you Requesting something?

**Comment by scavern** [comment]
Sorry, yes I am referring to the monitoring website. I have a test miner on it. It's great for a quick glance at info. It does however only show the estimated profit per miner, and not the total.

It is happening all the time.

e86cb133-78b6-450e-ac4d-f8c699dd6c14

**Comment by grantemsley** [comment]
Ok I see what you mean now.  I'm on it!

**Comment by grantemsley** [comment]
@scavern I don't seem to be able to duplicate the problem myself so far.  Can you please temporarily change the server on the monitoring tab to 'https://mining.emsley.ca'?  You can keep the same settings for everything else.  I can do a bit more to diagnose if if it's reporting there.

**Comment by grantemsley** [comment]
Ok, that was very helpful...what language and region is your computer set to?

Powershell seems to be unexpectedly localizing the number and using a comma for the decimal separator.

**Comment by scavern** [comment]
Language: English (United States)
Region: South Africa

**Comment by grantemsley** [comment]
@scavern awesome.  Thanks for your help narrowing it down.

I've made a pull request that will fix the issue for the next release.

**Comment by scavern** [comment]
great thanks!
