### ISSUE TITLE
Benchmarking stuck on algos not selected

### ISSUE THREAD

**Issue by neofixdata** [nemosminer/NemosMiner#840]
New version gets stuck benchmarking I dont understand why we have to benchmark algos we haven't selected. It wants to benchmark all algos at zpool24hrs. Everything else is great.

**Comment by nemosminer** [comment]
Algo selection / removal
  
      +algo for algo selection
      -algo for algo removal

      If "+" Used, all selected algo have to be listed
      If "Minus" Used, all algo selected but exluded ones.

      Do not combine + and - for the same algo

     Examples:
     Algo list = -x16r
     Will mine anything but x16r

     Algo list = -x16r,-bcd
     Will mine anything but x16r and bcd

     Algo list = +x16r
     Will mine only x16r

     Algo list = +x16r,+bcd
     Will mine only x16r and BCD

     Algo list = +x16r
     Will mine only x16r

     Algo list blank
     Will mine anything

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/835
