### ISSUE TITLE
DUAL mining

### ISSUE THREAD

**Issue by Yogurt79** [nemosminer/NemosMiner#846]
Good day. Please add mining DUAL to Bminer and Claymore (can be on Nicehash or another pool). Thank you very much.

**Comment by nemosminer** [comment]
not atm

**Comment by nemosminer** [comment]
which pool?

**Comment by nemosminer** [comment]
done phiphi has it

**Comment by nemosminer** [comment]
is it even worth it ? i haven't dual mined in years
