### ISSUE TITLE
Nicehash error loading pool stats

### ISSUE THREAD

**Issue by dealbreak3r** [nemosminer/NemosMiner#850]
Long-time user of Nemosminer, still looking for the best alternative since zergpool shut down.  I tried selecting NiceHash and it won't work for me.  I gave up and downloaded a fresh master.zip this morning
leaving all the default fields filled in:

![settings](https://user-images.githubusercontent.com/37665464/47583086-5c932f80-d924-11e8-9de9-69b28aba3f00.JPG)

From the start it won't download stats (error contacting the pool, retrying..) and null errors:

![statsdownload1](https://user-images.githubusercontent.com/37665464/47581919-d3c6c480-d920-11e8-854c-b74e18da3006.JPG)

I removed `-TimeoutSec 15` from line 4 of nicehash.ps1 and that allowed the stats to download from the API (populated in the stats folder).  Errors still persist:

![statsdownload3](https://user-images.githubusercontent.com/37665464/47582075-5780b100-d921-11e8-9614-d9560b75b18e.JPG)

Errors during refresh cycles:

![statsdownload4](https://user-images.githubusercontent.com/37665464/47583100-64eb6a80-d924-11e8-808c-744d3f11684f.JPG)

Fresh install. All other pools work (ahashpool, zpool, etc). It still mines, just a boat load of errors. Thoughts?

**Comment by nemosminer** [comment]
i'll double check now i downloaded master myself last nite on fresh rig i am also running nicehash atm been good profits last week or so, i had no issue

**Comment by nemosminer** [comment]
downloaded master just now it fine on nicehash no errors at all

**Comment by nemosminer** [comment]
https://imgur.com/a/G2MSWam

**Comment by nemosminer** [comment]
https://imgur.com/a/gU4S85n

**Comment by nemosminer** [comment]
https://imgur.com/a/z3nfTdi

**Comment by nemosminer** [comment]
all is well with NemosMiner and Nicehash

**Comment by nemosminer** [comment]
im not sure why you seem to be getting those errors i am not...

**Comment by nemosminer** [comment]
i'll installing 3 new rigs for people today i will be installing NemosMiner latest code on each one and they all requested nicehash as default pool so will let you know how they get on these are new rigs in different locations to my own

**Comment by nemosminer** [comment]
Latest source code https://github.com/nemosminer/NemosMiner/archive/master.zip

**Comment by dealbreak3r** [comment]
Thanks for lending a hand. I was able to fix it by manually deleting all the exclusions in Windows Defender, and letting NemosMiner prompt again at first run to re-add. Seemed to do the trick. No more errors.

**Comment by nemosminer** [comment]
no worries im glad its sorted for you
