### ISSUE TITLE
Use the correct region for stratum servers on Z-Pool

### ISSUE THREAD

**Issue by MonaxDK** [nemosminer/NemosMiner#857]
In the settings of nemosminer, I have set a location - EU, but in the miner window I see that the default location is used. 
![clipboard01](https://user-images.githubusercontent.com/29005588/48347334-b3b83480-e686-11e8-8559-213cb38c4874.png)
Here is an example setup from Z-Pool

```
STRATUM SERVERS - North America <na> - Europe <eu> - South East Asia <sea>
ccminer example:
-o stratum+tcp://<algo>.<region>.mine.zpool.ca:<PORT> -u <WALLET_ADDRESS> [-p c=<SYMBOL>,<OPTIONS>]
```

I did something wrong, or is it a miner problem?

**Comment by nemosminer** [comment]
miner problem. i just use usa server ping does effect hashrate or accepted shares (ie, profitability is un effected by server location its just to have lower latency thats all.

**Comment by MonaxDK** [comment]
They write that ping can affect the hash rate, at least it is worth checking

**Comment by nemosminer** [comment]
they?

**Comment by MonaxDK** [comment]
![111](https://user-images.githubusercontent.com/29005588/48369810-3c06fb80-e6c0-11e8-8e9c-e8f7f7e99851.jpg)
)))
For example:
https://ethereum.stackexchange.com/questions/18201/does-network-latency-significantly-affect-mining-rewards

**Comment by nemosminer** [comment]
done

**Comment by nemosminer** [comment]
tested working well 
Now fully support "eu", "us", "na", "sea"

**Comment by nemosminer** [comment]
also updated fixed nicehash stratum servers
