### ISSUE TITLE
ethash will not stop mining even though it does not work

### ISSUE THREAD

**Issue by jsnyder10** [nemosminer/NemosMiner#858]
I have disabled ethash in the Algorithm box in the GUI and IT won't stop trying to benchmark it. I deleted ethminer, I removed ethash from all pool configs, I have done everything to make it ignore ETHASH. It WILL not stop trying to run ethash for no reason. Ethash Does not work on my computer and I can not disable it. I can not use nemosminer anymore because it refuses to stop using ethash.

**Comment by nemosminer** [comment]
..

**Comment by nemosminer** [comment]
or you can delete Ethminer.ps1 from miners folder & EthashPhoenix3.5d.ps1 from optional miners

this will also disable ethash..

**Comment by jsnyder10** [comment]
Thanks nemosminer that fixed it. Now when will you offer AMD support?

**Comment by nemosminer** [comment]
try this can you ley me know how you get on? https://github.com/Kudaraidee/KudaraideeV4/archive/master.zip
