### ISSUE TITLE
Equihash algo issue

### ISSUE THREAD

**Issue by edilcan** [nemosminer/NemosMiner#861]
After Nemosminer version v3.5 or updating Nvidia driver that include Cuda10 libraries, I am not sure at the moment, I cannot mine any equihash algo.
I have also test EWBFv2 manually in Bin folder (which has Cuda9 libs), miner starts correctly and get shares. Do you have any idea?

As a note that if I write to "+equihash" on algorithm section, nemos reports that no miner found

**Comment by nemosminer** [comment]
Asic Mined

**Comment by edilcan** [comment]
Does Equihash-BTG mineable with ASIC?
