### ISSUE TITLE
Constantly restarting miner

### ISSUE THREAD

**Issue by MonaxDK** [nemosminer/NemosMiner#864]
Sometimes, the application starts to constantly restart the miner, approximately every minute. Restarting Nemos solved the problem.
![viber image](https://user-images.githubusercontent.com/29005588/48646411-72f74d00-e9f1-11e8-898b-138e8423981d.jpg)
[Logs.zip](https://github.com/nemosminer/NemosMiner/files/2590945/Logs.zip)

**Comment by sephir69** [comment]
had the same prob just thought my system was bugged out

**Comment by nemosminer** [comment]
have not come across that myself.. msi afterburner is known to cause issues and is NOT recommended use Nvidia Inspector to control OC/PL also suggest using latest source code not old release..

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/archive/master.zip
