### ISSUE TITLE
Ethminer 0.18.0-alpha.1 cuda 10

### ISSUE THREAD

**Issue by Yogurt79** [nemosminer/NemosMiner#868]
HI.  ethminer 0.18.0-alpha.1 cuda 10 not work with Nicehash. 
Please correct

**Comment by nemosminer** [comment]
i'll check 0.18.0-alpha.0 cuda 10 was algood

**Comment by nemosminer** [comment]
roll back

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/commit/9dba77beb1f78a86b58af6e88a03335b9a215013

**Comment by Yogurt79** [comment]
0.18.0-alpha.0 cuda 10 work good

**Comment by nemosminer** [comment]
nicehash yes mining pool hub no...

**Comment by Yogurt79** [comment]
Thank U
