### ISSUE TITLE
Gminer

### ISSUE THREAD

**Issue by ghost** [nemosminer/NemosMiner#875]
HI.
Please add Gminer 
https://bitcointalk.org/index.php?topic=5034735.0 
ThankU

**Comment by nemosminer** [comment]
sure can only    - Equihash 144,5 nicehash  support so not much point as i already have EWBF and Bminer.. there seems to be no increase in speed over ewbf...

**Comment by nemosminer** [comment]
ok i'll have a look cpu mining is possible you can you this version : https://github.com/MrPlusGH/NPlusMiner/releases

**Comment by Yogurt79** [comment]
Your version is better updated and I think that the CPU needs to be added !!! thank

**Comment by nemosminer** [comment]
just add cpuminer.ps1 files from nplus and tick the cpu selection.. i my add support at some point..

**Comment by Yogurt79** [comment]
I tried, it does not display CPU in Benchmarks

**Comment by nemosminer** [comment]
that is a shame, 

in regards to this Issue: "HI.
Please add Gminer
https://bitcointalk.org/index.php?topic=5034735.0
ThankU"

No

**Comment by Yogurt79** [comment]
> это стыд,
> 
> в отношении этой 
> проблемы : «HI. Пожалуйста, добавьте Gminer 
> https://bitcointalk.org/index.php?topic=5034735.0
> ThankU»
> 
> нет

OK
