### ISSUE TITLE
Z-ENEMY 1.26 ver.1  From: Dk & Enemy (z-enemy)

### ISSUE THREAD

**Issue by Yogurt79** [nemosminer/NemosMiner#876]
Z-ENEMY 1.26 ver.1  From: Dk & Enemy (z-enemy)

IMPORTANT:
For maximum performance make sure you have latest drivers  (ver. 415+)
http://www.nvidia.com/Download/index.aspx

Performance improvements:
- Up to +5-7% x16r/s, +7% bitcore, few percent on others (x17, c11, aergo ...) on GTX 10x0 cards.
- Hex algo +10% for GTX 10x0 cards and +2% for RTX 20x0 cards.

Other changes:
- Removed renesis algo
- Improved stability

@everyone

Windows:

Cuda 10.0(For 10x0 & 20x0 cards, new drivers ver 411+):https://mega.nz/#!hOQyzS5T!MNgW0srchmQHSgbpM5D0nKaiABG_6l44i-MYF-iUeEA
Cuda 9.2 (For 10x0 cards and drivers over ver 397+): https://mega.nz/#!EeBmgYrb!eKNSW0FyGOQWVpecHy3FQHYdg40HBbhXhFmDa3OC5Es
Cuda 9.1 (For 10x0 cards and drivers over ver 388+): https://mega.nz/#!0OB0WICS!kPvsbHxOtgPebX1JvwQRGLdp0-_4njbmnY2RCCqaceM

Linux: (HiveOS, PiMP OS , EthOS & Ubuntu):
Cuda   9.1 : https://mega.nz/#!ZeRACSxa!gzecFEiM-3vs4zOU1b3WtMhokAw8IZ_3un7zkwS7fAM
Cuda   9.2 : https://mega.nz/#!VbJk0CiL!RzP_A1gnlbhWXvSvyc2djg0nLp4_QTymBjztuVh_GxQ
Cuda  10.0 : https://mega.nz/#!hKI0HC7J!9Q2XV6qDLFX0NEalXO1fW3DOZ-i2PMY3xi3qsQZXwo4

**Comment by nemosminer** [comment]
Appreciated
