### ISSUE TITLE
Update FireIce 2.7.0

### ISSUE THREAD

**Issue by UselessGuru** [nemosminer/NemosMiner#877]
https://github.com/fireice-uk/xmr-stak/releases/tag/2.7.0

also see https://github.com/fireice-uk/xmr-stak/issues/2119

**Comment by MrPlusGH** [comment]
https://github.com/nemosminer/NemosMiner/commit/056ad7832828a1e5f7e534bdb4bddc7eee9fd12e

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/commit/056ad7832828a1e5f7e534bdb4bddc7eee9fd12e

thanks but it was already done..

**Comment by nemosminer** [comment]
@UselessGuru did you want a recompile ?
