### ISSUE TITLE
update ccminer x21s

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner#890]
add support for

compute_60,sm_60;compute_61,sm_61;compute_52,sm_52;compute_50,sm_50;compute_35,sm_35;compute_30,sm_30;compute_37,sm_37;compute_70,sm_70;compute_75,sm_75

recompile with vs2017v141cuda10.0 

RTX

**Comment by RockClubKASHMIR** [comment]
https://github.com/RitoProject/ccminer/releases/download/20181201/ccminer-2.3-cuda9.7z not exist

**Comment by nemosminer** [comment]
thanks

**Comment by nemosminer** [comment]
https://github.com/RitoProject/ccminer/archive/20181201.zip
