### ISSUE TITLE
Miner restart

### ISSUE THREAD

**Issue by MonaxDK** [nemosminer/NemosMiner#893]
The program closes the miner and opens it again, although the best algorithm has not changed. For example, it works on X17 on the T-Rex miner, at the end of the interval the miner closes and then opens again on the same x17.
The interval is set to 300 seconds
[Logs.zip](https://github.com/nemosminer/NemosMiner/files/2663078/Logs.zip)

![clipboard01](https://user-images.githubusercontent.com/29005588/49732276-bfe3e180-fc86-11e8-83a3-214eb2849e34.png)

**Comment by MrPlusGH** [comment]
I guess the miner is crashing for some reason.
could you run the miner in a command prompt and post the error message you get?

**Comment by nemosminer** [comment]
i have not been able to reproduce this
