### ISSUE TITLE
cryptodredge extranonce2 size hmq1725 error

### ISSUE THREAD

**Issue by gilby77** [nemosminer/NemosMiner#904]
Mining on cryptodredge 0.16.0 get error extranonce2 size,mining on zpool hmq1725 algo.

**Comment by nemosminer** [comment]
been fixed in 0.16

**Comment by nemosminer** [comment]
i need screen shots any more info that was happening in all previous versions of CD but not 0.16 where it has been fixed...   i will need to pass screen shots on to CD devs... Note me and STSMiner have both been testing 0.16 on zpool last 24hours we have not had this Issiue..
