### ISSUE TITLE
Cannot connect to ahashpool

### ISSUE THREAD

**Issue by GuyTechie** [nemosminer/NemosMiner#905]
Getting a "! Error contacting pool retrying in 30 seconds.." indefinitely.

**Comment by nemosminer** [comment]
thanks fix soon

**Comment by nemosminer** [comment]
fixed in the master : https://github.com/nemosminer/NemosMiner/archive/master.zip will be in next release

**Comment by GuyTechie** [comment]
Thanks!  Looking forward to it in the next mainstream auto update

**Comment by english1234** [comment]
Looking forward to this too. Which is the file which needs updating to make it work again?
