### ISSUE TITLE
Zergpool is back

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner#907]
Zerg is in the process of getting backup. Might want to think about getting pool options ready for it, and being able to add it once it is official.

**Comment by nemosminer** [comment]
awesome thankyou

**Comment by gak45** [comment]
Talk about it on their discord chan, pinpin is adding in coins and doing server work... and 200 peeps are mining on the zerg as we speak :)

**Comment by nemosminer** [comment]
thanks i got it, testing now nice made it into v3.6.6 Release !
