### ISSUE TITLE
Whalesburg Pool

### ISSUE THREAD

**Issue by MaynardMiner** [nemosminer/NemosMiner#909]
https://payouts.whalesburg.com/profitabilities/share_price

It took me awhile of climbing through their developer team, but I found out their api specs for profit.

it's ETH/mhs/second, and they do ETH only, but it is profit-switching.

I'm passing it around. I plan to make a pool file for it soon myself. Please pass it on.

**Comment by nemosminer** [comment]
ok already got ethash with nicehash and miningpoolhub so not to worried
