### ISSUE TITLE
cuckoo

### ISSUE THREAD

**Issue by Moskga** [nemosminer/NemosMiner#912]
for 3Gb video card ( like 1060) in zjazz need key
--cuckoo-intensity 16

or is crashed....

**Comment by nemosminer** [comment]
ok NemosMiner does not support 3gb cards..

Tested with 6x1070 6x1070ti 6x1080ti 6x2080 (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards

**Comment by Moskga** [comment]
why not support?! - in my videocard (5*1063 ,3*1063 ,481063) is working nemos is working....
