### ISSUE TITLE
TT-Miner 2.1.7

### ISSUE THREAD

**Issue by UselessGuru** [nemosminer/NemosMiner#913]
I've implemented in in MPM.

The miner uses the Claymore API, but the reported Ethash hashrate is NOT /1000 as all other Claymore based miners.

Also it requires logic to distinguish CUDA versions.

Since I do not (yet) understand enough of the inner logic of Nemos Miner I don't dare to hack around your code. So for your convenience I've attached some code that might be of use to you.

[NVIDIA-TTMiner_v2.1.7.zip](https://github.com/nemosminer/NemosMiner/files/2793709/NVIDIA-TTMiner_v2.1.7.zip)

**Comment by nemosminer** [comment]
thanks is TT faster than PhoenixMiner_4.1c ?

**Comment by UselessGuru** [comment]
NO, but it offers other algos

**Comment by nemosminer** [comment]
none that are on the pools we use...
