### ISSUE TITLE
Help needed for test on miningpoolhub

### ISSUE THREAD

**Issue by edilcan** [nemosminer/NemosMiner#915]
I try to enable all supported coins on miningpoolhub for test but on current situation only 3 algos are shown and these are; ethash, yescypt and neoscrypt. Stats link (https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics) on miningpoolhub.ps1 return multi algos but I cannot understand which code sections drop algos to three. 

Just for test purposes how can I enable all coins supported by miningpoolhub?

**Comment by nemosminer** [comment]
they are the only thing worth mining on MPH they have no good coins really apart from ethash.... i havn't used mining pool hub in over a year no point..

**Comment by nemosminer** [comment]
i have another look at it let me no what algos your would like enabled?

**Comment by edilcan** [comment]
I just want to enable every coins even if it is not worthy to mine. I could not find which piece of code disable other coins.

**Comment by nemosminer** [comment]
i removed any algos that are un profitable im not going to add them back.. no point

**Comment by edilcan** [comment]
I did not request to add algos back, just wonder which code section needs to be modified to enable deleted algos. Thanks for your meaningless help

**Comment by nemosminer** [comment]
edit the miners.ps1 remove # from algos you want to enable..
