### ISSUE TITLE
Gminer 1.25

### ISSUE THREAD

**Issue by DrRobotto** [nemosminer/NemosMiner#917]
On my testrig (2*1070ti) the issue still persists

**Comment by nemosminer** [comment]
try this one its working on my rigs running it atm... https://nemosminer.com/data/optional/gminer_1_25_minimal_windows64.7z

**Comment by nemosminer** [comment]
been testing it last 12hours...

**Comment by nemosminer** [comment]
it allgood.. must be user related problem...

**Comment by DrRobotto** [comment]
Hm, it gives me this
![beam](https://user-images.githubusercontent.com/20887855/51942733-1e704500-2418-11e9-9bb5-90c4a4ebe860.png)

**Comment by nemosminer** [comment]
remove +ssl from coomand will fix that for you @DrRobotto

**Comment by DrRobotto** [comment]
Thx, fixed
