### ISSUE TITLE
ccminer-KlausT-8.21-mod-r18-src-fix

### ISSUE THREAD

**Issue by platinum4** [nemosminer/NemosMiner#925]
Perform your duties and recompile this new shiz and release as yescryptR32 ty

**Comment by nemosminer** [comment]
hi @platinum4  i need source code if you would like me to compile this for you

**Comment by platinum4** [comment]
[ccminer-KlausT-8.21-mod-r18-src-fix.zip](https://github.com/nemosminer/NemosMiner/files/2824463/ccminer-KlausT-8.21-mod-r18-src-fix.zip)

**Comment by nemosminer** [comment]
this is older version..
the compiles im using currently are based on KlausT-8.23 
why go backwards?

**Comment by platinum4** [comment]
8.23 is different code base and not necessarily faster

**Comment by nemosminer** [comment]
ok will attempt to compile today will release here when done: https://github.com/nemosminer/ccminer-KlausT-8.21-mod-r18-src-fix

**Comment by nemosminer** [comment]
done its very fast on lyra2v3 faster than CryptoDredge even.. thankyou
