### ISSUE TITLE
Missing algos on zpool

### ISSUE THREAD

**Issue by MonaxDK** [nemosminer/NemosMiner#927]
I noticed recently that some algorithms are missing from the application. For example BCD and a few more that are present on the pool, but they are not in the application.

**Comment by nemosminer** [comment]
bcd is supported with trex optionalminers

**Comment by MonaxDK** [comment]
I think you do not quite understand what I mean.
As you can see, optional miners are on, BCD is not among the forbidden algorithms. However, it`s not listed.
![clipboard01](https://user-images.githubusercontent.com/29005588/52181496-4803e480-27fb-11e9-96a4-ca3cbe803060.png)

**Comment by nemosminer** [comment]
i understand exactly what you mean.. your using zpool24hr and zpool has not found a BCD block in last 24hours.. therefore nothing to show... try zpool or zpoolplus it will be there..

**Comment by MonaxDK** [comment]
This is not really a problem, but choosing zpool or zpoolplus does not help, there is still no BCD in the list
