### ISSUE TITLE
Strange behavior when changing the "-i" parameter

### ISSUE THREAD

**Issue by MonaxDK** [nemosminer/NemosMiner#928]
I have experimented with the "-i" parameter on some algorithms. If you change this parameter on the KlausT miner, in the file NemosMiner\Miners\ccminerKlausT.ps1, the application after restart downloads the miner again and it takes another stop / start to start the bench.
At the same time, if you change the "-i" parameter on some algo for Trex miner, the application does not download it again and immediately starts the bench.
Also about speed, with a default value of -i 12.5 on the yescrypt algo, the speed on my system (1080ti) is 40MH, with a value of -i 14.5 - 55MH. Almost the same with yescryptR8 - default -i 12.5 40MH, -i 14.5 57MH.  
I also noticed that if I remove the -i parameter at all, the miner himself will choose the best value. When I remove this parameter, I get the best speeds. I think this applies to all miners.

**Comment by nemosminer** [comment]
thanks

**Comment by nemosminer** [comment]
does not apply to all miners..

**Comment by MonaxDK** [comment]
So far, I can confirm that not specifying the -i parameter works well on KlausT and ccminerdyn
It does not work as it should for Trex

**Comment by MonaxDK** [comment]
had to add -i parameter in ccminerKlausTR32.ps1 otherwise it crashes.
I set the value to -i 13 (7.6 GB of memory is used), perhaps for cards with a smaller memory amount, less is needed.

**Comment by nemosminer** [comment]
thanks i set it to -i 12.5
