### ISSUE TITLE
Exclude GPU from Miner

### ISSUE THREAD

**Issue by aflakta** [nemosminer/NemosMiner#929]
Hello, How can exclude a GPU from a miner?,

For example:

I'm using 4 gtx 1080 ti and 1 gtx 1060 3gb with all algos enabled...

but there are only one miner that don't allows me run because the gtx 1060 3gb doesn't support it, "ccminermtp "  what i wanna to do is run only the 4 gtx 1080 ti ..

i'll appreciate any help, thanks so much

**Comment by nemosminer** [comment]
edit ccminermtp.ps1 find -d $($Config.SelGPUCC) 

change it to suit your 1080ti only 

eg: 

-d 0,1,2,3    (thats assuming 10603gb is card 4)
-d 0,1,3,4    (if 10603gb is  card 2)

Best Regards
Nemo

**Comment by nemosminer** [comment]
if you can't find -d $($Config.SelGPUCC) 

download and use latest master version it has been updated for you

master:  https://github.com/nemosminer/NemosMiner/archive/master.zip

**Comment by aflakta** [comment]
Thanks a bunch!! dude!!

**Comment by aflakta** [comment]
What is the best Overclocking setting for all algos using gtx 1080 ti?
