### ISSUE TITLE
Getting systematic "You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by english1234** [nemosminer/NemosMiner#931]
I'm getting Failed: 1 systematically, every miner is exiting with "You cannot call a method on a null-valued expression" in the log and no mining is being done. This seems to have happened in the last 2 or 3 days over the last 3 or 4 releases.

Have tried turning off overclocking, and resetting benchmarks and profits. This is using ahashpool.

**Comment by nemosminer** [comment]
no
