### ISSUE TITLE
Gminer is faster than Bminer on grincuckaroo29 with 1080 Ti

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#936]
I have 5x 1080 Ti, overclocked 75%/+150/+500
NVIDIA driver: 417.71

This is the result:
![image](https://user-images.githubusercontent.com/1230402/52852093-fbcc7480-3117-11e9-932b-683da18e94ee.png)

So, in my case, your statement is not true that Gminer...
> fastest on 20 series, Bminer faster on 10series

Maybe removing the `-nofee` option? Because we probably lose more hashrate:
> -nofee Disable the devfee but it also disables some optimizations.

**Comment by dealbreak3r** [comment]
Opposite for me, (3) 1070 Ti's.  If your pool reports 24hr average hash rates (I'm on SparkPool at the moment) do a comparison.   I find the hashrate reported by Gminer is not accurate.

Solely using Gminer for the past week: Miner output shows 14.9 G/s, but the pool has been consistently reporting 13.89 G/s 24hr avg (0% invalid shares). 
I switched to BMiner a day ago. Although i'm now getting 4% rejected shares, my pool average has crept up to 14.33 G/s 24hr avg.

Do some tests, see what works best for you.

**Comment by borzaka** [comment]
Well, the test results are interesting...

I have tested Gminer and Bminer for 12 hours straight each. The REPORTED hashrate by the miners (devfee excluded):
```
Miner           Algorithm            Speed mBTC/Day BTC/Day USD/Day   BTC/GH/Day Pool
-----           ---------            ----- -------- ------- -------   ---------- ----
Gminer          Grincuckaroo29  36,26  H/s    1,480 0,00148   5,276 40 823,18600 nicehash-
Bminer          Grincuckaroo29  32,83  H/s    1,340 0,00134   4,778 40 823,18600 nicehash-
```
So Gminer looks way faster than Bminer. But when I checked the results on the pool side, it's the opposite.

### Gminer on NiceHash 12 hours: **27,74 G/s** average
![image](https://user-images.githubusercontent.com/1230402/52899122-a6ab6400-31e6-11e9-9fe8-950b9f528b1d.png)
27,74 G/s average? WTF? This is nothing close the the reported 36,26 G/s!

### Bminer on NiceHash 12 hours: **32,75 G/s** average
![image](https://user-images.githubusercontent.com/1230402/52899094-559b7000-31e6-11e9-9a97-5aa450debf3e.png)
Well, the average is pretty close the reported 32,83 G/s, but I see many rejected shares here.
I can't see the exact percentage for this 12 hours test, and can't see either in the miner, because when there are too many rejected shares the miner resets the counter and starts over. Now the miner reports ~2,7% rejected shares (but I don't know the timespan).

_Note: the big gap probably a NiceHash API or a temporary connection problem._

Bonus: you can see the elevation in the average hashrate in the graph in the last 24 hours.
First half: Gminer
Second half: Bminer
![image](https://user-images.githubusercontent.com/1230402/52899333-41a53d80-31e9-11e9-83d9-d24c72fd8268.png)

**Comment by nemosminer** [comment]
not looking for testers...
