### ISSUE TITLE
Bminer password empty on NiceHash

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#938]
Starting command:
`Bin\NVIDIA-Bminer1431\bminer.exe  -uri cuckaroo29://xxx.NemosMiner:@grincuckaroo29.eu.nicehash.com:3371 -max-temperature 94 -devices 0,1,2,3,4 -api 127.0.0.1:4068`

Another one:
`Bin\NVIDIA-Bminer1431\bminer.exe  -uri beam://xxx.NemosMiner:@beam.eu.nicehash.com:3370 -max-temperature 94 -devices 0,1,2,3,4 -api 127.0.0.1:4068`

After the `NemosMiner:` there is nothing. `x` should be there when using NiceHash.

![image](https://user-images.githubusercontent.com/1230402/52887171-1255e880-3177-11e9-95e3-343b43847088.png)

**Comment by borzaka** [comment]
This is how not an issue?

Something is wrong with this:
`$Pass = If ($Pools.($Algo).Pass -like "*,*") {$Pools.($Algo).Pass.ToString().replace(',','%2C')} else {$Pass}`
or with this:
`Arguments = "$($Commands.$_)$($Pools.($Algo).User):$($Pass)@$($Pools.($Algo).Host):$($Pools.($Algo).Port) -max-temperature 94 -devices $($Config.SelGPUCC) -api 127.0.0.1:$Port"`
in _Bminer.ps1_

Because the `$Pass` is empty in the end.

**Comment by nemosminer** [comment]
it just works

**Comment by borzaka** [comment]
Luckily...
If NiceHash or Bminer changes something how they parse/check the password field, this could broke.

**Comment by MrPlusGH** [comment]
Fixed
https://github.com/nemosminer/NemosMiner/commit/b24754a73329f1bdd264489acbb5d33d1048856d
