### ISSUE TITLE
ccminerKlausTR32 out of memory error after update

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#940]
After this commit, I'am having trouble with this miner. e4dc33f30e30236cc0b8059c96fe34e4448da6bf

5x 1080 Ti
![ccminerklaustr32_out_of_memory](https://user-images.githubusercontent.com/1230402/52900661-c5b2f180-31f8-11e9-8096-b79ad749f9d3.png)

**Comment by nemosminer** [comment]
then add 12.5 you seem capable
