### ISSUE TITLE
Added NiceHash MTP support

### ISSUE THREAD

**Issue by MrPlusGH** [nemosminer/NemosMiner#941]
@nemosminer 
Just added NiceHash MTP support
Required to filter out NH from CD and ccminermtp

**Comment by nemosminer** [comment]
thankyou

**Comment by borzaka** [comment]
Guys, the ccminermtpnh and the ccminermtp miner are not showing up in the list, unless I delete these lines:
`If ($Pools.($Algo).Host -notlike "*nicehash*") {return}`
and
`If ($Pools.($Algo).Host -like "*nicehash*") {return}`
