### ISSUE TITLE
Fixing multiminer script

### ISSUE THREAD

**Issue by sinnx3** [nemosminer/NemosMiner#951]
Whenever I manually try to fix the batch script in the variables.xml it gets overwritten and the benchmark never completes because miner crashes due to the defaults used/being overwritten. Any way to fix?

by removing --gpu-batchsize=210 I get the script to work fine standalone but whenever it's edited in nemosminer it gets overwritten and crashes due to being re-added.
![cmd_2ucxf0dcet](https://user-images.githubusercontent.com/3137441/53649026-ede21d80-3c06-11e9-9674-9f01e7d057f7.png)

![cmd_vaqkeyyxja](https://user-images.githubusercontent.com/3137441/53648860-8b891d00-3c06-11e9-93a7-08db9ce20440.png)

**Comment by nemosminer** [comment]
go into miners folder find MultiMiner.ps1 edit it with powershell or visual studio code.

Find and Change:

$Commands = [PSCustomObject]@{
    "argon2d4096" = " --use-gpu=CUDA --gpu-batchsize=210 " #Argon2d4096 

to suit your needs then save file and re reun NemosMiner it will use your new settings..

Note: with Default setting/current setting its working for me on 1070 1070ti
