### ISSUE TITLE
ccminermtp - wrong arguments

### ISSUE THREAD

**Issue by borzaka** [nemosminer/NemosMiner#953]
![image](https://user-images.githubusercontent.com/1230402/53680019-73cc9a00-3cd5-11e9-9bb7-2ddec7dfd59e.png)

`Bin\NVIDIA-ccminermtp11141\ccminer.exe --cpu-priority 4 -N 3 -R 1 -b 4068 -o stratum+tcp://mtp.mine.zergpool.com:3000 -a MTP -u WALLET -p ID=NemosMiner,c=BTC -d 0,1,2,3`

**Comment by nemosminer** [comment]
nope all is well and correct

**Comment by borzaka** [comment]
Now it works fine. I don't know what happend :(

**Comment by nemosminer** [comment]
: )
