### ISSUE TITLE
MultiMiner crashes

### ISSUE THREAD

**Issue by szentigrad3** [nemosminer/NemosMiner#959]
the cmd box opens for a second then closes

**Comment by nemosminer** [comment]
tested working well ..

Made for & Tested with 6x1070 6x1070ti 6x1080 6x1080ti 6x1660ti 6x2060 6x2070 6x2080 6x2080ti(users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards

**Comment by nemosminer** [comment]
in optional miners folder find MultiMiner.ps1 edit it:

Change:  --gpu-batchsize=512 -t 2

to:   --gpu-batchsize=210 -t 1 

Should fix it for you... what gpu/gpu's are you running?
