### ISSUE TITLE
BrainPlus on hashrate_last24h_shared won't work

### ISSUE THREAD

**Issue by MrPlusGH** [nemosminer/NemosMiner#960]
Hi Nemo,
I've seen the change made in BrainPlus for ZergPool using hashrate_last24h_shared

This won't work has it will be comparing non relative values with the current estimate.
What you're trying to do kind of make sense but would need more thinking.

+MrPlus

**Comment by nemosminer** [comment]
ok cheers i'll change it

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/commit/275350a8782393268b2d4af51796f2cc547fe2af
