### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by ghostofiht** [nemosminer/NemosMiner#962]
Hello, I support open source community with my logo design contributions. I've seen a great project like Nemos Minner doesn't have a logo yet. I have a great logo design idea for Nemos Miner. Would you like to see this?

**Comment by nemosminer** [comment]
sure

**Comment by ghostofiht** [comment]
The design is as follows. Feel free to tell me if you have any modification request on the design. Your ideas are valuable to me.

![nemosminner](https://user-images.githubusercontent.com/42060713/55762279-0bf33700-5a6b-11e9-806b-25c7cc5d376a.jpg)

**Comment by nemosminer** [comment]
i don't like it sorry its miner not minner..

**Comment by nemosminer** [comment]
sorry you must of put a alot of time into this. thank you for trying i mostly didnt like the yellow.. if you have any more designs feel free to post them

**Comment by ghostofiht** [comment]
@nemosminer Of course, Do you have any ideas for design? Does the word "Nemos" mean anything? Which feature of NemosMiner do you want to emphasize in design? You can help me by answering these questions.

**Comment by nemosminer** [comment]
thanks for trying
