### ISSUE TITLE
Faster CCminer MTP

### ISSUE THREAD

**Issue by UselessGuru** [nemosminer/NemosMiner#979]
https://github.com/zcoinofficial/ccminer/releases

**Comment by grantemsley** [comment]
@UselessGuru This repo is pretty much done since nemosminer lost his 2fa key.  New one is at https://github.com/Minerx117/NemosMiner

**Comment by Minerx117** [comment]
@UselessGuru  done few days ago.. https://github.com/Minerx117/NemosMiner

**Comment by UselessGuru** [comment]
Thank you very much!
